/**
 * Canonical technology taxonomy: categories, capabilities and architecture
 * slots. Extensible: add a category or capability here and the retrieval,
 * pipeline classification and UI pick it up automatically.
 */
import type { ArchitectureGroup } from "./types";

export interface CategoryDef {
  id: string;
  label: string;
  parent?: string;
  description: string;
}

const C = (id: string, label: string, description: string, parent?: string): CategoryDef => ({
  id,
  label,
  description,
  parent,
});

export const CATEGORIES: CategoryDef[] = [
  C("ai-models", "AI Models", "Foundation and task models offered as products or weights"),
  C("ai-infrastructure", "AI Infrastructure", "Serving, GPU clouds, model hosting, inference gateways"),
  C("ai-agents", "AI Agents", "Agent frameworks and agent platforms"),
  C("ai-orchestration", "AI Orchestration", "LLM application frameworks, prompt/flow orchestration"),
  C("embeddings", "Embeddings", "Embedding models and embedding APIs"),
  C("vector-databases", "Vector Databases", "Vector indexes and similarity search stores"),
  C("databases", "Databases", "General purpose data stores"),
  C("sql-databases", "SQL Databases", "Relational databases and managed Postgres/MySQL", "databases"),
  C("nosql-databases", "NoSQL Databases", "Document, key-value, wide-column and graph stores", "databases"),
  C("caching", "Caching", "In-memory caches and CDN-adjacent caches"),
  C("search", "Search", "Full-text and hybrid search engines"),
  C("analytics", "Analytics", "Product and web analytics"),
  C("data-warehouses", "Data Warehouses", "Analytical column stores"),
  C("data-lakes", "Data Lakes", "Lakehouse formats and lake platforms"),
  C("data-engineering", "Data Engineering", "Pipelines, orchestration, transformation"),
  C("etl", "ETL / ELT", "Connectors and transformation tools", "data-engineering"),
  C("streaming", "Streaming", "Event streaming and stream processing"),
  C("queues", "Queues / Messaging", "Message brokers, task queues and background jobs"),
  C("backend-frameworks", "Backend Frameworks", "Server frameworks and API frameworks"),
  C("frontend-frameworks", "Frontend Frameworks", "Web UI frameworks and meta-frameworks"),
  C("mobile", "Mobile", "iOS, Android and cross-platform mobile"),
  C("desktop", "Desktop", "Desktop application frameworks"),
  C("languages", "Languages", "Programming languages"),
  C("runtimes", "Runtimes", "Language runtimes"),
  C("apis", "APIs", "API styles, tooling and public APIs"),
  C("api-gateways", "API Gateways", "Gateways, rate limiting and API management"),
  C("authentication", "Authentication", "Identity, login and session management"),
  C("authorization", "Authorization", "Permissions and policy engines"),
  C("payments", "Payments", "Payment processing"),
  C("billing", "Billing", "Subscriptions, metering and invoicing"),
  C("cloud-platforms", "Cloud Platforms", "Hyperscalers and developer clouds"),
  C("compute", "Compute", "Virtual machines and bare metal"),
  C("serverless", "Serverless", "Functions as a service"),
  C("containers", "Containers", "Container build and runtime"),
  C("kubernetes", "Kubernetes", "Kubernetes distributions and tooling"),
  C("storage", "Storage", "Object and block storage"),
  C("cdn-edge", "CDN / Edge", "Content delivery and edge compute"),
  C("networking", "Networking", "Load balancing, VPN, service mesh"),
  C("observability", "Observability", "Metrics, logs and traces in one platform"),
  C("logging", "Logging", "Log aggregation", "observability"),
  C("tracing", "Tracing", "Distributed tracing", "observability"),
  C("monitoring", "Monitoring", "Uptime and metrics monitoring", "observability"),
  C("security", "Security", "Application and infrastructure security"),
  C("secrets", "Secrets", "Secret and key management"),
  C("ci-cd", "CI/CD", "Build and deployment automation"),
  C("developer-tools", "Developer Tools", "IDEs, editors, coding assistants"),
  C("testing", "Testing", "Test frameworks and QA tooling"),
  C("feature-flags", "Feature Flags", "Flags and experimentation"),
  C("cms", "CMS", "Content management"),
  C("email", "Email", "Transactional and marketing email"),
  C("messaging", "Messaging", "Chat, SMS and communication APIs"),
  C("notifications", "Notifications", "Push and multi-channel notifications"),
  C("maps", "Maps", "Maps and geospatial"),
  C("video", "Video", "Video processing, streaming and generation"),
  C("audio", "Audio", "Audio processing and generation"),
  C("image", "Image", "Image processing and generation"),
  C("speech", "Speech", "Speech to text and text to speech"),
  C("ocr", "OCR", "Document and text recognition"),
  C("web-scraping", "Web Scraping", "Crawling and extraction"),
  C("browser-automation", "Browser Automation", "Headless browsers and automation"),
  C("search-apis", "Search APIs", "Web search APIs for applications and agents"),
  C("workflow-automation", "Workflow Automation", "Durable workflows and no-code automation"),
  C("infrastructure-as-code", "Infrastructure as Code", "Declarative infrastructure"),
  C("hosting", "Hosting", "Application hosting platforms"),
  C("dns", "DNS", "Domain and DNS management"),
  C("source-control", "Source Control", "Git hosting and code review"),
  C("package-managers", "Package Managers", "Dependency management and registries"),
  C("realtime", "Realtime", "WebSockets, presence and live sync"),
  C("orm", "ORM / Data Access", "Object relational mappers and query builders"),
  C("ml-platforms", "ML Platforms", "Training, experiment tracking and MLOps"),
  C("gpu-compute", "GPU Compute", "GPU clouds and accelerators"),
  C("local-ai", "Local AI", "On-device and self-hosted inference"),
  C("documents", "Documents / PDF", "Document parsing and generation"),
  C("scheduling", "Scheduling / Cron", "Scheduled jobs"),
  C("ecommerce", "E-commerce", "Commerce platforms"),
  C("compliance", "Compliance", "Compliance automation"),
];

export const CATEGORY_IDS = new Set(CATEGORIES.map((c) => c.id));
export const categoryLabel = (id: string) => CATEGORIES.find((c) => c.id === id)?.label ?? id;

/**
 * Capabilities are what a requirement asks for and what a technology provides.
 * Slot ids in the requirement graph map 1:1 to capabilities.
 */
export interface CapabilityDef {
  id: string;
  label: string;
  group: ArchitectureGroup;
  description: string;
  /** Categories whose members plausibly provide this capability. */
  categories: string[];
  /** Question used for intent extraction (Noul). */
  needQuestion: string;
  needYes: string;
  needNo: string;
  /** Retrieval query text. */
  query: string;
  /** Always included in a full product stack regardless of extraction. */
  baseline?: boolean;
  dependsOn?: string[];
}

const K = (
  id: string,
  label: string,
  group: ArchitectureGroup,
  description: string,
  categories: string[],
  needQuestion: string,
  needYes: string,
  needNo: string,
  query: string,
  extra: Partial<CapabilityDef> = {},
): CapabilityDef => ({ id, label, group, description, categories, needQuestion, needYes, needNo, query, ...extra });

export const CAPABILITIES: CapabilityDef[] = [
  // EXPERIENCE
  K("web-frontend", "Web frontend", "EXPERIENCE", "A browser-based user interface", ["frontend-frameworks"],
    "Does the product described in `request` need a web (browser) user interface?",
    "Users interact through a website or web app, or the platform is unspecified and a web app is the natural default",
    "The request explicitly rules out a web UI, or it is purely a backend, CLI, pipeline, or native-only product",
    "web frontend framework for building the user interface", { baseline: true }),
  K("ios-client", "iOS client", "EXPERIENCE", "A native iOS application", ["mobile"],
    "Does the product described in `request` need a native iOS or iPhone app?",
    "iOS, iPhone, iPad, App Store or 'mobile app for Apple' is stated or clearly implied",
    "No iOS or mobile requirement is stated",
    "native iOS application development framework Swift"),
  K("android-client", "Android client", "EXPERIENCE", "A native Android application", ["mobile"],
    "Does the product described in `request` need a native Android app?",
    "Android or Google Play is stated, or 'mobile app' is stated without naming a platform",
    "No Android or mobile requirement is stated",
    "native Android application development framework Kotlin"),
  K("cross-platform-mobile", "Cross-platform mobile", "EXPERIENCE", "One codebase for iOS and Android", ["mobile"],
    "Would the product described in `request` be best served by a single cross-platform mobile codebase covering both iOS and Android?",
    "Both iOS and Android are wanted, or 'mobile app' is wanted with a small team or budget where one codebase is sensible",
    "Only one mobile platform is wanted, native performance is explicitly demanded, or no mobile app is wanted",
    "cross-platform mobile framework React Native Flutter"),
  K("desktop-client", "Desktop client", "EXPERIENCE", "A desktop application", ["desktop"],
    "Does the product described in `request` need a desktop application (Windows, macOS or Linux app)?",
    "A desktop app, menu bar app, or installable native desktop client is stated",
    "No desktop application is mentioned",
    "desktop application framework"),
  K("cms", "Content management", "EXPERIENCE", "Editorial content management", ["cms"],
    "Does the product described in `request` need a content management system for editors to publish content (articles, pages, marketing content)?",
    "Non-developers need to author and publish content such as articles, blog posts or marketing pages",
    "Content is user generated, machine generated, or there is no editorial content",
    "headless CMS content management"),

  // API
  K("api-backend", "API / backend", "API", "The application server or API layer", ["backend-frameworks"],
    "Does the product described in `request` need its own backend or API service?",
    "Almost every product with users, data, or AI features needs a backend or API layer",
    "The request is purely a static site or purely a data pipeline with no application server",
    "backend API framework web server", { baseline: true }),
  K("authentication", "Authentication", "API", "User identity and login", ["authentication"],
    "Does the product described in `request` have user accounts or logins?",
    "The product has users, accounts, teams, subscriptions, personalization or any per-user data",
    "The product is anonymous, an internal batch pipeline, or explicitly has no accounts",
    "user authentication login identity provider", { baseline: true }),
  K("authorization", "Authorization", "API", "Fine-grained permissions", ["authorization"],
    "Does the product described in `request` need fine-grained permissions such as roles, organizations, multi-tenant access control or policy enforcement beyond simple login?",
    "Roles, admin/member distinctions, organizations, workspaces, tenants, sharing permissions or compliance-driven access control are stated or clearly implied (e.g. B2B SaaS, healthcare, finance)",
    "A simple single-user or single-role product",
    "authorization permissions policy engine RBAC"),
  K("realtime", "Realtime delivery", "API", "Live updates to clients", ["realtime"],
    "Does the product described in `request` need realtime or live updates pushed to clients (websockets, presence, live feeds, collaboration, chat)?",
    "Real-time, live, streaming updates, chat, collaboration, presence, multiplayer or instant notifications are stated or clearly implied",
    "Data can be fetched on page load or refresh without live push",
    "realtime websockets pub/sub live updates presence"),
  K("telephony", "Telephony / voice calls", "API", "Placing and receiving phone calls and real-time voice sessions", ["messaging", "speech", "realtime"],
    "Does the product described in `request` place or receive phone calls, or run live real-time voice or video sessions with users?",
    "Phone calls, call centers, IVR, a voice agent that answers the phone, live voice conversations, or video calls are stated",
    "No calling or live voice/video sessions",
    "telephony phone calls voice agent real-time voice infrastructure SIP WebRTC"),
  K("api-gateway", "API gateway", "API", "Public API management", ["api-gateways"],
    "Does the product described in `request` expose a public developer API to third parties that needs rate limiting, keys and API management?",
    "The product is an API product, developer platform or must expose APIs to external developers or partners",
    "The API is only consumed by the product's own clients",
    "API gateway rate limiting API keys management"),
  K("payments", "Payments", "API", "Accepting payments", ["payments", "billing"],
    "Does the product described in `request` accept payments or sell subscriptions?",
    "Payments, checkout, subscriptions, billing, marketplace transactions, SaaS pricing tiers, or e-commerce are stated or clearly implied",
    "No money changes hands inside the product",
    "payment processing subscriptions billing checkout"),
  K("email", "Transactional email", "API", "Sending email", ["email"],
    "Does the product described in `request` need to send email (transactional email such as sign-up confirmations, receipts, digests or notifications)?",
    "Users have accounts (needing verification/reset emails), the product sends digests, newsletters, receipts or alerts by email",
    "The product has no users to email and no email features",
    "transactional email API sending email"),
  K("notifications", "Push notifications", "API", "Mobile and multi-channel notifications", ["notifications", "messaging"],
    "Does the product described in `request` need push notifications, SMS, or multi-channel notifications beyond email?",
    "Mobile push, SMS, in-app notification centers, or alerting users across channels is stated or clearly implied (e.g. a mobile social or news app)",
    "No notification features beyond email",
    "push notifications SMS multi-channel notification service"),

  // DATA
  K("relational-db", "Relational persistence", "DATA", "Primary transactional database", ["sql-databases"],
    "Does the product described in `request` need a primary relational (SQL) database for transactional application data such as users, accounts, orders or configuration?",
    "The product stores structured application data with relationships and needs consistency; this is the default for nearly all products with users",
    "The request explicitly wants a document/NoSQL primary store, or there is no persistent application data",
    "relational SQL database PostgreSQL transactional persistence", { baseline: true }),
  K("nosql-db", "Document / NoSQL store", "DATA", "Flexible-schema document or key-value store", ["nosql-databases"],
    "Does the product described in `request` specifically call for a NoSQL, document, key-value, wide-column or graph database as a primary or secondary store?",
    "NoSQL, MongoDB, DynamoDB, Firestore, document store, graph database, or a schemaless/flexible data model is explicitly requested, or the request says to replace Firebase/Firestore-style storage with an equivalent",
    "No NoSQL requirement; a relational database is enough",
    "NoSQL document database key-value store"),
  K("cache", "Cache", "DATA", "In-memory caching and ephemeral state", ["caching"],
    "Does the product described in `request` need an in-memory cache or ephemeral store (sessions, rate limits, hot data, leaderboards, pub/sub)?",
    "High traffic, realtime features, rate limiting, sessions at scale, feeds, leaderboards, background job queues, or expensive computations that benefit from caching are stated or clearly implied",
    "A small, low-traffic product where the primary database alone is sufficient",
    "in-memory cache Redis key-value session store"),
  K("object-storage", "Object storage", "DATA", "Files, media and blobs", ["storage"],
    "Does the product described in `request` store user-uploaded files, images, video, audio, documents or other binary media?",
    "Uploads, images, media, video, audio, PDFs, documents, exports, backups, or generated assets are part of the product",
    "The product handles only structured text data",
    "object storage S3-compatible file uploads blobs"),
  K("vector-db", "Vector retrieval", "DATA", "Similarity search over embeddings", ["vector-databases"],
    "Does the product described in `request` need vector similarity search over embeddings (semantic search, RAG, recommendations, deduplication)?",
    "RAG, semantic search, similar items, embeddings, AI assistants over documents/knowledge bases, personalization by similarity, or summarization over large corpora that must be retrieved",
    "No semantic retrieval; AI features (if any) operate on the current input only",
    "vector database similarity search embeddings index", { dependsOn: ["embeddings"] }),
  K("search-engine", "Full-text search", "DATA", "Keyword search over content", ["search"],
    "Does the product described in `request` need full-text keyword search over its content (search box over articles, products, listings, messages)?",
    "Users search a catalog, articles, documents, listings, or messages by keyword, or a search feature is stated",
    "No user-facing search, or search over a tiny data set the primary database can handle",
    "full-text search engine keyword search typo tolerance"),
  K("analytics", "Product analytics", "DATA", "Usage analytics", ["analytics"],
    "Does the product described in `request` need product or web analytics (tracking usage, funnels, events, dashboards about users)?",
    "Analytics, metrics about users, growth, A/B testing, or a consumer product where usage insight is expected",
    "Internal tooling or a pipeline where user analytics are irrelevant",
    "product analytics event tracking dashboards"),
  K("data-warehouse", "Analytical warehouse", "DATA", "Analytical column store", ["data-warehouses", "data-lakes"],
    "Does the product described in `request` need an analytical data warehouse or lakehouse for large-scale reporting, BI or analytics workloads separate from the transactional database?",
    "Large-scale analytics, BI, reporting over big data, data science, ML feature pipelines, or 'data platform' is stated or clearly implied",
    "Reporting needs are small enough for the transactional database",
    "data warehouse analytical OLAP columnar"),
  K("orm", "Data access layer", "DATA", "ORM or query builder", ["orm"],
    "Would the product described in `request` benefit from an ORM or typed query builder for its application database?",
    "There is an application backend with a relational or document database and application developers will write data access code",
    "There is no application database, or the language/ecosystem has no need for a separate ORM",
    "ORM query builder database schema migrations", { dependsOn: ["relational-db"] }),

  // AI
  K("llm-inference", "LLM inference", "AI", "Large language model access", ["ai-models", "ai-infrastructure"],
    "Does the product described in `request` use large language models or generative AI (summaries, chat, generation, classification, agents, extraction)?",
    "AI, LLM, GPT, generative, summaries, chatbot, assistant, agent, copilot, RAG, content generation or text understanding is stated or clearly implied",
    "No generative AI features",
    "large language model API inference chat completion"),
  K("embeddings", "Embeddings", "AI", "Text or multimodal embeddings", ["embeddings", "ai-models"],
    "Does the product described in `request` need to compute embeddings (vector representations) of text, images or other content?",
    "Semantic search, RAG, recommendations, similarity, clustering, deduplication or a knowledge base over documents",
    "AI features do not involve retrieval or similarity",
    "text embedding model API"),
  K("ai-orchestration", "AI orchestration", "AI", "LLM application framework", ["ai-orchestration", "ai-agents"],
    "Does the product described in `request` involve multi-step AI workflows, agents, tool use, RAG pipelines or chains that benefit from an orchestration framework?",
    "Agents, pipelines, RAG, tool calling, multi-step reasoning, autonomous workflows or several AI stages",
    "A single direct model call, or no AI",
    "LLM orchestration framework agents RAG pipeline", { dependsOn: ["llm-inference"] }),
  K("ai-evaluation", "AI evaluation & observability", "AI", "LLM tracing and evaluation", ["observability", "ml-platforms"],
    "Does the product described in `request` run AI features in production at a scale or importance where tracing, evaluation and monitoring of model calls is needed?",
    "AI is central to the product, it processes large volumes, or reliability/compliance is emphasized",
    "AI is a minor feature or a prototype",
    "LLM observability tracing evaluation prompt monitoring", { dependsOn: ["llm-inference"] }),
  K("gpu-compute", "GPU compute", "AI", "Serverless or dedicated GPUs", ["gpu-compute", "ai-infrastructure"],
    "Does the product described in `request` need its own GPU compute (running open models, fine-tuning, training, video/image generation, or self-hosted inference) rather than only calling hosted model APIs?",
    "Open-weight models, self-hosted inference, fine-tuning, training, NVIDIA hardware, local-first AI, or heavy media generation is stated",
    "Hosted model APIs are sufficient",
    "GPU cloud serverless GPU inference hosting"),
  K("local-inference", "Local inference", "AI", "On-device or self-hosted model serving", ["local-ai", "ai-infrastructure"],
    "Does the product described in `request` need to run AI models locally, on-device, offline, on the user's own hardware, or self-hosted rather than through a hosted API?",
    "Local-first, offline, on-device, privacy-preserving, self-hosted models, 'runs on my machine', NVIDIA/consumer GPU is stated",
    "Hosted APIs are acceptable",
    "local LLM inference server run models locally"),
  K("speech", "Speech", "AI", "Speech to text or text to speech", ["speech", "audio"],
    "Does the product described in `request` involve speech: transcription, voice input, voice agents, or text to speech?",
    "Voice, audio transcription, meetings, calls, podcasts, dictation, voice assistants or TTS",
    "No speech features",
    "speech to text transcription text to speech voice API"),
  K("image-generation", "Image generation", "AI", "Generating or editing images", ["image", "ai-models"],
    "Does the product described in `request` generate or edit images with AI?",
    "Image generation, thumbnails, avatars, design generation, or visual content creation with AI",
    "No AI image generation",
    "image generation model API"),
  K("video-generation", "Video generation & processing", "AI", "Generating, editing or processing video", ["video", "ai-models"],
    "Does the product described in `request` generate, edit, transcode, or stream video?",
    "Video generation, video pipeline, editing, transcoding, live streaming, or video delivery",
    "No video features",
    "video generation processing transcoding streaming API"),
  K("ocr-documents", "Document understanding", "AI", "OCR and document parsing", ["ocr", "documents"],
    "Does the product described in `request` need to parse, OCR, or extract data from documents, PDFs, invoices, forms or scans?",
    "PDFs, invoices, receipts, contracts, forms, scanned documents, or document ingestion is stated",
    "No document parsing",
    "OCR document parsing PDF extraction API"),
  K("web-search-api", "Web search / crawling", "AI", "Live web data for the app or agents", ["search-apis", "web-scraping"],
    "Does the product described in `request` need to search or crawl the live web (news, research, agents that browse, web data collection)?",
    "News aggregation, research agents, competitor monitoring, web crawling, scraping, or live web information",
    "The product only uses its own data",
    "web search API crawler scraping live web data"),

  // INGESTION
  K("queue", "Queue / messaging", "INGESTION", "Asynchronous work distribution", ["queues", "streaming"],
    "Does the product described in `request` need a message queue or job queue for asynchronous or background processing?",
    "Ingestion pipelines, batch processing, AI jobs that outlive a request, email sending at volume, webhooks, high traffic, or workers are stated or clearly implied",
    "All work can complete within a request and there is no background processing",
    "message queue background jobs task queue"),
  K("workers", "Background workers", "INGESTION", "Durable background job execution", ["queues", "workflow-automation", "serverless"],
    "Does the product described in `request` need background workers or durable job execution (long running tasks, retries, scheduled processing, pipelines)?",
    "Processing content in the background, AI pipelines, ingestion, exports, retries, or long-running work",
    "No background work",
    "background worker durable execution job processing", { dependsOn: ["queue"] }),
  K("scheduler", "Scheduled jobs", "INGESTION", "Cron and recurring tasks", ["scheduling", "workflow-automation"],
    "Does the product described in `request` need scheduled or recurring jobs (cron, hourly/daily ingestion, digests, cleanups)?",
    "Recurring ingestion, daily digests, periodic sync, polling sources, or 'every N minutes' is stated or implied (e.g. a news or monitoring product)",
    "No recurring jobs",
    "cron scheduled jobs recurring tasks"),
  K("streaming", "Event streaming", "INGESTION", "High-throughput event streams", ["streaming"],
    "Does the product described in `request` need high-throughput event streaming (Kafka-style) rather than a simple job queue?",
    "Event-driven architecture at large scale, stream processing, event sourcing, IoT/telemetry firehose, 100k+ events per hour with multiple consumers",
    "Volume is modest or a simple queue is enough",
    "event streaming platform Kafka stream processing"),
  K("etl", "Data pipelines / ETL", "INGESTION", "Connectors and transformations", ["etl", "data-engineering"],
    "Does the product described in `request` need ETL/ELT data pipelines or orchestration to move and transform data between systems?",
    "Data platform, analytics warehouse loading, syncing many sources, dbt-style transformation, or 'data pipeline' is stated",
    "No data movement beyond the app's own reads and writes",
    "data pipeline orchestration ETL ELT connectors"),
  K("browser-automation", "Browser automation", "INGESTION", "Headless browsing", ["browser-automation", "web-scraping"],
    "Does the product described in `request` need to automate a browser or scrape JavaScript-heavy sites?",
    "Scraping dynamic sites, automating web tasks, browsing agents, or end-to-end web automation",
    "No browser automation",
    "headless browser automation scraping"),

  // INFRASTRUCTURE
  K("hosting", "Deployment / hosting", "INFRASTRUCTURE", "Where the application runs", ["hosting", "cloud-platforms", "serverless", "compute"],
    "Does the product described in `request` need to be deployed and hosted somewhere?",
    "Any product that runs for users needs hosting",
    "The request is only about a local tool that never gets deployed",
    "application hosting deployment platform cloud", { baseline: true }),
  K("container-orchestration", "Container orchestration", "INFRASTRUCTURE", "Kubernetes or equivalent", ["kubernetes", "containers"],
    "Does the product described in `request` need container orchestration such as Kubernetes (many services, self-hosting at scale, GPU fleets, strict infrastructure control)?",
    "Kubernetes is requested, the product self-hosts many services, runs GPU clusters, or has a platform team and large scale",
    "A managed platform, serverless or a single container host is sufficient (small teams, MVPs)",
    "Kubernetes container orchestration managed cluster"),
  K("cdn", "CDN / edge", "INFRASTRUCTURE", "Content delivery and edge network", ["cdn-edge"],
    "Does the product described in `request` benefit from a CDN or edge network (global users, media delivery, high traffic, DDoS protection)?",
    "Global audience, media/video delivery, high traffic, public web product, or latency is emphasized",
    "Internal tool, tiny audience, or the hosting platform already includes a CDN and nothing extra is needed",
    "CDN edge network global delivery DDoS protection"),
  K("monitoring", "Monitoring & observability", "INFRASTRUCTURE", "Errors, metrics, logs", ["observability", "monitoring", "logging", "tracing"],
    "Does the product described in `request` need production monitoring (error tracking, logs, metrics, uptime)?",
    "Any production product serving real users, especially with scale, compliance or reliability requirements",
    "A throwaway prototype or a local-only tool",
    "error tracking monitoring observability logs metrics", { baseline: true }),
  K("ci-cd", "CI/CD & source control", "INFRASTRUCTURE", "Code hosting and delivery pipeline", ["ci-cd", "source-control"],
    "Does the product described in `request` need source control and CI/CD for a team to build and ship it?",
    "Any product built by developers and deployed more than once",
    "A one-off script",
    "git hosting CI/CD pipeline continuous deployment", { baseline: true }),
  K("infrastructure-as-code", "Infrastructure as code", "INFRASTRUCTURE", "Declarative infrastructure", ["infrastructure-as-code"],
    "Does the product described in `request` warrant infrastructure as code (Terraform-style) because it uses raw cloud resources across many services, needs reproducible environments, or has compliance requirements?",
    "AWS/GCP/Azure with several services, Kubernetes, compliance (HIPAA/SOC 2/PCI), multiple environments, or a platform team",
    "A fully managed platform (Vercel/Railway/Supabase style) where infrastructure is implicit, or a tiny MVP",
    "infrastructure as code Terraform provisioning"),
  K("secrets", "Secrets management", "INFRASTRUCTURE", "Keys and secrets", ["secrets", "security"],
    "Does the product described in `request` need dedicated secrets management (beyond platform environment variables) due to compliance, many services, or self-hosting?",
    "Compliance requirements, many services, Kubernetes, or self-hosted infrastructure",
    "A managed platform's environment variables are sufficient",
    "secrets management vault key management"),
  K("feature-flags", "Feature flags", "INFRASTRUCTURE", "Flags and experimentation", ["feature-flags"],
    "Does the product described in `request` need feature flags or experimentation (gradual rollouts, A/B tests, kill switches)?",
    "A/B testing, experimentation, staged rollouts, large user base, or growth-focused consumer product is stated",
    "A small product where flags are unnecessary",
    "feature flags experimentation rollouts"),
  K("compliance-automation", "Compliance automation", "INFRASTRUCTURE", "Audit and compliance tooling", ["compliance", "security"],
    "Does the product described in `request` have regulatory compliance requirements (HIPAA, SOC 2, PCI DSS, GDPR, ISO 27001, FedRAMP) that warrant compliance automation tooling?",
    "HIPAA, SOC 2, PCI, GDPR, healthcare, banking, fintech, government or 'compliance' is stated",
    "No regulated data",
    "compliance automation SOC 2 HIPAA audit"),
  K("dns", "DNS & domains", "INFRASTRUCTURE", "Domain and DNS management", ["dns", "cdn-edge"],
    "Does the product described in `request` need DNS and domain management as an explicit component (custom domains for tenants, many domains, or DNS-level routing)?",
    "Custom domains per customer, multi-domain, DNS-based routing or white-labeling is stated",
    "A single domain handled by the hosting provider",
    "DNS domain management"),
  K("maps", "Maps & geospatial", "INFRASTRUCTURE", "Maps and location", ["maps"],
    "Does the product described in `request` need maps, geocoding, routing or location features?",
    "Maps, locations, delivery, logistics, nearby search, geofencing or travel",
    "No location features",
    "maps geocoding location API"),
  K("ecommerce", "Commerce platform", "API", "Catalog, cart and checkout", ["ecommerce"],
    "Does the product described in `request` need an e-commerce platform (product catalog, cart, checkout, orders) rather than just accepting payments?",
    "An online store, marketplace with product catalog, or 'e-commerce' is stated",
    "Only subscriptions or single payments are needed",
    "e-commerce platform headless commerce catalog cart"),
  K("testing", "Testing", "INFRASTRUCTURE", "Automated testing", ["testing"],
    "Does the product described in `request` emphasize quality, reliability or compliance such that an explicit end-to-end testing tool belongs in the recommended stack?",
    "Reliability, compliance, healthcare, finance, large user base, or 'production-grade' is emphasized",
    "A prototype, MVP or the request does not emphasize testing",
    "end-to-end testing framework"),
];

export const CAPABILITY_BY_ID = new Map(CAPABILITIES.map((c) => [c.id, c]));
export const CAPABILITY_IDS = CAPABILITIES.map((c) => c.id);

export const GROUP_ORDER: ArchitectureGroup[] = ["EXPERIENCE", "API", "DATA", "AI", "INGESTION", "INFRASTRUCTURE"];

/** Extra capability ids technologies may declare that are not slots on their own. */
export const AUXILIARY_CAPABILITIES = [
  "billing",
  "source-control",
  "language",
  "runtime",
  "package-manager",
  "ide",
  "coding-assistant",
  "logging",
  "tracing",
  "networking",
  "service-mesh",
  "vpn",
  "ml-training",
  "experiment-tracking",
  "model-hosting",
  "prompt-management",
  "sms",
  "chat-sdk",
  "audio-processing",
  "image-processing",
  "graph-db",
  "time-series-db",
  "sqlite",
  "lakehouse",
  "bi",
  "reverse-etl",
  "cdc",
  "serverless-functions",
  "static-hosting",
  "container-registry",
  "vm-compute",
  "bare-metal",
  "block-storage",
  "object-storage",
  "ddos-protection",
  "waf",
  "backend-as-a-service",
  "database-branching",
  "edge-functions",
  "session-management",
  "sso",
  "mfa",
  "passkeys",
  "reranking",
  "inference-gateway",
  "fine-tuning",
  "gpu-serverless",
];

export const ALL_CAPABILITY_IDS = new Set([...CAPABILITY_IDS, ...AUXILIARY_CAPABILITIES]);

/** Maps yc-oss tags to canonical categories. Unknown tags are kept as tags only. */
export const YC_TAG_MAP: Record<string, string[]> = {
  "Developer Tools": ["developer-tools"],
  "Open Source": [],
  "Infrastructure": ["cloud-platforms"],
  "Databases": ["databases"],
  "Data Engineering": ["data-engineering"],
  "Big Data": ["data-engineering"],
  "Analytics": ["analytics"],
  "API": ["apis"],
  "Artificial Intelligence": ["ai-infrastructure"],
  "AI": ["ai-infrastructure"],
  "Generative AI": ["ai-models"],
  "Machine Learning": ["ml-platforms"],
  "AI Assistant": ["ai-agents"],
  "AIOps": ["observability"],
  "DevOps": ["ci-cd"],
  "DevSecOps": ["security"],
  "Security": ["security"],
  "Cloud Computing": ["cloud-platforms"],
  "Cloud Workload Protection": ["security"],
  "Payments": ["payments"],
  "Fintech": ["payments"],
  "Identity": ["authentication"],
  "Authentication": ["authentication"],
  "Messaging": ["messaging"],
  "Email": ["email"],
  "Video": ["video"],
  "Computer Vision": ["image"],
  "Speech Recognition": ["speech"],
  "Conversational AI": ["ai-agents"],
  "Workflow Automation": ["workflow-automation"],
  "Automation": ["workflow-automation"],
  "Search": ["search"],
  "Observability": ["observability"],
  "Kubernetes": ["kubernetes"],
  "Compliance": ["compliance"],
  "No-code": ["workflow-automation"],
  "Low-code": ["workflow-automation"],
  "E-commerce": ["ecommerce"],
  "Documents": ["documents"],
  "Robotic Process Automation": ["browser-automation"],
  "Data Labeling": ["ml-platforms"],
  "Data Visualization": ["analytics"],
  "Data Science": ["ml-platforms"],
  "Web Development": ["frontend-frameworks"],
  "Mobile": ["mobile"],
  "Design Tools": ["developer-tools"],
  "Testing": ["testing"],
  "Quality Assurance": ["testing"],
  "Vector Databases": ["vector-databases"],
  "Robotics": [],
  "SaaS": [],
  "B2B": [],
};

/** Developer-relevant yc tags used to pick candidates out of the yc dataset. */
export const YC_DISCOVERY_TAGS = new Set([
  "Developer Tools",
  "Infrastructure",
  "Databases",
  "Data Engineering",
  "API",
  "Open Source",
  "AIOps",
  "DevOps",
  "DevSecOps",
  "Cloud Computing",
  "Kubernetes",
  "Observability",
  "Machine Learning",
  "Generative AI",
  "Workflow Automation",
  "Vector Databases",
  "Identity",
  "Authentication",
  "Messaging",
  "Search",
  "Video",
  "Speech Recognition",
  "Payments",
  "Compliance",
  "Testing",
  "Documents",
]);
