import type { Architecture } from "@/lib/types";

/** Markdown summary of an architecture, suitable for a README, a PR or a design doc. */
export function architectureToMarkdown(a: Architecture, url?: string): string {
  const lines: string[] = [];
  lines.push(`# Stack: ${a.request}`, "");
  lines.push(`> ${a.intent.interpretation?.enhancedRequest ?? a.intent.summary}`, "");
  if (url) lines.push(`Interactive version: ${url}`, "");
  const hard = a.intent.constraints.filter((c) => c.severity === "hard");
  if (hard.length) lines.push("**Hard constraints:** " + hard.map((c) => c.label).join(", "), "");
  if (a.assumptions.length) lines.push("**Assumptions:**", ...a.assumptions.map((x) => `- ${x}`), "");
  let group = "";
  for (const c of a.components) {
    if (c.group !== group) {
      group = c.group;
      lines.push(`## ${group.charAt(0) + group.slice(1).toLowerCase()}`, "");
    }
    lines.push(`### ${c.name} — ${c.role}`, "", c.whyHere, "", `*Tradeoff:* ${c.tradeoff}`, "");
    if (c.alternatives.length) lines.push(`*Alternatives:* ${c.alternatives.map((x) => `${x.name} (${x.whenPreferable.replace(/\.$/, "").toLowerCase()})`).join("; ")}`, "");
  }
  const notes = a.issues.filter((i) => i.severity !== "info");
  if (notes.length) lines.push("## Validation notes", "", ...notes.map((i) => `- ${i.message}`), "");
  lines.push(`---`, `Generated by Stack4That · ${a.stats.decisions} decisions over ${a.stats.technologiesSearched} technologies · decided by TypeSafe`);
  return lines.join("\n");
}
