import { t } from "./helper";

export const AI = [
  t("openai", "OpenAI API", {
    company: "OpenAI", type: "api", cats: ["ai-models", "embeddings", "speech", "image"], caps: ["llm-inference", "embeddings", "speech", "image-generation"],
    desc: "GPT model family, embeddings, Whisper speech, image generation and the Responses API with tool use. The broadest hosted model API.",
    site: "https://openai.com/api/", docs: "https://platform.openai.com/docs", pricingUrl: "https://openai.com/api/pricing/",
    deploy: ["managed-cloud"], langs: ["python", "typescript", "java", "go", "csharp"], pricing: "usage-based", free: false, pricingSummary: "Per-token pricing by model", compliance: ["SOC 2", "GDPR"], aliases: ["GPT", "ChatGPT API"], tags: ["hosted-llm"],
  }),
  t("anthropic", "Anthropic Claude", {
    company: "Anthropic", type: "api", cats: ["ai-models", "ai-agents"], caps: ["llm-inference"],
    desc: "Claude model family via the Claude API with long context, tool use, extended thinking and the Claude Agent SDK; strong for coding, agents and careful reasoning.",
    site: "https://www.anthropic.com/api", docs: "https://docs.anthropic.com", pricingUrl: "https://www.anthropic.com/pricing",
    deploy: ["managed-cloud"], clouds: ["aws", "gcp", "azure"], langs: ["python", "typescript"], pricing: "usage-based", pricingSummary: "Per-token pricing by model", compliance: ["SOC 2", "HIPAA", "GDPR"], aliases: ["Claude"], tags: ["hosted-llm", "agents"], icon: "anthropic",
  }),
  t("google-gemini", "Google Gemini API", {
    company: "Google", type: "api", cats: ["ai-models", "embeddings"], caps: ["llm-inference", "embeddings", "image-generation", "video-generation"],
    desc: "Gemini multimodal models via AI Studio or Vertex AI with very long context, native audio/video understanding and Veo/Imagen media generation.",
    site: "https://ai.google.dev", docs: "https://ai.google.dev/gemini-api/docs", pricingUrl: "https://ai.google.dev/pricing",
    deploy: ["managed-cloud"], clouds: ["gcp"], pricing: "usage-based", free: true, pricingSummary: "Free tier in AI Studio, then per-token", compliance: ["SOC 2", "HIPAA", "GDPR"], aliases: ["Gemini", "Google AI Studio"], icon: "googlegemini",
  }),
  t("mistral", "Mistral AI", {
    company: "Mistral AI", type: "api", cats: ["ai-models", "embeddings"], caps: ["llm-inference", "embeddings", "ocr-documents"],
    desc: "European model provider with open-weight and hosted models, OCR and EU data residency.",
    site: "https://mistral.ai", docs: "https://docs.mistral.ai", pricingUrl: "https://mistral.ai/pricing",
    deploy: ["managed-cloud", "self-hosted"], pricing: "usage-based", free: true, regions: ["eu"], compliance: ["GDPR", "SOC 2"], tags: ["open-weights", "eu"], icon: "mistralai",
  }),
  t("cohere", "Cohere", {
    company: "Cohere", type: "api", cats: ["ai-models", "embeddings"], caps: ["llm-inference", "embeddings", "reranking"],
    desc: "Enterprise-focused models with best-in-class embeddings and rerankers for retrieval, deployable in private clouds.",
    site: "https://cohere.com", docs: "https://docs.cohere.com", pricingUrl: "https://cohere.com/pricing",
    deploy: ["managed-cloud", "self-hosted"], clouds: ["aws", "azure", "oracle"], pricing: "usage-based", free: true, compliance: ["SOC 2", "GDPR"], tags: ["enterprise", "rerank"],
  }),
  t("voyage-ai", "Voyage AI", {
    company: "MongoDB", type: "api", cats: ["embeddings"], caps: ["embeddings", "reranking"],
    desc: "High-accuracy embedding and reranking models, including domain-specific code and finance embeddings.",
    site: "https://www.voyageai.com", docs: "https://docs.voyageai.com", pricingUrl: "https://www.voyageai.com/pricing",
    deploy: ["managed-cloud"], pricing: "usage-based", free: true, maturity: "growing", icon: null,
  }),
  t("jina-ai", "Jina AI", {
    company: "Jina AI", type: "api", cats: ["embeddings", "search-apis"], caps: ["embeddings", "reranking", "web-search-api"],
    desc: "Embeddings, rerankers and the Reader/Search APIs that turn web pages into LLM-ready text.",
    site: "https://jina.ai", docs: "https://jina.ai/embeddings/", pricingUrl: "https://jina.ai/pricing",
    deploy: ["managed-cloud", "self-hosted"], pricing: "usage-based", free: true, maturity: "growing", icon: null,
  }),
  t("sentence-transformers", "Sentence Transformers (BGE, E5)", {
    company: "Hugging Face", type: "library", cats: ["embeddings", "local-ai"], caps: ["embeddings", "local-inference"],
    desc: "Run open embedding models such as BGE, E5 and GTE locally in Python or via ONNX/Transformers.js; no API cost and full data control.",
    site: "https://sbert.net", docs: "https://sbert.net/docs/quickstart.html", repo: "https://github.com/UKPLab/sentence-transformers", oss: true, license: "Apache-2.0",
    deploy: ["self-hosted", "on-device"], langs: ["python", "typescript"], free: true, aliases: ["BGE", "bge-small", "E5"], tags: ["local", "open-weights"], icon: "huggingface",
  }),
  t("hugging-face", "Hugging Face", {
    company: "Hugging Face", type: "platform", cats: ["ai-models", "ai-infrastructure", "ml-platforms"], caps: ["llm-inference", "embeddings", "model-hosting", "gpu-compute"],
    desc: "Model hub with hundreds of thousands of open models, Inference Endpoints for dedicated hosting and Spaces for demos.",
    site: "https://huggingface.co", docs: "https://huggingface.co/docs", pricingUrl: "https://huggingface.co/pricing",
    deploy: ["managed-cloud", "self-hosted"], pricing: "freemium", free: true, tags: ["open-weights", "hub"], icon: "huggingface",
  }),
  t("together-ai", "Together AI", {
    company: "Together AI", type: "api", cats: ["ai-infrastructure", "ai-models", "gpu-compute"], caps: ["llm-inference", "embeddings", "gpu-compute", "fine-tuning", "image-generation"],
    desc: "Fast serverless inference and fine-tuning for open models (Llama, DeepSeek, Qwen, FLUX) plus dedicated GPU clusters.",
    site: "https://www.together.ai", docs: "https://docs.together.ai", pricingUrl: "https://www.together.ai/pricing",
    deploy: ["managed-cloud"], pricing: "usage-based", free: true, tags: ["open-weights"], icon: null,
  }),
  t("fireworks-ai", "Fireworks AI", {
    company: "Fireworks AI", type: "api", cats: ["ai-infrastructure", "ai-models"], caps: ["llm-inference", "fine-tuning", "image-generation"],
    desc: "Low-latency inference platform for open models with function calling, fine-tuning and compound AI systems.",
    site: "https://fireworks.ai", docs: "https://docs.fireworks.ai", pricingUrl: "https://fireworks.ai/pricing",
    deploy: ["managed-cloud"], pricing: "usage-based", free: true, compliance: ["SOC 2", "HIPAA"], tags: ["open-weights"], icon: null,
  }),
  t("groq", "Groq", {
    company: "Groq", type: "api", cats: ["ai-infrastructure", "ai-models"], caps: ["llm-inference", "speech"],
    desc: "Custom LPU hardware delivering extremely fast token generation for open models; ideal for latency-sensitive chat and voice.",
    site: "https://groq.com", docs: "https://console.groq.com/docs", pricingUrl: "https://groq.com/pricing",
    deploy: ["managed-cloud"], pricing: "usage-based", free: true, tags: ["fast-inference"], icon: null,
  }),
  t("openrouter", "OpenRouter", {
    company: "OpenRouter", type: "api", cats: ["ai-infrastructure"], caps: ["llm-inference", "inference-gateway"],
    desc: "Unified API across hundreds of models from many providers with automatic fallbacks and a single bill.",
    site: "https://openrouter.ai", docs: "https://openrouter.ai/docs", pricingUrl: "https://openrouter.ai/models",
    deploy: ["managed-cloud"], pricing: "usage-based", free: true, maturity: "growing", tags: ["gateway", "multi-provider"], icon: null,
  }),
  t("vercel-ai-gateway", "Vercel AI Gateway", {
    company: "Vercel", type: "service", cats: ["ai-infrastructure"], caps: ["inference-gateway", "llm-inference"],
    desc: "Model routing gateway integrated with the AI SDK: provider failover, budgets, observability and BYOK.",
    site: "https://vercel.com/ai-gateway", docs: "https://vercel.com/docs/ai-gateway",
    deploy: ["managed-cloud"], clouds: ["vercel"], integrations: ["vercel-ai-sdk", "vercel"], pricing: "usage-based", free: true, maturity: "emerging", icon: "vercel",
  }),
  t("litellm", "LiteLLM", {
    company: "BerriAI", type: "library", cats: ["ai-infrastructure", "ai-orchestration"], caps: ["inference-gateway"],
    desc: "Open-source proxy and Python SDK exposing 100+ LLM providers through the OpenAI format with cost tracking and rate limits.",
    site: "https://www.litellm.ai", docs: "https://docs.litellm.ai", repo: "https://github.com/BerriAI/litellm", oss: true, license: "MIT",
    deploy: ["self-hosted", "managed-cloud"], langs: ["python"], free: true, maturity: "growing", tags: ["gateway"], icon: null,
  }),
  t("amazon-bedrock", "Amazon Bedrock", {
    company: "Amazon", type: "service", cats: ["ai-infrastructure", "ai-models"], caps: ["llm-inference", "embeddings", "ai-orchestration", "image-generation"],
    desc: "Managed access to Claude, Llama, Mistral, Nova and other models inside AWS with private networking, guardrails and agents.",
    site: "https://aws.amazon.com/bedrock/", docs: "https://docs.aws.amazon.com/bedrock/", pricingUrl: "https://aws.amazon.com/bedrock/pricing/",
    deploy: ["managed-cloud"], clouds: ["aws"], pricing: "usage-based", compliance: ["HIPAA", "SOC 2", "PCI DSS", "FedRAMP", "GDPR"], tags: ["enterprise", "aws"], icon: "amazonwebservices",
  }),
  t("azure-openai", "Azure OpenAI Service", {
    company: "Microsoft", type: "service", cats: ["ai-infrastructure", "ai-models"], caps: ["llm-inference", "embeddings", "image-generation", "speech"],
    desc: "OpenAI models hosted in Azure with enterprise networking, regional deployments and Microsoft compliance coverage.",
    site: "https://azure.microsoft.com/products/ai-services/openai-service", docs: "https://learn.microsoft.com/azure/ai-services/openai/",
    deploy: ["managed-cloud"], clouds: ["azure"], pricing: "usage-based", compliance: ["HIPAA", "SOC 2", "PCI DSS", "FedRAMP", "GDPR"], tags: ["enterprise", "azure"], icon: null,
  }),
  t("vertex-ai", "Google Vertex AI", {
    company: "Google", type: "platform", cats: ["ai-infrastructure", "ml-platforms"], caps: ["llm-inference", "embeddings", "ml-training", "gpu-compute", "fine-tuning"],
    desc: "Google Cloud's ML platform for Gemini and open models, training, tuning, pipelines and vector search.",
    site: "https://cloud.google.com/vertex-ai", docs: "https://cloud.google.com/vertex-ai/docs",
    deploy: ["managed-cloud"], clouds: ["gcp"], pricing: "usage-based", compliance: ["HIPAA", "SOC 2", "PCI DSS", "GDPR"], tags: ["enterprise", "gcp"], icon: "googlecloud",
  }),
  t("ollama", "Ollama", {
    company: "Ollama", type: "tool", cats: ["local-ai", "ai-infrastructure"], caps: ["local-inference", "llm-inference", "embeddings"],
    desc: "Run open models (Llama, Gemma, Qwen, Mistral, embedding models) locally with one command and an OpenAI-compatible API. The easiest local inference option on Mac, Linux, Windows and NVIDIA GPUs.",
    site: "https://ollama.com", docs: "https://github.com/ollama/ollama/tree/main/docs", repo: "https://github.com/ollama/ollama", oss: true, license: "MIT",
    deploy: ["on-device", "self-hosted"], langs: ["python", "typescript", "go"], free: true, tags: ["local", "nvidia", "cuda"], useCases: ["local-first AI", "private RAG", "offline assistants"],
  }),
  t("vllm", "vLLM", {
    type: "library", cats: ["local-ai", "ai-infrastructure"], caps: ["local-inference", "llm-inference", "model-hosting"],
    desc: "High-throughput LLM serving engine with PagedAttention, continuous batching and an OpenAI-compatible server; the standard for self-hosted production inference on NVIDIA GPUs.",
    site: "https://docs.vllm.ai", docs: "https://docs.vllm.ai/en/latest/", repo: "https://github.com/vllm-project/vllm", oss: true, license: "Apache-2.0",
    deploy: ["self-hosted"], langs: ["python"], free: true, tags: ["nvidia", "cuda", "serving"], useCases: ["self-hosted production inference", "GPU clusters"], icon: null,
  }),
  t("llama-cpp", "llama.cpp", {
    type: "library", cats: ["local-ai"], caps: ["local-inference", "llm-inference"],
    desc: "C/C++ inference for quantized GGUF models on CPUs and consumer GPUs; powers many local AI apps.",
    site: "https://github.com/ggml-org/llama.cpp", docs: "https://github.com/ggml-org/llama.cpp/tree/master/docs", repo: "https://github.com/ggml-org/llama.cpp", oss: true, license: "MIT",
    deploy: ["on-device", "self-hosted"], free: true, tags: ["local", "quantized"], icon: null,
  }),
  t("nvidia-nim", "NVIDIA NIM / Triton", {
    company: "NVIDIA", type: "platform", cats: ["ai-infrastructure", "local-ai"], caps: ["local-inference", "model-hosting", "llm-inference"],
    desc: "NVIDIA's optimized inference microservices (NIM) and Triton Inference Server for deploying models on NVIDIA GPUs with TensorRT acceleration.",
    site: "https://www.nvidia.com/en-us/ai/", docs: "https://docs.nvidia.com/nim/", repo: "https://github.com/triton-inference-server/server",
    deploy: ["self-hosted", "managed-cloud"], pricing: "freemium", free: true, pricingSummary: "Free for development; NVIDIA AI Enterprise license for production", tags: ["nvidia", "cuda", "tensorrt"], aliases: ["Triton Inference Server", "TensorRT-LLM"], icon: "nvidia",
  }),
  t("pytorch", "PyTorch", {
    company: "Linux Foundation", type: "framework", cats: ["ml-platforms", "ai-infrastructure"], caps: ["ml-training", "local-inference"],
    desc: "The dominant deep learning framework for research and production training on NVIDIA and other accelerators.",
    site: "https://pytorch.org", docs: "https://pytorch.org/docs/stable/", repo: "https://github.com/pytorch/pytorch", oss: true, license: "BSD-3-Clause",
    deploy: ["self-hosted", "on-device"], langs: ["python"], free: true, tags: ["nvidia", "cuda", "training"],
  }),
  t("langchain", "LangChain", {
    company: "LangChain", type: "framework", cats: ["ai-orchestration", "ai-agents"], caps: ["ai-orchestration"],
    desc: "Framework for composing LLM applications with integrations for every model, vector store and tool; LangGraph adds stateful agent graphs.",
    site: "https://www.langchain.com", docs: "https://python.langchain.com/docs/", repo: "https://github.com/langchain-ai/langchain", oss: true, license: "MIT",
    deploy: ["self-hosted", "managed-cloud"], langs: ["python", "typescript"], integrations: ["openai", "anthropic", "pinecone", "qdrant", "pgvector", "langsmith"], free: true, aliases: ["LangGraph"], tags: ["rag", "agents"],
  }),
  t("llamaindex", "LlamaIndex", {
    company: "LlamaIndex", type: "framework", cats: ["ai-orchestration"], caps: ["ai-orchestration", "ocr-documents"],
    desc: "Data framework specialized for connecting LLMs to documents: loaders, indexes, query engines, agents and LlamaParse document parsing.",
    site: "https://www.llamaindex.ai", docs: "https://docs.llamaindex.ai", repo: "https://github.com/run-llama/llama_index", oss: true, license: "MIT",
    deploy: ["self-hosted", "managed-cloud"], langs: ["python", "typescript"], free: true, tags: ["rag", "documents"], icon: null,
  }),
  t("vercel-ai-sdk", "Vercel AI SDK", {
    company: "Vercel", type: "library", cats: ["ai-orchestration"], caps: ["ai-orchestration"],
    desc: "TypeScript toolkit for streaming chat UIs, structured output, tool calling and agents across providers; the default for AI features in Next.js apps.",
    site: "https://ai-sdk.dev", docs: "https://ai-sdk.dev/docs", repo: "https://github.com/vercel/ai", oss: true, license: "Apache-2.0",
    deploy: ["self-hosted", "serverless", "edge"], langs: ["typescript"], frameworks: ["nextjs", "react", "sveltekit", "nuxt"], integrations: ["nextjs", "openai", "anthropic", "google-gemini", "vercel-ai-gateway"], free: true, aliases: ["AI SDK"], tags: ["typescript", "streaming"], icon: "vercel",
  }),
  t("pydantic-ai", "Pydantic AI", {
    company: "Pydantic", type: "framework", cats: ["ai-agents", "ai-orchestration"], caps: ["ai-orchestration"],
    desc: "Type-safe Python agent framework from the Pydantic team with structured outputs, dependency injection and evals.",
    site: "https://ai.pydantic.dev", docs: "https://ai.pydantic.dev", repo: "https://github.com/pydantic/pydantic-ai", oss: true, license: "MIT",
    deploy: ["self-hosted"], langs: ["python"], free: true, maturity: "emerging", tags: ["agents", "typed"], icon: "pydantic",
  }),
  t("crewai", "CrewAI", {
    company: "CrewAI", type: "framework", cats: ["ai-agents"], caps: ["ai-orchestration"],
    desc: "Role-based multi-agent orchestration framework in Python with a managed enterprise platform.",
    site: "https://www.crewai.com", docs: "https://docs.crewai.com", repo: "https://github.com/crewAIInc/crewAI", oss: true, license: "MIT",
    deploy: ["self-hosted", "managed-cloud"], langs: ["python"], free: true, maturity: "growing", tags: ["multi-agent"], icon: null,
  }),
  t("openai-agents-sdk", "OpenAI Agents SDK", {
    company: "OpenAI", type: "library", cats: ["ai-agents"], caps: ["ai-orchestration"],
    desc: "Lightweight agent framework with handoffs, guardrails and tracing, in Python and TypeScript.",
    site: "https://openai.github.io/openai-agents-python/", docs: "https://openai.github.io/openai-agents-python/", repo: "https://github.com/openai/openai-agents-python", oss: true, license: "MIT",
    deploy: ["self-hosted"], langs: ["python", "typescript"], integrations: ["openai"], free: true, maturity: "emerging", icon: "openai",
  }),
  t("claude-agent-sdk", "Claude Agent SDK", {
    company: "Anthropic", type: "library", cats: ["ai-agents"], caps: ["ai-orchestration"],
    desc: "Build autonomous agents on the same harness that powers Claude Code: tools, file system access, subagents, hooks and MCP.",
    site: "https://docs.anthropic.com/en/api/agent-sdk/overview", docs: "https://docs.anthropic.com/en/api/agent-sdk/overview", repo: "https://github.com/anthropics/claude-agent-sdk-python", oss: true, license: "MIT",
    deploy: ["self-hosted"], langs: ["python", "typescript"], integrations: ["anthropic", "model-context-protocol"], free: true, maturity: "emerging", icon: "anthropic",
  }),
  t("model-context-protocol", "Model Context Protocol", {
    company: "Anthropic", type: "protocol", cats: ["ai-agents", "apis"], caps: [],
    desc: "Open standard for connecting AI models to tools and data sources through MCP servers; supported by major agent clients.",
    site: "https://modelcontextprotocol.io", docs: "https://modelcontextprotocol.io/docs", repo: "https://github.com/modelcontextprotocol", oss: true, license: "MIT",
    deploy: ["self-hosted"], langs: ["python", "typescript"], free: true, maturity: "growing", aliases: ["MCP"], icon: "modelcontextprotocol",
  }),
  t("dspy", "DSPy", {
    company: "Stanford NLP", type: "framework", cats: ["ai-orchestration"], caps: ["ai-orchestration"],
    desc: "Programming framework that compiles declarative LLM pipelines and optimizes prompts against metrics.",
    site: "https://dspy.ai", docs: "https://dspy.ai/learn/", repo: "https://github.com/stanfordnlp/dspy", oss: true, license: "MIT",
    deploy: ["self-hosted"], langs: ["python"], free: true, maturity: "growing", icon: null,
  }),
  t("haystack", "Haystack", {
    company: "deepset", type: "framework", cats: ["ai-orchestration"], caps: ["ai-orchestration"],
    desc: "Production-oriented open-source framework for RAG and agent pipelines with a component graph model.",
    site: "https://haystack.deepset.ai", docs: "https://docs.haystack.deepset.ai", repo: "https://github.com/deepset-ai/haystack", oss: true, license: "Apache-2.0",
    deploy: ["self-hosted", "managed-cloud"], langs: ["python"], free: true, icon: null,
  }),
  t("typesafe-ai", "TypeSafe AI (Jev)", {
    company: "TypeSafe", type: "api", cats: ["ai-models", "ai-orchestration"], caps: ["llm-inference", "ai-orchestration"],
    desc: "System One decision model that returns typed, calibrated judgments (choice, score, yes/no) instead of generated text; used for routing, ranking, verification and structured decisions in code.",
    site: "https://typesafe.ai", docs: "https://docs.typesafe.ai", pricingUrl: "https://docs.typesafe.ai/models",
    deploy: ["managed-cloud"], langs: ["python", "typescript"], pricing: "usage-based", pricingSummary: "Per input token", maturity: "emerging", aliases: ["Jev"], tags: ["decision-engine", "calibrated"], icon: null,
  }),
  t("langsmith", "LangSmith", {
    company: "LangChain", type: "service", cats: ["observability", "ml-platforms"], caps: ["ai-evaluation"],
    desc: "Tracing, evaluation and prompt management for LLM apps; works with or without LangChain.",
    site: "https://www.langchain.com/langsmith", docs: "https://docs.smith.langchain.com", pricingUrl: "https://www.langchain.com/pricing",
    deploy: ["managed-cloud", "self-hosted"], pricing: "freemium", free: true, compliance: ["SOC 2", "HIPAA"], icon: "langchain",
  }),
  t("langfuse", "Langfuse", {
    company: "Langfuse", type: "platform", cats: ["observability", "ml-platforms"], caps: ["ai-evaluation"],
    desc: "Open-source LLM engineering platform: tracing, evals, prompt management and cost analytics; easy to self-host.",
    site: "https://langfuse.com", docs: "https://langfuse.com/docs", repo: "https://github.com/langfuse/langfuse", pricingUrl: "https://langfuse.com/pricing", oss: true, license: "MIT",
    deploy: ["managed-cloud", "self-hosted"], pricing: "freemium", free: true, compliance: ["SOC 2", "HIPAA", "GDPR"], maturity: "growing", icon: null,
  }),
  t("braintrust", "Braintrust", {
    company: "Braintrust", type: "service", cats: ["ml-platforms", "observability"], caps: ["ai-evaluation"],
    desc: "Evaluation and observability platform for AI products with datasets, scorers, playgrounds and CI integration.",
    site: "https://www.braintrust.dev", docs: "https://www.braintrust.dev/docs", pricingUrl: "https://www.braintrust.dev/pricing",
    deploy: ["managed-cloud", "self-hosted"], pricing: "freemium", free: true, maturity: "growing", icon: null,
  }),
  t("weights-and-biases", "Weights & Biases", {
    company: "CoreWeave", type: "platform", cats: ["ml-platforms", "observability"], caps: ["experiment-tracking", "ai-evaluation", "ml-training"],
    desc: "Experiment tracking, model registry and Weave LLM observability for ML teams.",
    site: "https://wandb.ai", docs: "https://docs.wandb.ai", pricingUrl: "https://wandb.ai/site/pricing",
    deploy: ["managed-cloud", "self-hosted"], pricing: "freemium", free: true, compliance: ["SOC 2", "HIPAA"], aliases: ["W&B", "Weave"], icon: "weightsandbiases",
  }),
  t("mlflow", "MLflow", {
    company: "Databricks", type: "platform", cats: ["ml-platforms"], caps: ["experiment-tracking", "ai-evaluation", "model-hosting"],
    desc: "Open-source platform for the ML lifecycle: tracking, model registry, deployment and GenAI tracing.",
    site: "https://mlflow.org", docs: "https://mlflow.org/docs/latest/", repo: "https://github.com/mlflow/mlflow", oss: true, license: "Apache-2.0",
    deploy: ["self-hosted", "managed-cloud"], langs: ["python"], free: true,
  }),
  t("modal", "Modal", {
    company: "Modal", type: "platform", cats: ["gpu-compute", "serverless", "ai-infrastructure"], caps: ["gpu-compute", "workers", "scheduler", "model-hosting", "hosting"],
    desc: "Serverless Python compute with instant GPU access: define functions in code, get autoscaling containers, cron jobs and web endpoints. Outstanding for AI pipelines and batch jobs.",
    site: "https://modal.com", docs: "https://modal.com/docs", pricingUrl: "https://modal.com/pricing",
    deploy: ["managed-cloud", "serverless"], langs: ["python"], pricing: "usage-based", free: true, pricingSummary: "Monthly free credit, then per-second compute", compliance: ["SOC 2", "HIPAA"], maturity: "growing", tags: ["gpu", "serverless", "python"], useCases: ["batch inference", "video generation pipelines", "fine-tuning"],
  }),
  t("replicate", "Replicate", {
    company: "Replicate", type: "api", cats: ["ai-infrastructure", "ai-models", "image", "video"], caps: ["llm-inference", "image-generation", "video-generation", "gpu-compute", "model-hosting"],
    desc: "Run thousands of open image, video, audio and language models through one API, or deploy custom models with Cog.",
    site: "https://replicate.com", docs: "https://replicate.com/docs", pricingUrl: "https://replicate.com/pricing",
    deploy: ["managed-cloud"], pricing: "usage-based", pricingSummary: "Per-second GPU time or per-output pricing", tags: ["media-generation"],
  }),
  t("fal-ai", "fal.ai", {
    company: "fal", type: "api", cats: ["ai-infrastructure", "image", "video"], caps: ["image-generation", "video-generation", "gpu-compute"],
    desc: "Fast generative media inference (FLUX, video models, audio) with an API and serverless GPU runtime.",
    site: "https://fal.ai", docs: "https://docs.fal.ai", pricingUrl: "https://fal.ai/pricing",
    deploy: ["managed-cloud"], pricing: "usage-based", maturity: "growing", tags: ["media-generation", "fast"], icon: null,
  }),
  t("runpod", "RunPod", {
    company: "RunPod", type: "platform", cats: ["gpu-compute"], caps: ["gpu-compute", "model-hosting"],
    desc: "Affordable GPU cloud with pods and serverless GPU endpoints for inference and training.",
    site: "https://www.runpod.io", docs: "https://docs.runpod.io", pricingUrl: "https://www.runpod.io/pricing",
    deploy: ["managed-cloud"], pricing: "usage-based", tags: ["gpu", "nvidia"], icon: null,
  }),
  t("lambda-labs", "Lambda Labs", {
    company: "Lambda", type: "platform", cats: ["gpu-compute"], caps: ["gpu-compute", "ml-training"],
    desc: "GPU cloud with on-demand and reserved NVIDIA instances and clusters for training and inference. Known as Lambda; listed as Lambda Labs to distinguish it from AWS Lambda.",
    aliases: ["Lambda GPU Cloud"],
    site: "https://lambda.ai", docs: "https://docs.lambda.ai", pricingUrl: "https://lambda.ai/pricing",
    deploy: ["managed-cloud"], pricing: "usage-based", tags: ["gpu", "nvidia"], icon: null,
  }),
  t("coreweave", "CoreWeave", {
    company: "CoreWeave", type: "platform", cats: ["gpu-compute", "kubernetes"], caps: ["gpu-compute", "ml-training", "container-orchestration"],
    desc: "Kubernetes-native GPU cloud built for large-scale AI training and inference.",
    site: "https://www.coreweave.com", docs: "https://docs.coreweave.com",
    deploy: ["managed-cloud"], pricing: "usage-based", tags: ["gpu", "nvidia", "scale"], icon: null,
  }),
  t("baseten", "Baseten", {
    company: "Baseten", type: "platform", cats: ["ai-infrastructure", "gpu-compute"], caps: ["model-hosting", "gpu-compute", "llm-inference"],
    desc: "Production model serving with Truss packaging, autoscaling GPUs and optimized inference engines.",
    site: "https://www.baseten.co", docs: "https://docs.baseten.co", pricingUrl: "https://www.baseten.co/pricing",
    deploy: ["managed-cloud", "self-hosted"], pricing: "usage-based", compliance: ["SOC 2", "HIPAA"], maturity: "growing", icon: null,
  }),
  t("deepgram", "Deepgram", {
    company: "Deepgram", type: "api", cats: ["speech"], caps: ["speech"],
    desc: "Fast, accurate speech-to-text and text-to-speech APIs with streaming and voice agent support.",
    site: "https://deepgram.com", docs: "https://developers.deepgram.com", pricingUrl: "https://deepgram.com/pricing",
    deploy: ["managed-cloud", "self-hosted"], pricing: "usage-based", free: true, compliance: ["SOC 2", "HIPAA"], icon: null,
  }),
  t("assemblyai", "AssemblyAI", {
    company: "AssemblyAI", type: "api", cats: ["speech"], caps: ["speech"],
    desc: "Speech AI API for transcription, speaker diarization and audio intelligence.",
    site: "https://www.assemblyai.com", docs: "https://www.assemblyai.com/docs", pricingUrl: "https://www.assemblyai.com/pricing",
    deploy: ["managed-cloud"], pricing: "usage-based", free: true, compliance: ["SOC 2", "HIPAA", "GDPR"], icon: null,
  }),
  t("elevenlabs", "ElevenLabs", {
    company: "ElevenLabs", type: "api", cats: ["speech", "audio"], caps: ["speech"],
    desc: "Leading text-to-speech, voice cloning, dubbing and conversational voice agent APIs.",
    site: "https://elevenlabs.io", docs: "https://elevenlabs.io/docs", pricingUrl: "https://elevenlabs.io/pricing",
    deploy: ["managed-cloud"], pricing: "freemium", free: true, compliance: ["SOC 2", "GDPR"],
  }),
  t("whisper", "Whisper", {
    company: "OpenAI", type: "model", cats: ["speech", "local-ai"], caps: ["speech", "local-inference"],
    desc: "Open-weight speech recognition model runnable locally (whisper.cpp, faster-whisper) or via hosted APIs.",
    site: "https://github.com/openai/whisper", docs: "https://github.com/openai/whisper#readme", repo: "https://github.com/openai/whisper", oss: true, license: "MIT",
    deploy: ["on-device", "self-hosted", "managed-cloud"], free: true, tags: ["open-weights"], icon: "openai",
  }),
  t("comfyui", "ComfyUI", {
    company: "Comfy Org", type: "tool", cats: ["image", "local-ai", "ai-orchestration"], caps: ["image-generation", "local-inference", "video-generation"],
    desc: "Open-source node-based engine for running image and video generation models locally on your own GPU, with an API for programmatic pipelines.",
    site: "https://www.comfy.org", docs: "https://docs.comfy.org", repo: "https://github.com/comfyanonymous/ComfyUI", oss: true, license: "GPL-3.0",
    deploy: ["self-hosted", "on-device"], langs: ["python"], free: true, maturity: "growing", tags: ["local", "nvidia", "open-weights"], icon: null,
  }),
  t("stability-ai", "Stability AI", {
    company: "Stability AI", type: "api", cats: ["image", "ai-models"], caps: ["image-generation", "video-generation"],
    desc: "Stable Diffusion image models and Stable Video available as open weights and hosted APIs.",
    site: "https://stability.ai", docs: "https://platform.stability.ai/docs", pricingUrl: "https://platform.stability.ai/pricing",
    deploy: ["managed-cloud", "self-hosted"], pricing: "usage-based", tags: ["open-weights"], icon: null,
  }),
  t("black-forest-labs", "Black Forest Labs (FLUX)", {
    company: "Black Forest Labs", type: "model", cats: ["image", "ai-models"], caps: ["image-generation"],
    desc: "FLUX family of image generation and editing models, hosted and as open weights.",
    site: "https://bfl.ai", docs: "https://docs.bfl.ai",
    deploy: ["managed-cloud", "self-hosted"], pricing: "usage-based", maturity: "growing", aliases: ["FLUX"], icon: null,
  }),
  t("runway", "Runway", {
    company: "Runway", type: "api", cats: ["video", "ai-models"], caps: ["video-generation"],
    desc: "Generative video models (Gen-4) available through an API for text- and image-to-video.",
    site: "https://runwayml.com", docs: "https://docs.dev.runwayml.com", pricingUrl: "https://runwayml.com/pricing",
    deploy: ["managed-cloud"], pricing: "usage-based", tags: ["video-generation"], icon: null,
  }),
  t("luma-ai", "Luma AI", {
    company: "Luma AI", type: "api", cats: ["video", "ai-models"], caps: ["video-generation", "image-generation"],
    desc: "Dream Machine video and image generation models with a developer API.",
    site: "https://lumalabs.ai", docs: "https://docs.lumalabs.ai",
    deploy: ["managed-cloud"], pricing: "usage-based", maturity: "growing", icon: null,
  }),
  t("mux", "Mux", {
    company: "Mux", type: "api", cats: ["video"], caps: ["video-generation"],
    desc: "Video API for upload, transcoding, adaptive streaming, live video and player analytics.",
    site: "https://www.mux.com", docs: "https://docs.mux.com", pricingUrl: "https://www.mux.com/pricing",
    deploy: ["managed-cloud"], pricing: "usage-based", free: true, compliance: ["SOC 2", "GDPR"], tags: ["video-infrastructure"],
  }),
  t("cloudflare-stream", "Cloudflare Stream", {
    company: "Cloudflare", type: "service", cats: ["video", "cdn-edge"], caps: ["video-generation", "cdn"],
    desc: "Video storage, encoding and delivery with a simple per-minute price on Cloudflare's network.",
    site: "https://www.cloudflare.com/developer-platform/products/cloudflare-stream/", docs: "https://developers.cloudflare.com/stream/",
    deploy: ["managed-cloud", "edge"], clouds: ["cloudflare"], pricing: "usage-based", icon: "cloudflare",
  }),
  t("ffmpeg", "FFmpeg", {
    type: "tool", cats: ["video", "audio"], caps: ["video-generation", "audio-processing"],
    desc: "The universal open-source toolkit for decoding, encoding, transcoding and filtering audio and video.",
    site: "https://ffmpeg.org", docs: "https://ffmpeg.org/documentation.html", repo: "https://github.com/FFmpeg/FFmpeg", oss: true, license: "LGPL-2.1",
    deploy: ["self-hosted", "on-device"], free: true,
  }),
  t("remotion", "Remotion", {
    company: "Remotion", type: "framework", cats: ["video"], caps: ["video-generation"],
    desc: "Create videos programmatically with React components and render them server-side or on Lambda.",
    site: "https://www.remotion.dev", docs: "https://www.remotion.dev/docs/", repo: "https://github.com/remotion-dev/remotion", oss: true, license: "Remotion License",
    deploy: ["self-hosted", "serverless"], clouds: ["aws"], langs: ["typescript"], frameworks: ["react"], pricing: "freemium", free: true, pricingSummary: "Free for individuals and small teams; company license otherwise", maturity: "growing", icon: null,
  }),
  t("cloudinary", "Cloudinary", {
    company: "Cloudinary", type: "service", cats: ["image", "video", "storage"], caps: ["object-storage", "image-processing", "video-generation"],
    desc: "Image and video management with on-the-fly transformations, optimization and delivery.",
    site: "https://cloudinary.com", docs: "https://cloudinary.com/documentation", pricingUrl: "https://cloudinary.com/pricing",
    deploy: ["managed-cloud"], pricing: "freemium", free: true, compliance: ["SOC 2", "GDPR"],
  }),
  t("unstructured", "Unstructured", {
    company: "Unstructured", type: "api", cats: ["ocr", "documents"], caps: ["ocr-documents"],
    desc: "ETL for LLMs: partitions PDFs, Office files, HTML and images into structured chunks for RAG.",
    site: "https://unstructured.io", docs: "https://docs.unstructured.io", repo: "https://github.com/Unstructured-IO/unstructured", oss: true, license: "Apache-2.0",
    deploy: ["managed-cloud", "self-hosted"], langs: ["python"], pricing: "freemium", free: true, maturity: "growing", icon: null,
  }),
  t("reducto", "Reducto", {
    company: "Reducto", type: "api", cats: ["ocr", "documents"], caps: ["ocr-documents"],
    desc: "High-accuracy document parsing and extraction API for complex PDFs, tables and forms.",
    site: "https://reducto.ai", docs: "https://docs.reducto.ai",
    deploy: ["managed-cloud"], pricing: "usage-based", compliance: ["SOC 2", "HIPAA"], maturity: "emerging", icon: null,
  }),
  t("docling", "Docling", {
    company: "IBM", type: "library", cats: ["ocr", "documents"], caps: ["ocr-documents"],
    desc: "Open-source document conversion (PDF, DOCX, images) to structured Markdown/JSON for RAG, runnable fully locally.",
    site: "https://docling-project.github.io/docling/", docs: "https://docling-project.github.io/docling/", repo: "https://github.com/docling-project/docling", oss: true, license: "MIT",
    deploy: ["self-hosted", "on-device"], langs: ["python"], free: true, maturity: "growing", tags: ["local"], icon: null,
  }),
  t("tesseract", "Tesseract OCR", {
    type: "library", cats: ["ocr"], caps: ["ocr-documents"],
    desc: "Classic open-source OCR engine for extracting text from images; no cost, fully local.",
    site: "https://github.com/tesseract-ocr/tesseract", docs: "https://tesseract-ocr.github.io", repo: "https://github.com/tesseract-ocr/tesseract", oss: true, license: "Apache-2.0",
    deploy: ["self-hosted", "on-device"], free: true, icon: null,
  }),
  t("tavily", "Tavily", {
    company: "Tavily", type: "api", cats: ["search-apis"], caps: ["web-search-api"],
    desc: "Search and extract API designed for LLM agents and RAG with clean, ranked results.",
    site: "https://tavily.com", docs: "https://docs.tavily.com", pricingUrl: "https://tavily.com/#pricing",
    deploy: ["managed-cloud"], pricing: "freemium", free: true, maturity: "growing", icon: null,
  }),
  t("exa", "Exa", {
    company: "Exa", type: "api", cats: ["search-apis"], caps: ["web-search-api"],
    desc: "Neural web search API returning semantically relevant pages and contents for AI applications.",
    site: "https://exa.ai", docs: "https://docs.exa.ai", pricingUrl: "https://exa.ai/pricing",
    deploy: ["managed-cloud"], pricing: "freemium", free: true, maturity: "growing", icon: null,
  }),
  t("brave-search-api", "Brave Search API", {
    company: "Brave", type: "api", cats: ["search-apis"], caps: ["web-search-api"],
    desc: "Independent web search index with an affordable API including news and LLM-oriented endpoints.",
    site: "https://brave.com/search/api/", docs: "https://api-dashboard.search.brave.com/app/documentation",
    deploy: ["managed-cloud"], pricing: "usage-based", free: true, icon: "brave",
  }),
  t("firecrawl", "Firecrawl", {
    company: "Firecrawl", type: "api", cats: ["web-scraping", "search-apis"], caps: ["web-search-api", "browser-automation"],
    desc: "Crawl and scrape websites into clean Markdown/JSON for LLMs; open-source with a hosted API.",
    site: "https://www.firecrawl.dev", docs: "https://docs.firecrawl.dev", repo: "https://github.com/mendableai/firecrawl", pricingUrl: "https://www.firecrawl.dev/pricing", oss: true, license: "AGPL-3.0",
    deploy: ["managed-cloud", "self-hosted"], pricing: "freemium", free: true, maturity: "growing", icon: null,
  }),
  t("apify", "Apify", {
    company: "Apify", type: "platform", cats: ["web-scraping", "browser-automation"], caps: ["web-search-api", "browser-automation"],
    desc: "Web scraping and automation platform with a marketplace of ready-made scrapers (Actors) and the Crawlee library.",
    site: "https://apify.com", docs: "https://docs.apify.com", pricingUrl: "https://apify.com/pricing",
    deploy: ["managed-cloud"], pricing: "freemium", free: true,
  }),
  t("playwright", "Playwright", {
    company: "Microsoft", type: "library", cats: ["browser-automation", "testing"], caps: ["browser-automation", "testing"],
    desc: "Reliable cross-browser automation and end-to-end testing for Chromium, Firefox and WebKit.",
    site: "https://playwright.dev", docs: "https://playwright.dev/docs/intro", repo: "https://github.com/microsoft/playwright", oss: true, license: "Apache-2.0",
    deploy: ["self-hosted"], langs: ["typescript", "python", "java", "csharp"], free: true,
  }),
  t("puppeteer", "Puppeteer", {
    company: "Google", type: "library", cats: ["browser-automation"], caps: ["browser-automation"],
    desc: "Node.js library to control headless Chrome for scraping, screenshots and PDF generation.",
    site: "https://pptr.dev", docs: "https://pptr.dev/guides", repo: "https://github.com/puppeteer/puppeteer", oss: true, license: "Apache-2.0",
    deploy: ["self-hosted"], langs: ["typescript", "javascript"], free: true,
  }),
  t("browserbase", "Browserbase", {
    company: "Browserbase", type: "service", cats: ["browser-automation"], caps: ["browser-automation"],
    desc: "Managed headless browser infrastructure for agents and automation with Stagehand's AI-driven browsing SDK.",
    site: "https://www.browserbase.com", docs: "https://docs.browserbase.com", pricingUrl: "https://www.browserbase.com/pricing",
    deploy: ["managed-cloud"], pricing: "freemium", free: true, maturity: "emerging", aliases: ["Stagehand"], icon: null,
  }),
  t("scrapy", "Scrapy", {
    company: "Zyte", type: "framework", cats: ["web-scraping"], caps: ["web-search-api"],
    desc: "Mature Python framework for building fast, large-scale web crawlers.",
    site: "https://scrapy.org", docs: "https://docs.scrapy.org", repo: "https://github.com/scrapy/scrapy", oss: true, license: "BSD-3-Clause",
    deploy: ["self-hosted"], langs: ["python"], free: true,
  }),
  t("newsapi", "NewsAPI", {
    company: "NewsAPI", type: "api", cats: ["search-apis", "apis"], caps: ["web-search-api"],
    desc: "Simple JSON API for live headlines and article search across tens of thousands of news sources.",
    site: "https://newsapi.org", docs: "https://newsapi.org/docs", pricingUrl: "https://newsapi.org/pricing",
    deploy: ["managed-cloud"], pricing: "freemium", free: true, tags: ["news"], icon: null,
  }),
];
