import { t } from "./helper";

export const BACKEND = [
  t("fastapi", "FastAPI", {
    type: "framework", cats: ["backend-frameworks"], caps: ["api-backend"],
    desc: "High-performance async Python web framework with automatic OpenAPI docs and Pydantic validation. The default Python choice for AI-heavy backends.",
    site: "https://fastapi.tiangolo.com", docs: "https://fastapi.tiangolo.com/learn/", repo: "https://github.com/fastapi/fastapi", oss: true, license: "MIT",
    deploy: ["self-hosted", "managed-cloud", "serverless"], langs: ["python"], integrations: ["sqlalchemy", "pydantic", "uvicorn", "postgresql", "celery"], free: true, tags: ["python", "async", "openapi"],
  }),
  t("django", "Django", {
    company: "Django Software Foundation", type: "framework", cats: ["backend-frameworks"], caps: ["api-backend", "orm", "authentication"],
    desc: "Batteries-included Python web framework with ORM, admin, auth and migrations. Strong for content-heavy and CRUD-heavy products.",
    site: "https://www.djangoproject.com", docs: "https://docs.djangoproject.com", repo: "https://github.com/django/django", oss: true, license: "BSD-3-Clause",
    deploy: ["self-hosted", "managed-cloud"], langs: ["python"], integrations: ["postgresql", "celery", "redis"], free: true, tags: ["python", "batteries-included"],
  }),
  t("flask", "Flask", {
    company: "Pallets", type: "framework", cats: ["backend-frameworks"], caps: ["api-backend"],
    desc: "Minimal Python microframework; simple to start, requires assembling extensions for larger apps.",
    site: "https://flask.palletsprojects.com", docs: "https://flask.palletsprojects.com/en/stable/", repo: "https://github.com/pallets/flask", oss: true, license: "BSD-3-Clause",
    deploy: ["self-hosted", "managed-cloud", "serverless"], langs: ["python"], free: true,
  }),
  t("express", "Express", {
    company: "OpenJS Foundation", type: "framework", cats: ["backend-frameworks"], caps: ["api-backend"],
    desc: "Minimal, unopinionated Node.js web framework with the largest middleware ecosystem.",
    site: "https://expressjs.com", docs: "https://expressjs.com/en/starter/installing.html", repo: "https://github.com/expressjs/express", oss: true, license: "MIT",
    deploy: ["self-hosted", "managed-cloud", "serverless"], langs: ["typescript", "javascript"], free: true,
  }),
  t("hono", "Hono", {
    type: "framework", cats: ["backend-frameworks"], caps: ["api-backend"],
    desc: "Small, fast web framework built on Web Standards that runs on Cloudflare Workers, Deno, Bun, Node and edge runtimes.",
    site: "https://hono.dev", docs: "https://hono.dev/docs/", repo: "https://github.com/honojs/hono", oss: true, license: "MIT",
    deploy: ["edge", "serverless", "self-hosted"], clouds: ["cloudflare", "vercel", "aws", "deno-deploy"], langs: ["typescript", "javascript"], integrations: ["cloudflare-workers", "bun", "deno"], free: true, maturity: "growing", tags: ["edge", "web-standards"],
  }),
  t("nestjs", "NestJS", {
    type: "framework", cats: ["backend-frameworks"], caps: ["api-backend"],
    desc: "Opinionated, modular TypeScript server framework with dependency injection, inspired by Angular. Popular with enterprise Node teams.",
    site: "https://nestjs.com", docs: "https://docs.nestjs.com", repo: "https://github.com/nestjs/nest", oss: true, license: "MIT",
    deploy: ["self-hosted", "managed-cloud"], langs: ["typescript"], free: true, tags: ["enterprise", "di"],
  }),
  t("fastify", "Fastify", {
    type: "framework", cats: ["backend-frameworks"], caps: ["api-backend"],
    desc: "Fast, low-overhead Node.js web framework with schema-based validation and a plugin architecture.",
    site: "https://fastify.dev", docs: "https://fastify.dev/docs/latest/", repo: "https://github.com/fastify/fastify", oss: true, license: "MIT",
    deploy: ["self-hosted", "managed-cloud"], langs: ["typescript", "javascript"], free: true,
  }),
  t("trpc", "tRPC", {
    type: "library", cats: ["apis", "backend-frameworks"], caps: ["api-backend"],
    desc: "End-to-end typesafe APIs for TypeScript monorepos without code generation; ideal when frontend and backend share a codebase.",
    site: "https://trpc.io", docs: "https://trpc.io/docs", repo: "https://github.com/trpc/trpc", oss: true, license: "MIT",
    deploy: ["self-hosted", "serverless", "edge"], langs: ["typescript"], frameworks: ["nextjs", "react"], integrations: ["nextjs", "react", "zod"], free: true,
  }),
  t("graphql", "GraphQL", {
    company: "GraphQL Foundation", type: "protocol", cats: ["apis"], caps: [],
    desc: "Query language and runtime for APIs that lets clients request exactly the data they need. Suits products with many client types.",
    site: "https://graphql.org", docs: "https://graphql.org/learn/", repo: "https://github.com/graphql/graphql-spec", oss: true, license: "MIT",
    deploy: ["self-hosted", "managed-cloud"], langs: ["typescript", "python", "go", "java", "ruby"], free: true, tags: ["api", "schema"],
  }),
  t("apollo-graphql", "Apollo GraphQL", {
    company: "Apollo", type: "platform", cats: ["apis", "api-gateways"], caps: ["api-backend", "api-gateway"],
    desc: "GraphQL server, client and federated supergraph platform for large multi-team API estates.",
    site: "https://www.apollographql.com", docs: "https://www.apollographql.com/docs", repo: "https://github.com/apollographql/apollo-server", pricingUrl: "https://www.apollographql.com/pricing", oss: true, license: "MIT",
    deploy: ["self-hosted", "managed-cloud"], langs: ["typescript", "javascript"], integrations: ["graphql"], pricing: "freemium", free: true, pricingSummary: "Open-source libraries; GraphOS has free and paid tiers", tags: ["enterprise"],
  }),
  t("spring-boot", "Spring Boot", {
    company: "Broadcom", type: "framework", cats: ["backend-frameworks"], caps: ["api-backend", "authentication"],
    desc: "The standard JVM application framework for enterprise Java and Kotlin services with a vast ecosystem.",
    site: "https://spring.io/projects/spring-boot", docs: "https://docs.spring.io/spring-boot/", repo: "https://github.com/spring-projects/spring-boot", oss: true, license: "Apache-2.0",
    deploy: ["self-hosted", "managed-cloud"], langs: ["java", "kotlin"], free: true, tags: ["enterprise", "jvm"], icon: "springboot",
  }),
  t("ruby-on-rails", "Ruby on Rails", {
    type: "framework", cats: ["backend-frameworks"], caps: ["api-backend", "orm", "authentication", "workers"],
    desc: "Convention-over-configuration full-stack framework known for developer productivity; excellent for small teams shipping fast.",
    site: "https://rubyonrails.org", docs: "https://guides.rubyonrails.org", repo: "https://github.com/rails/rails", oss: true, license: "MIT",
    deploy: ["self-hosted", "managed-cloud"], langs: ["ruby"], integrations: ["postgresql", "redis", "sidekiq"], free: true, aliases: ["Rails"], icon: "rubyonrails",
  }),
  t("laravel", "Laravel", {
    type: "framework", cats: ["backend-frameworks"], caps: ["api-backend", "orm", "authentication", "workers"],
    desc: "Expressive PHP framework with a complete ecosystem: ORM, queues, auth, billing and first-party hosting.",
    site: "https://laravel.com", docs: "https://laravel.com/docs", repo: "https://github.com/laravel/laravel", oss: true, license: "MIT",
    deploy: ["self-hosted", "managed-cloud"], langs: ["php"], free: true,
  }),
  t("phoenix", "Phoenix", {
    type: "framework", cats: ["backend-frameworks", "realtime"], caps: ["api-backend", "realtime", "web-frontend"],
    desc: "Elixir web framework with LiveView for server-rendered realtime UIs and Channels for massive concurrent connections.",
    site: "https://www.phoenixframework.org", docs: "https://hexdocs.pm/phoenix", repo: "https://github.com/phoenixframework/phoenix", oss: true, license: "MIT",
    deploy: ["self-hosted", "managed-cloud"], clouds: ["fly-io"], langs: ["elixir"], free: true, tags: ["realtime", "beam"], icon: "phoenixframework",
  }),
  t("go", "Go", {
    company: "Google", type: "language", cats: ["languages", "backend-frameworks"], caps: ["api-backend", "language"],
    desc: "Compiled, statically typed language with simple concurrency and small deployable binaries; the standard for infrastructure and high-throughput services.",
    site: "https://go.dev", docs: "https://go.dev/doc/", repo: "https://github.com/golang/go", oss: true, license: "BSD-3-Clause",
    deploy: ["self-hosted", "managed-cloud", "serverless"], langs: ["go"], free: true, aliases: ["Golang"],
  }),
  t("gin", "Gin", {
    type: "framework", cats: ["backend-frameworks"], caps: ["api-backend"],
    desc: "Fast, minimal Go HTTP web framework with a martini-like API.",
    site: "https://gin-gonic.com", docs: "https://gin-gonic.com/docs/", repo: "https://github.com/gin-gonic/gin", oss: true, license: "MIT",
    deploy: ["self-hosted", "managed-cloud"], langs: ["go"], free: true,
  }),
  t("rust", "Rust", {
    company: "Rust Foundation", type: "language", cats: ["languages"], caps: ["language", "api-backend"],
    desc: "Memory-safe systems language with top-tier performance; used for services needing extreme efficiency and safety.",
    site: "https://www.rust-lang.org", docs: "https://doc.rust-lang.org", repo: "https://github.com/rust-lang/rust", oss: true, license: "MIT",
    deploy: ["self-hosted", "managed-cloud", "edge"], langs: ["rust"], free: true,
  }),
  t("axum", "Axum", {
    company: "Tokio", type: "framework", cats: ["backend-frameworks"], caps: ["api-backend"],
    desc: "Ergonomic Rust web framework built on Tokio and Tower for high-performance services.",
    site: "https://github.com/tokio-rs/axum", docs: "https://docs.rs/axum", repo: "https://github.com/tokio-rs/axum", oss: true, license: "MIT",
    deploy: ["self-hosted", "managed-cloud"], langs: ["rust"], free: true, maturity: "growing", icon: null,
  }),
  t("dotnet", ".NET / ASP.NET Core", {
    company: "Microsoft", type: "framework", cats: ["backend-frameworks", "runtimes"], caps: ["api-backend", "runtime"],
    desc: "Microsoft's cross-platform runtime and web framework for C#; strong in enterprise and Azure-centric shops.",
    site: "https://dotnet.microsoft.com", docs: "https://learn.microsoft.com/aspnet/core/", repo: "https://github.com/dotnet/aspnetcore", oss: true, license: "MIT",
    deploy: ["self-hosted", "managed-cloud", "serverless"], clouds: ["azure", "aws"], langs: ["csharp"], free: true, aliases: ["ASP.NET Core", "C#"], tags: ["enterprise"],
  }),
  t("nodejs", "Node.js", {
    company: "OpenJS Foundation", type: "runtime", cats: ["runtimes"], caps: ["runtime"],
    desc: "The default JavaScript server runtime with the npm ecosystem.",
    site: "https://nodejs.org", docs: "https://nodejs.org/docs/latest/api/", repo: "https://github.com/nodejs/node", oss: true, license: "MIT",
    deploy: ["self-hosted", "managed-cloud", "serverless"], langs: ["typescript", "javascript"], free: true, icon: "nodedotjs",
  }),
  t("bun", "Bun", {
    company: "Anthropic", type: "runtime", cats: ["runtimes", "package-managers"], caps: ["runtime", "package-manager"],
    desc: "Fast all-in-one JavaScript runtime, bundler, test runner and package manager compatible with Node APIs.",
    site: "https://bun.sh", docs: "https://bun.sh/docs", repo: "https://github.com/oven-sh/bun", oss: true, license: "MIT",
    deploy: ["self-hosted", "managed-cloud"], langs: ["typescript", "javascript"], free: true, maturity: "growing",
  }),
  t("deno", "Deno", {
    company: "Deno Land", type: "runtime", cats: ["runtimes", "serverless"], caps: ["runtime", "hosting"],
    desc: "Secure TypeScript-first runtime with web-standard APIs and Deno Deploy edge hosting.",
    site: "https://deno.com", docs: "https://docs.deno.com", repo: "https://github.com/denoland/deno", oss: true, license: "MIT",
    deploy: ["self-hosted", "edge"], langs: ["typescript", "javascript"], free: true, maturity: "growing",
  }),
  t("python", "Python", {
    company: "Python Software Foundation", type: "language", cats: ["languages"], caps: ["language"],
    desc: "The dominant language for AI, data and scripting with the richest ML ecosystem.",
    site: "https://www.python.org", docs: "https://docs.python.org/3/", repo: "https://github.com/python/cpython", oss: true, license: "PSF-2.0",
    deploy: ["self-hosted", "managed-cloud", "serverless"], langs: ["python"], free: true,
  }),
  t("typescript", "TypeScript", {
    company: "Microsoft", type: "language", cats: ["languages"], caps: ["language"],
    desc: "Typed superset of JavaScript used across frontend, backend and edge; the lingua franca of modern web stacks.",
    site: "https://www.typescriptlang.org", docs: "https://www.typescriptlang.org/docs/", repo: "https://github.com/microsoft/TypeScript", oss: true, license: "Apache-2.0",
    deploy: ["self-hosted"], langs: ["typescript"], free: true,
  }),
  t("clerk", "Clerk", {
    company: "Clerk", type: "service", cats: ["authentication", "authorization"], caps: ["authentication", "authorization", "sso", "mfa", "session-management"],
    desc: "Drop-in authentication and user management with prebuilt React components, organizations, MFA and SSO. Excellent Next.js developer experience.",
    site: "https://clerk.com", docs: "https://clerk.com/docs", pricingUrl: "https://clerk.com/pricing",
    deploy: ["managed-cloud"], langs: ["typescript", "javascript"], frameworks: ["nextjs", "react", "expo", "remix"], integrations: ["nextjs", "react", "expo", "supabase", "convex"], pricing: "freemium", free: true, pricingSummary: "Free up to 10,000 monthly active users, then per-MAU pricing", compliance: ["SOC 2", "GDPR", "HIPAA", "CCPA"], maturity: "growing",
  }),
  t("auth0", "Auth0", {
    company: "Okta", type: "service", cats: ["authentication", "authorization"], caps: ["authentication", "authorization", "sso", "mfa"],
    desc: "Enterprise identity platform with extensive protocol support, enterprise SSO connections and compliance certifications.",
    site: "https://auth0.com", docs: "https://auth0.com/docs", pricingUrl: "https://auth0.com/pricing",
    deploy: ["managed-cloud"], langs: ["typescript", "python", "java", "go", "csharp", "swift", "kotlin"], pricing: "freemium", free: true, pricingSummary: "Free tier, then per-MAU plans; enterprise features are paid", compliance: ["SOC 2", "HIPAA", "GDPR", "ISO 27001", "PCI DSS"], tags: ["enterprise"],
  }),
  t("auth-js", "Auth.js (NextAuth)", {
    type: "library", cats: ["authentication"], caps: ["authentication", "session-management"],
    desc: "Open-source authentication library for Next.js and other frameworks with OAuth providers, email and database sessions. No vendor, you own the user table.",
    site: "https://authjs.dev", docs: "https://authjs.dev/getting-started", repo: "https://github.com/nextauthjs/next-auth", oss: true, license: "ISC",
    deploy: ["self-hosted", "serverless", "edge"], langs: ["typescript"], frameworks: ["nextjs", "sveltekit"], integrations: ["nextjs", "prisma", "drizzle"], free: true, aliases: ["NextAuth"], icon: null,
  }),
  t("better-auth", "Better Auth", {
    type: "library", cats: ["authentication"], caps: ["authentication", "session-management", "mfa", "passkeys"],
    desc: "Framework-agnostic TypeScript authentication library with plugins for organizations, 2FA, passkeys and more, storing users in your own database.",
    site: "https://www.better-auth.com", docs: "https://www.better-auth.com/docs", repo: "https://github.com/better-auth/better-auth", oss: true, license: "MIT",
    deploy: ["self-hosted", "serverless"], langs: ["typescript"], integrations: ["drizzle", "prisma", "nextjs", "hono"], free: true, maturity: "emerging", icon: null,
  }),
  t("supabase-auth", "Supabase Auth", {
    company: "Supabase", type: "service", cats: ["authentication"], caps: ["authentication", "session-management", "sso", "mfa"],
    desc: "Postgres-backed authentication built into Supabase with row-level security integration, social logins and magic links.",
    site: "https://supabase.com/auth", docs: "https://supabase.com/docs/guides/auth", repo: "https://github.com/supabase/auth", oss: true, license: "MIT",
    deploy: ["managed-cloud", "self-hosted"], integrations: ["supabase", "postgresql", "nextjs"], pricing: "freemium", free: true, pricingSummary: "Included with Supabase plans", icon: "supabase",
  }),
  t("firebase-auth", "Firebase Authentication", {
    company: "Google", type: "service", cats: ["authentication"], caps: ["authentication", "mfa"],
    desc: "Google's mobile-first auth service with phone, social and anonymous login; tightly coupled to the Firebase ecosystem.",
    site: "https://firebase.google.com/products/auth", docs: "https://firebase.google.com/docs/auth", pricingUrl: "https://firebase.google.com/pricing",
    deploy: ["managed-cloud"], clouds: ["gcp"], langs: ["typescript", "swift", "kotlin", "dart"], integrations: ["firebase"], pricing: "freemium", free: true, pricingSummary: "Generous free tier; phone auth billed per verification", icon: "firebase",
  }),
  t("keycloak", "Keycloak", {
    company: "Red Hat", type: "platform", cats: ["authentication", "authorization"], caps: ["authentication", "authorization", "sso", "mfa"],
    desc: "Self-hosted open-source identity and access management with OIDC, SAML, user federation and fine-grained authorization.",
    site: "https://www.keycloak.org", docs: "https://www.keycloak.org/documentation", repo: "https://github.com/keycloak/keycloak", oss: true, license: "Apache-2.0",
    deploy: ["self-hosted"], langs: ["java"], free: true, tags: ["enterprise", "self-hosted"],
  }),
  t("workos", "WorkOS", {
    company: "WorkOS", type: "service", cats: ["authentication", "authorization"], caps: ["authentication", "sso", "authorization"],
    desc: "Enterprise-readiness APIs: SSO, SCIM directory sync, audit logs and AuthKit hosted authentication for B2B SaaS.",
    site: "https://workos.com", docs: "https://workos.com/docs", pricingUrl: "https://workos.com/pricing",
    deploy: ["managed-cloud"], pricing: "freemium", free: true, pricingSummary: "AuthKit free up to 1M MAU; SSO/SCIM priced per connection", compliance: ["SOC 2", "GDPR"], tags: ["b2b", "enterprise"],
  }),
  t("stytch", "Stytch", {
    company: "Stytch", type: "service", cats: ["authentication"], caps: ["authentication", "passkeys", "mfa", "sso"],
    desc: "API-first authentication with passwordless, passkeys, device fingerprinting and B2B organizations.",
    site: "https://stytch.com", docs: "https://stytch.com/docs", pricingUrl: "https://stytch.com/pricing",
    deploy: ["managed-cloud"], pricing: "freemium", free: true, pricingSummary: "Free tier, then per-MAU pricing", compliance: ["SOC 2", "GDPR"], icon: null,
  }),
  t("permit-io", "Permit.io", {
    company: "Permit.io", type: "service", cats: ["authorization"], caps: ["authorization"],
    desc: "Authorization-as-a-service with RBAC, ABAC and ReBAC policies backed by OPA and Cedar.",
    site: "https://www.permit.io", docs: "https://docs.permit.io", pricingUrl: "https://www.permit.io/pricing",
    deploy: ["managed-cloud", "self-hosted"], pricing: "freemium", free: true, pricingSummary: "Free tier, then usage-based plans", maturity: "growing", icon: null,
  }),
  t("open-policy-agent", "Open Policy Agent", {
    company: "CNCF", type: "tool", cats: ["authorization", "security"], caps: ["authorization"],
    desc: "General-purpose policy engine with the Rego language, used for API authorization, Kubernetes admission and infrastructure policy.",
    site: "https://www.openpolicyagent.org", docs: "https://www.openpolicyagent.org/docs/", repo: "https://github.com/open-policy-agent/opa", oss: true, license: "Apache-2.0",
    deploy: ["self-hosted"], langs: ["go"], free: true, aliases: ["OPA"], icon: "openpolicyagent" ,
  }),
  t("casbin", "Casbin", {
    type: "library", cats: ["authorization"], caps: ["authorization"],
    desc: "Authorization library supporting ACL, RBAC and ABAC models across many languages.",
    site: "https://casbin.org", docs: "https://casbin.org/docs/overview", repo: "https://github.com/casbin/casbin", oss: true, license: "Apache-2.0",
    deploy: ["self-hosted"], langs: ["go", "java", "python", "typescript", "csharp", "rust"], free: true, icon: null,
  }),
  t("stripe", "Stripe", {
    company: "Stripe", type: "api", cats: ["payments", "billing"], caps: ["payments", "billing"],
    desc: "The default developer payments platform: cards, wallets, subscriptions, invoicing, Connect for marketplaces and tax. Best-in-class API and docs.",
    site: "https://stripe.com", docs: "https://docs.stripe.com", pricingUrl: "https://stripe.com/pricing",
    deploy: ["managed-cloud"], langs: ["typescript", "python", "ruby", "go", "java", "php", "csharp"], pricing: "usage-based", free: true, pricingSummary: "No monthly fee; per-transaction pricing", compliance: ["PCI DSS", "SOC 2", "GDPR"],
  }),
  t("paddle", "Paddle", {
    company: "Paddle", type: "service", cats: ["payments", "billing"], caps: ["payments", "billing"],
    desc: "Merchant of record for SaaS that handles global sales tax, invoicing and subscriptions on your behalf.",
    site: "https://www.paddle.com", docs: "https://developer.paddle.com", pricingUrl: "https://www.paddle.com/pricing",
    deploy: ["managed-cloud"], pricing: "usage-based", pricingSummary: "Percentage per transaction; includes tax compliance", compliance: ["PCI DSS", "SOC 2"], tags: ["merchant-of-record"],
  }),
  t("lemon-squeezy", "Lemon Squeezy", {
    company: "Stripe", type: "service", cats: ["payments", "billing"], caps: ["payments", "billing"],
    desc: "Merchant-of-record checkout and subscriptions for digital products and SaaS, popular with indie developers.",
    site: "https://www.lemonsqueezy.com", docs: "https://docs.lemonsqueezy.com", pricingUrl: "https://www.lemonsqueezy.com/pricing",
    deploy: ["managed-cloud"], pricing: "usage-based", pricingSummary: "Percentage per transaction", tags: ["merchant-of-record", "indie"], icon: null,
  }),
  t("polar", "Polar", {
    company: "Polar", type: "service", cats: ["payments", "billing"], caps: ["payments", "billing"],
    desc: "Open-source merchant of record for developers selling SaaS and digital products, with usage-based billing and license keys.",
    site: "https://polar.sh", docs: "https://docs.polar.sh", repo: "https://github.com/polarsource/polar", oss: true, license: "Apache-2.0",
    deploy: ["managed-cloud"], pricing: "usage-based", pricingSummary: "Percentage per transaction", maturity: "emerging", icon: null,
  }),
  t("adyen", "Adyen", {
    company: "Adyen", type: "api", cats: ["payments"], caps: ["payments"],
    desc: "Enterprise global payments platform with unified commerce across online, mobile and in-store.",
    site: "https://www.adyen.com", docs: "https://docs.adyen.com", pricingUrl: "https://www.adyen.com/pricing",
    deploy: ["managed-cloud"], pricing: "usage-based", pricingSummary: "Interchange++ per transaction", compliance: ["PCI DSS"], tags: ["enterprise"],
  }),
  t("lago", "Lago", {
    company: "Lago", type: "platform", cats: ["billing"], caps: ["billing"],
    desc: "Open-source usage-based metering and billing engine; self-host or use the cloud version.",
    site: "https://www.getlago.com", docs: "https://docs.getlago.com", repo: "https://github.com/getlago/lago", oss: true, license: "AGPL-3.0",
    deploy: ["self-hosted", "managed-cloud"], integrations: ["stripe"], pricing: "freemium", free: true, maturity: "growing", icon: null,
  }),
  t("resend", "Resend", {
    company: "Resend", type: "api", cats: ["email"], caps: ["email"],
    desc: "Developer-first transactional email API with React Email templates and a clean dashboard.",
    site: "https://resend.com", docs: "https://resend.com/docs", pricingUrl: "https://resend.com/pricing",
    deploy: ["managed-cloud"], langs: ["typescript", "python", "go", "ruby", "php"], integrations: ["nextjs", "react"], pricing: "freemium", free: true, pricingSummary: "Free tier of monthly emails, then tiered plans", maturity: "growing", compliance: ["SOC 2", "GDPR"],
  }),
  t("postal", "Postal", {
    company: "Krystal", type: "platform", cats: ["email"], caps: ["email"],
    desc: "Open-source mail delivery platform you run yourself: SMTP and HTTP APIs, message queues, bounce handling, webhooks and a web UI.",
    site: "https://docs.postalserver.io", docs: "https://docs.postalserver.io", repo: "https://github.com/postalserver/postal", oss: true, license: "MIT",
    deploy: ["self-hosted"], free: true, maturity: "growing", tags: ["self-hosted"], icon: null,
  }),
  t("listmonk", "Listmonk", {
    type: "platform", cats: ["email"], caps: ["email", "notifications"],
    desc: "Self-hosted newsletter and mailing-list manager with templates, subscriber management and an HTTP API; pairs with any SMTP relay.",
    site: "https://listmonk.app", docs: "https://listmonk.app/docs/", repo: "https://github.com/knadh/listmonk", oss: true, license: "AGPL-3.0",
    deploy: ["self-hosted"], langs: ["go"], integrations: ["postgresql"], free: true, maturity: "growing", tags: ["self-hosted"], icon: null,
  }),
  t("sendgrid", "SendGrid", {
    company: "Twilio", type: "api", cats: ["email"], caps: ["email"],
    desc: "High-volume transactional and marketing email with mature deliverability tooling.",
    site: "https://sendgrid.com", docs: "https://www.twilio.com/docs/sendgrid", pricingUrl: "https://sendgrid.com/en-us/pricing",
    deploy: ["managed-cloud"], pricing: "freemium", free: true, pricingSummary: "Free trial tier, then volume-based plans", compliance: ["SOC 2", "GDPR"], icon: null,
  }),
  t("postmark", "Postmark", {
    company: "ActiveCampaign", type: "api", cats: ["email"], caps: ["email"],
    desc: "Transactional email service focused on fast, reliable delivery and templates.",
    site: "https://postmarkapp.com", docs: "https://postmarkapp.com/developer", pricingUrl: "https://postmarkapp.com/pricing",
    deploy: ["managed-cloud"], pricing: "freemium", free: true, pricingSummary: "Free developer tier, then volume plans", icon: null,
  }),
  t("amazon-ses", "Amazon SES", {
    company: "Amazon", type: "api", cats: ["email"], caps: ["email"],
    desc: "Cheapest high-volume email sending for teams already on AWS; requires more setup for deliverability.",
    site: "https://aws.amazon.com/ses/", docs: "https://docs.aws.amazon.com/ses/", pricingUrl: "https://aws.amazon.com/ses/pricing/",
    deploy: ["managed-cloud"], clouds: ["aws"], pricing: "usage-based", free: true, pricingSummary: "Pay per email; free tier for EC2-originated mail", compliance: ["HIPAA", "SOC 2", "PCI DSS"], icon: "amazonsimpleemailservice",
  }),
  t("twilio", "Twilio", {
    company: "Twilio", type: "api", cats: ["messaging", "notifications"], caps: ["telephony", "notifications", "sms"],
    desc: "Communication APIs for phone numbers, programmable voice, SMS, WhatsApp and verification; the default telephony layer for voice agents.",
    site: "https://www.twilio.com", docs: "https://www.twilio.com/docs", pricingUrl: "https://www.twilio.com/en-us/pricing",
    deploy: ["managed-cloud"], pricing: "usage-based", pricingSummary: "Pay per message or minute", compliance: ["SOC 2", "HIPAA", "GDPR"],
  }),
  t("telnyx", "Telnyx", {
    company: "Telnyx", type: "api", cats: ["messaging"], caps: ["telephony", "sms"],
    desc: "Carrier-grade telephony, SIP trunking, phone numbers and SMS on a private global network, with built-in voice AI features.",
    site: "https://telnyx.com", docs: "https://developers.telnyx.com", pricingUrl: "https://telnyx.com/pricing",
    deploy: ["managed-cloud"], pricing: "usage-based", pricingSummary: "Pay per minute and per message", compliance: ["SOC 2", "HIPAA", "GDPR"], icon: null,
  }),
  t("livekit", "LiveKit", {
    company: "LiveKit", type: "platform", cats: ["realtime", "speech", "ai-agents"], caps: ["telephony", "realtime", "ai-orchestration"],
    desc: "Open-source WebRTC infrastructure for real-time voice and video, with the LiveKit Agents framework for voice AI and SIP telephony; self-host or LiveKit Cloud.",
    site: "https://livekit.io", docs: "https://docs.livekit.io", repo: "https://github.com/livekit/livekit", pricingUrl: "https://livekit.io/pricing", oss: true, license: "Apache-2.0",
    deploy: ["self-hosted", "managed-cloud"], langs: ["python", "typescript", "go", "swift", "kotlin"], pricing: "freemium", free: true, compliance: ["SOC 2", "HIPAA", "GDPR"], maturity: "growing", tags: ["webrtc", "voice-ai"],
  }),
  t("vapi", "Vapi", {
    company: "Vapi", type: "platform", cats: ["ai-agents", "speech"], caps: ["telephony", "speech", "ai-orchestration"],
    desc: "Managed voice AI agent platform: phone numbers, speech-to-text, LLM and text-to-speech orchestrated with low latency via API.",
    site: "https://vapi.ai", docs: "https://docs.vapi.ai", pricingUrl: "https://vapi.ai/pricing",
    deploy: ["managed-cloud"], pricing: "usage-based", pricingSummary: "Per-minute platform fee plus provider costs", compliance: ["SOC 2", "HIPAA"], maturity: "emerging", tags: ["voice-ai"], icon: null,
  }),
  t("retell-ai", "Retell AI", {
    company: "Retell AI", type: "platform", cats: ["ai-agents", "speech"], caps: ["telephony", "speech", "ai-orchestration"],
    desc: "Platform for building, testing and deploying phone-call voice agents with telephony, turn-taking and analytics built in.",
    site: "https://www.retellai.com", docs: "https://docs.retellai.com", pricingUrl: "https://www.retellai.com/pricing",
    deploy: ["managed-cloud"], pricing: "usage-based", compliance: ["SOC 2", "HIPAA"], maturity: "emerging", tags: ["voice-ai"], icon: null,
  }),
  t("onesignal", "OneSignal", {
    company: "OneSignal", type: "service", cats: ["notifications"], caps: ["notifications"],
    desc: "Push notification, in-app messaging, email and SMS platform with mobile SDKs and segmentation.",
    site: "https://onesignal.com", docs: "https://documentation.onesignal.com", pricingUrl: "https://onesignal.com/pricing",
    deploy: ["managed-cloud"], langs: ["swift", "kotlin", "typescript", "dart"], pricing: "freemium", free: true, pricingSummary: "Free tier, then subscription plans",
  }),
  t("knock", "Knock", {
    company: "Knock", type: "service", cats: ["notifications"], caps: ["notifications", "email"],
    desc: "Notification infrastructure API: workflows, preferences, batching and in-app feeds across email, push, SMS and chat.",
    site: "https://knock.app", docs: "https://docs.knock.app", pricingUrl: "https://knock.app/pricing",
    deploy: ["managed-cloud"], pricing: "freemium", free: true, pricingSummary: "Free tier, then usage-based plans", maturity: "growing", icon: null,
  }),
  t("novu", "Novu", {
    company: "Novu", type: "platform", cats: ["notifications"], caps: ["notifications"],
    desc: "Open-source notification infrastructure with an in-app inbox component and multi-channel workflows.",
    site: "https://novu.co", docs: "https://docs.novu.co", repo: "https://github.com/novuhq/novu", oss: true, license: "MIT",
    deploy: ["self-hosted", "managed-cloud"], pricing: "freemium", free: true, maturity: "growing", icon: null,
  }),
  t("firebase-cloud-messaging", "Firebase Cloud Messaging", {
    company: "Google", type: "service", cats: ["notifications"], caps: ["notifications"],
    desc: "Free cross-platform push notification delivery for iOS, Android and web.",
    site: "https://firebase.google.com/products/cloud-messaging", docs: "https://firebase.google.com/docs/cloud-messaging",
    deploy: ["managed-cloud"], clouds: ["gcp"], pricing: "free", free: true, integrations: ["firebase"], icon: "firebase", aliases: ["FCM"],
  }),
  t("kong", "Kong Gateway", {
    company: "Kong", type: "platform", cats: ["api-gateways"], caps: ["api-gateway"],
    desc: "High-performance API gateway with plugins for auth, rate limiting and observability; open-source core and enterprise edition.",
    site: "https://konghq.com", docs: "https://docs.konghq.com", repo: "https://github.com/Kong/kong", oss: true, license: "Apache-2.0",
    deploy: ["self-hosted", "managed-cloud"], pricing: "freemium", free: true, pricingSummary: "Open-source gateway; Konnect and Enterprise are paid",
  }),
  t("aws-api-gateway", "Amazon API Gateway", {
    company: "Amazon", type: "service", cats: ["api-gateways", "serverless"], caps: ["api-gateway"],
    desc: "Managed API gateway for REST, HTTP and WebSocket APIs in front of Lambda and other AWS services.",
    site: "https://aws.amazon.com/api-gateway/", docs: "https://docs.aws.amazon.com/apigateway/", pricingUrl: "https://aws.amazon.com/api-gateway/pricing/",
    deploy: ["managed-cloud"], clouds: ["aws"], pricing: "usage-based", free: true, compliance: ["HIPAA", "SOC 2", "PCI DSS"], icon: "amazonapigateway",
  }),
  t("unkey", "Unkey", {
    company: "Unkey", type: "service", cats: ["api-gateways"], caps: ["api-gateway"],
    desc: "Open-source API key management and rate limiting for developer APIs.",
    site: "https://www.unkey.com", docs: "https://www.unkey.com/docs", repo: "https://github.com/unkeyed/unkey", oss: true, license: "AGPL-3.0",
    deploy: ["managed-cloud", "self-hosted"], pricing: "freemium", free: true, maturity: "emerging", icon: null,
  }),
  t("zuplo", "Zuplo", {
    company: "Zuplo", type: "service", cats: ["api-gateways"], caps: ["api-gateway"],
    desc: "Programmable, edge-deployed API gateway with developer portal, API keys and rate limiting configured in code.",
    site: "https://zuplo.com", docs: "https://zuplo.com/docs", pricingUrl: "https://zuplo.com/pricing",
    deploy: ["managed-cloud", "edge"], pricing: "freemium", free: true, maturity: "emerging", icon: null,
  }),
  t("shopify", "Shopify", {
    company: "Shopify", type: "platform", cats: ["ecommerce", "payments"], caps: ["ecommerce", "payments"],
    desc: "Hosted commerce platform with Storefront API and Hydrogen headless framework for custom storefronts.",
    site: "https://www.shopify.com", docs: "https://shopify.dev/docs", pricingUrl: "https://www.shopify.com/pricing",
    deploy: ["managed-cloud"], pricing: "subscription", pricingSummary: "Monthly plans plus transaction fees", compliance: ["PCI DSS"],
  }),
  t("medusa", "Medusa", {
    company: "Medusa", type: "framework", cats: ["ecommerce", "backend-frameworks"], caps: ["ecommerce"],
    desc: "Open-source, Node.js headless commerce engine with modular cart, orders, inventory and payment plugins.",
    site: "https://medusajs.com", docs: "https://docs.medusajs.com", repo: "https://github.com/medusajs/medusa", oss: true, license: "MIT",
    deploy: ["self-hosted", "managed-cloud"], langs: ["typescript"], integrations: ["postgresql", "stripe", "nextjs"], free: true, maturity: "growing",
  }),
  t("saleor", "Saleor", {
    company: "Saleor", type: "platform", cats: ["ecommerce"], caps: ["ecommerce"],
    desc: "Open-source GraphQL-first headless commerce platform written in Python.",
    site: "https://saleor.io", docs: "https://docs.saleor.io", repo: "https://github.com/saleor/saleor", oss: true, license: "BSD-3-Clause",
    deploy: ["self-hosted", "managed-cloud"], langs: ["python"], integrations: ["graphql", "postgresql"], pricing: "freemium", free: true, icon: null,
  }),
  t("zod", "Zod", {
    type: "library", cats: ["developer-tools", "apis"], caps: ["api-backend"],
    desc: "TypeScript-first schema validation with static type inference, used at API boundaries and for structured LLM output.",
    site: "https://zod.dev", docs: "https://zod.dev", repo: "https://github.com/colinhacks/zod", oss: true, license: "MIT",
    deploy: ["self-hosted"], langs: ["typescript"], free: true,
  }),
  t("pydantic", "Pydantic", {
    company: "Pydantic", type: "library", cats: ["developer-tools", "apis"], caps: ["api-backend"],
    desc: "Data validation for Python using type hints; the foundation of FastAPI and most Python AI tooling.",
    site: "https://pydantic.dev", docs: "https://docs.pydantic.dev", repo: "https://github.com/pydantic/pydantic", oss: true, license: "MIT",
    deploy: ["self-hosted"], langs: ["python"], free: true,
  }),
];
