import { t } from "./helper";

export const DATA = [
  t("postgresql", "PostgreSQL", {
    company: "PostgreSQL Global Development Group", type: "database", cats: ["sql-databases", "databases"], caps: ["relational-db"],
    desc: "The most capable open-source relational database: ACID transactions, rich indexing, JSONB, full-text search and extensions such as pgvector and PostGIS. Available managed on every cloud.",
    site: "https://www.postgresql.org", docs: "https://www.postgresql.org/docs/", repo: "https://github.com/postgres/postgres", oss: true, license: "PostgreSQL",
    deploy: ["self-hosted", "managed-cloud"], clouds: ["aws", "gcp", "azure", "neon", "supabase"], langs: ["python", "typescript", "go", "java", "ruby", "rust", "php", "csharp"], integrations: ["pgvector", "prisma", "drizzle", "sqlalchemy", "supabase", "neon"], free: true, aliases: ["Postgres"], tags: ["sql", "relational", "acid"], useCases: ["transactional app data", "multi-tenant SaaS", "analytics at moderate scale"],
  }),
  t("mysql", "MySQL", {
    company: "Oracle", type: "database", cats: ["sql-databases", "databases"], caps: ["relational-db"],
    desc: "Widely deployed open-source relational database with broad hosting support; PostgreSQL has overtaken it for new projects but it remains a solid choice.",
    site: "https://www.mysql.com", docs: "https://dev.mysql.com/doc/", repo: "https://github.com/mysql/mysql-server", oss: true, license: "GPL-2.0",
    deploy: ["self-hosted", "managed-cloud"], clouds: ["aws", "gcp", "azure", "planetscale"], free: true,
  }),
  t("sqlite", "SQLite", {
    type: "database", cats: ["sql-databases", "databases"], caps: ["relational-db", "sqlite"],
    desc: "Embedded, zero-configuration SQL database stored in a single file. Ideal for local-first apps, on-device storage and small single-server deployments.",
    site: "https://sqlite.org", docs: "https://sqlite.org/docs.html", oss: true, license: "Public Domain",
    deploy: ["on-device", "self-hosted", "desktop"], free: true, tags: ["embedded", "local-first"], useCases: ["local-first", "mobile storage", "edge replicas"],
  }),
  t("supabase", "Supabase", {
    company: "Supabase", type: "platform", cats: ["sql-databases", "databases", "authentication", "storage", "realtime"], caps: ["relational-db", "authentication", "object-storage", "realtime", "backend-as-a-service", "vector-db", "edge-functions"],
    desc: "Open-source Firebase alternative on Postgres: managed database, auth, storage, realtime subscriptions, edge functions and pgvector in one project. The strongest Firebase replacement for teams wanting SQL.",
    site: "https://supabase.com", docs: "https://supabase.com/docs", repo: "https://github.com/supabase/supabase", pricingUrl: "https://supabase.com/pricing", oss: true, license: "Apache-2.0",
    deploy: ["managed-cloud", "self-hosted"], clouds: ["aws"], langs: ["typescript", "python", "swift", "kotlin", "dart"], frameworks: ["nextjs", "react-native", "flutter"], integrations: ["postgresql", "pgvector", "nextjs", "expo", "vercel"], pricing: "freemium", free: true, pricingSummary: "Free tier with two projects; Pro from a flat monthly fee plus usage", compliance: ["SOC 2", "HIPAA", "GDPR"], tags: ["baas", "firebase-alternative"], useCases: ["MVPs", "Firebase replacement", "small team backends"],
  }),
  t("neon", "Neon", {
    company: "Databricks", type: "service", cats: ["sql-databases", "databases"], caps: ["relational-db", "database-branching"],
    desc: "Serverless Postgres with autoscaling, scale-to-zero and database branching for preview environments. Excellent with Vercel and serverless backends.",
    site: "https://neon.com", docs: "https://neon.com/docs/introduction", repo: "https://github.com/neondatabase/neon", pricingUrl: "https://neon.com/pricing", oss: true, license: "Apache-2.0",
    deploy: ["managed-cloud"], clouds: ["aws", "azure", "vercel"], integrations: ["postgresql", "vercel", "drizzle", "prisma"], pricing: "freemium", free: true, pricingSummary: "Free tier, then usage-based compute and storage", compliance: ["SOC 2", "HIPAA", "GDPR"], maturity: "growing", tags: ["serverless-postgres"],
  }),
  t("planetscale", "PlanetScale", {
    company: "PlanetScale", type: "service", cats: ["sql-databases", "databases"], caps: ["relational-db", "database-branching"],
    desc: "Managed MySQL (Vitess) and Postgres with branching, non-blocking schema changes and horizontal sharding for very large workloads.",
    site: "https://planetscale.com", docs: "https://planetscale.com/docs", pricingUrl: "https://planetscale.com/pricing",
    deploy: ["managed-cloud"], clouds: ["aws", "gcp"], integrations: ["mysql", "postgresql", "prisma", "drizzle"], pricing: "subscription", free: false, pricingSummary: "Paid plans; no free tier", compliance: ["SOC 2", "HIPAA", "GDPR"], tags: ["scale"],
  }),
  t("cockroachdb", "CockroachDB", {
    company: "Cockroach Labs", type: "database", cats: ["sql-databases", "databases"], caps: ["relational-db"],
    desc: "Distributed SQL database with Postgres wire compatibility, multi-region survivability and horizontal scale.",
    site: "https://www.cockroachlabs.com", docs: "https://www.cockroachlabs.com/docs/", repo: "https://github.com/cockroachdb/cockroach", pricingUrl: "https://www.cockroachlabs.com/pricing/",
    deploy: ["managed-cloud", "self-hosted"], clouds: ["aws", "gcp", "azure"], pricing: "freemium", free: true, pricingSummary: "Free serverless tier, then usage-based", compliance: ["SOC 2", "PCI DSS", "HIPAA"], tags: ["distributed", "multi-region"], icon: null,
  }),
  t("amazon-rds", "Amazon RDS / Aurora", {
    company: "Amazon", type: "service", cats: ["sql-databases", "databases"], caps: ["relational-db"],
    desc: "AWS managed relational databases including Aurora, a cloud-native Postgres/MySQL-compatible engine with serverless and global options.",
    site: "https://aws.amazon.com/rds/", docs: "https://docs.aws.amazon.com/rds/", pricingUrl: "https://aws.amazon.com/rds/pricing/",
    deploy: ["managed-cloud"], clouds: ["aws"], integrations: ["postgresql", "mysql"], pricing: "usage-based", free: true, pricingSummary: "Instance hours plus storage; free tier for small instances", compliance: ["HIPAA", "SOC 2", "PCI DSS", "FedRAMP", "GDPR"], aliases: ["Aurora", "RDS"], icon: "amazonrds",
  }),
  t("cloud-sql", "Google Cloud SQL / AlloyDB", {
    company: "Google", type: "service", cats: ["sql-databases", "databases"], caps: ["relational-db"],
    desc: "Google Cloud's managed Postgres and MySQL, plus AlloyDB for high-performance Postgres-compatible workloads.",
    site: "https://cloud.google.com/sql", docs: "https://cloud.google.com/sql/docs", pricingUrl: "https://cloud.google.com/sql/pricing",
    deploy: ["managed-cloud"], clouds: ["gcp"], integrations: ["postgresql", "mysql"], pricing: "usage-based", compliance: ["HIPAA", "SOC 2", "PCI DSS", "GDPR"], aliases: ["AlloyDB"], icon: "googlecloud",
  }),
  t("azure-sql", "Azure Database for PostgreSQL", {
    company: "Microsoft", type: "service", cats: ["sql-databases", "databases"], caps: ["relational-db"],
    desc: "Azure's managed Postgres (Flexible Server) alongside Azure SQL for Microsoft-centric estates.",
    site: "https://azure.microsoft.com/products/postgresql", docs: "https://learn.microsoft.com/azure/postgresql/",
    deploy: ["managed-cloud"], clouds: ["azure"], integrations: ["postgresql"], pricing: "usage-based", compliance: ["HIPAA", "SOC 2", "PCI DSS", "FedRAMP", "GDPR"], icon: null,
  }),
  t("turso", "Turso", {
    company: "Turso", type: "service", cats: ["sql-databases", "databases"], caps: ["relational-db", "sqlite"],
    desc: "Managed SQLite (libSQL) with embedded replicas and per-tenant databases; great for edge and local-first apps.",
    site: "https://turso.tech", docs: "https://docs.turso.tech", repo: "https://github.com/tursodatabase/libsql", pricingUrl: "https://turso.tech/pricing", oss: true, license: "MIT",
    deploy: ["managed-cloud", "edge", "on-device"], integrations: ["sqlite", "drizzle"], pricing: "freemium", free: true, maturity: "growing", tags: ["sqlite", "edge", "multi-tenant"], icon: null,
  }),
  t("mongodb", "MongoDB", {
    company: "MongoDB", type: "database", cats: ["nosql-databases", "databases"], caps: ["nosql-db", "vector-db"],
    desc: "Document database with flexible schemas, Atlas managed cloud, and built-in vector and full-text search in Atlas.",
    site: "https://www.mongodb.com", docs: "https://www.mongodb.com/docs/", repo: "https://github.com/mongodb/mongo", pricingUrl: "https://www.mongodb.com/pricing", oss: true, license: "SSPL-1.0",
    deploy: ["managed-cloud", "self-hosted"], clouds: ["aws", "gcp", "azure"], integrations: ["mongoose", "prisma"], pricing: "freemium", free: true, pricingSummary: "Atlas free tier, then usage-based clusters", compliance: ["SOC 2", "HIPAA", "PCI DSS", "GDPR"], tags: ["document"],
  }),
  t("dynamodb", "Amazon DynamoDB", {
    company: "Amazon", type: "service", cats: ["nosql-databases", "databases"], caps: ["nosql-db"],
    desc: "Fully managed serverless key-value and document database with single-digit millisecond latency at any scale; requires access-pattern-first modeling.",
    site: "https://aws.amazon.com/dynamodb/", docs: "https://docs.aws.amazon.com/dynamodb/", pricingUrl: "https://aws.amazon.com/dynamodb/pricing/",
    deploy: ["managed-cloud"], clouds: ["aws"], pricing: "usage-based", free: true, pricingSummary: "Pay per request or provisioned capacity; free tier", compliance: ["HIPAA", "SOC 2", "PCI DSS", "FedRAMP"], icon: "amazondynamodb",
  }),
  t("firebase", "Firebase (Firestore)", {
    company: "Google", type: "platform", cats: ["nosql-databases", "databases", "authentication", "hosting", "realtime"], caps: ["nosql-db", "realtime", "authentication", "hosting", "backend-as-a-service", "object-storage", "notifications"],
    desc: "Google's mobile backend-as-a-service: Firestore document database with realtime sync, auth, storage, hosting, functions and messaging. Fast to start; harder to leave and to query relationally.",
    site: "https://firebase.google.com", docs: "https://firebase.google.com/docs", pricingUrl: "https://firebase.google.com/pricing",
    deploy: ["managed-cloud"], clouds: ["gcp"], langs: ["typescript", "swift", "kotlin", "dart"], pricing: "freemium", free: true, pricingSummary: "Spark free tier; Blaze pay as you go", compliance: ["SOC 2", "HIPAA", "GDPR", "ISO 27001"], aliases: ["Firestore", "Firebase Realtime Database"], tags: ["baas", "mobile"],
  }),
  t("convex", "Convex", {
    company: "Convex", type: "platform", cats: ["databases", "realtime", "backend-frameworks"], caps: ["nosql-db", "realtime", "api-backend", "backend-as-a-service", "workers", "scheduler", "vector-db"],
    desc: "Reactive backend platform: TypeScript functions, a transactional document database with realtime subscriptions, scheduling, file storage and vector search.",
    site: "https://www.convex.dev", docs: "https://docs.convex.dev", repo: "https://github.com/get-convex/convex-backend", pricingUrl: "https://www.convex.dev/pricing", oss: true, license: "FSL-1.1-Apache-2.0",
    deploy: ["managed-cloud", "self-hosted"], langs: ["typescript"], frameworks: ["react", "nextjs", "react-native"], integrations: ["nextjs", "clerk", "react"], pricing: "freemium", free: true, maturity: "growing", tags: ["reactive", "baas", "firebase-alternative"], icon: null,
  }),
  t("redis", "Redis", {
    company: "Redis", type: "database", cats: ["caching", "nosql-databases"], caps: ["cache", "queue", "realtime", "vector-db"],
    desc: "In-memory data structure store used for caching, sessions, rate limiting, pub/sub, queues and (with Redis Stack) vector search. The default cache.",
    site: "https://redis.io", docs: "https://redis.io/docs/latest/", repo: "https://github.com/redis/redis", pricingUrl: "https://redis.io/pricing/", oss: true, license: "AGPL-3.0",
    deploy: ["self-hosted", "managed-cloud"], clouds: ["aws", "gcp", "azure", "upstash"], integrations: ["bullmq", "sidekiq", "celery", "upstash"], pricing: "freemium", free: true, pricingSummary: "Open-source server; Redis Cloud has a free tier", tags: ["in-memory", "cache", "pubsub"],
  }),
  t("valkey", "Valkey", {
    company: "Linux Foundation", type: "database", cats: ["caching", "nosql-databases"], caps: ["cache", "queue", "realtime"],
    desc: "BSD-licensed fork of Redis backed by the Linux Foundation and major clouds; drop-in compatible for caching and pub/sub.",
    site: "https://valkey.io", docs: "https://valkey.io/docs/", repo: "https://github.com/valkey-io/valkey", oss: true, license: "BSD-3-Clause",
    deploy: ["self-hosted", "managed-cloud"], clouds: ["aws", "gcp"], free: true, maturity: "growing", icon: null,
  }),
  t("upstash", "Upstash", {
    company: "Upstash", type: "service", cats: ["caching", "queues"], caps: ["cache", "queue", "scheduler", "vector-db"],
    desc: "Serverless Redis, Kafka, QStash message scheduling and a vector database with HTTP APIs and per-request pricing; ideal for serverless and edge apps.",
    site: "https://upstash.com", docs: "https://upstash.com/docs", pricingUrl: "https://upstash.com/pricing",
    deploy: ["managed-cloud", "serverless"], clouds: ["aws", "gcp", "vercel", "cloudflare"], integrations: ["redis", "vercel", "nextjs", "cloudflare-workers"], pricing: "freemium", free: true, pricingSummary: "Free tier, then per-request pricing", compliance: ["SOC 2", "GDPR", "HIPAA"], maturity: "growing", tags: ["serverless", "edge"],
  }),
  t("memcached", "Memcached", {
    type: "database", cats: ["caching"], caps: ["cache"],
    desc: "Simple, high-performance distributed memory cache; fewer features than Redis, minimal operational surface.",
    site: "https://memcached.org", docs: "https://github.com/memcached/memcached/wiki", repo: "https://github.com/memcached/memcached", oss: true, license: "BSD-3-Clause",
    deploy: ["self-hosted", "managed-cloud"], clouds: ["aws", "gcp"], free: true, icon: null,
  }),
  t("dragonfly", "Dragonfly", {
    company: "DragonflyDB", type: "database", cats: ["caching"], caps: ["cache"],
    desc: "Multi-threaded, Redis-compatible in-memory store built for vertical scale on modern hardware.",
    site: "https://www.dragonflydb.io", docs: "https://www.dragonflydb.io/docs", repo: "https://github.com/dragonflydb/dragonfly", oss: true, license: "BSL-1.1",
    deploy: ["self-hosted", "managed-cloud"], free: true, maturity: "growing", icon: null,
  }),
  t("amazon-s3", "Amazon S3", {
    company: "Amazon", type: "service", cats: ["storage"], caps: ["object-storage"],
    desc: "The reference object storage service: eleven nines durability, lifecycle policies, event notifications and a universally supported API.",
    site: "https://aws.amazon.com/s3/", docs: "https://docs.aws.amazon.com/s3/", pricingUrl: "https://aws.amazon.com/s3/pricing/",
    deploy: ["managed-cloud"], clouds: ["aws"], pricing: "usage-based", free: true, pricingSummary: "Per GB stored and per request; free tier", compliance: ["HIPAA", "SOC 2", "PCI DSS", "FedRAMP", "GDPR"], aliases: ["S3"], icon: "amazons3",
  }),
  t("cloudflare-r2", "Cloudflare R2", {
    company: "Cloudflare", type: "service", cats: ["storage"], caps: ["object-storage"],
    desc: "S3-compatible object storage with zero egress fees, making it the cheapest choice for media-heavy products.",
    site: "https://www.cloudflare.com/developer-platform/products/r2/", docs: "https://developers.cloudflare.com/r2/", pricingUrl: "https://developers.cloudflare.com/r2/pricing/",
    deploy: ["managed-cloud", "edge"], clouds: ["cloudflare"], integrations: ["cloudflare-workers", "amazon-s3"], pricing: "usage-based", free: true, pricingSummary: "Free tier; per GB stored, no egress fees", compliance: ["SOC 2", "GDPR", "ISO 27001"], aliases: ["R2"], icon: "cloudflare",
  }),
  t("google-cloud-storage", "Google Cloud Storage", {
    company: "Google", type: "service", cats: ["storage"], caps: ["object-storage"],
    desc: "Google Cloud's unified object storage with multi-region buckets and tight integration with BigQuery and Vertex AI.",
    site: "https://cloud.google.com/storage", docs: "https://cloud.google.com/storage/docs", pricingUrl: "https://cloud.google.com/storage/pricing",
    deploy: ["managed-cloud"], clouds: ["gcp"], pricing: "usage-based", free: true, compliance: ["HIPAA", "SOC 2", "PCI DSS", "GDPR"], icon: "googlecloudstorage",
  }),
  t("azure-blob-storage", "Azure Blob Storage", {
    company: "Microsoft", type: "service", cats: ["storage"], caps: ["object-storage"],
    desc: "Azure's object storage for unstructured data with hot, cool and archive tiers.",
    site: "https://azure.microsoft.com/products/storage/blobs", docs: "https://learn.microsoft.com/azure/storage/blobs/",
    deploy: ["managed-cloud"], clouds: ["azure"], pricing: "usage-based", compliance: ["HIPAA", "SOC 2", "PCI DSS", "FedRAMP", "GDPR"], icon: null,
  }),
  t("minio", "MinIO", {
    company: "MinIO", type: "platform", cats: ["storage"], caps: ["object-storage"],
    desc: "High-performance, S3-compatible object storage you can self-host on any infrastructure, including on-prem and Kubernetes.",
    site: "https://min.io", docs: "https://min.io/docs/minio/linux/index.html", repo: "https://github.com/minio/minio", oss: true, license: "AGPL-3.0",
    deploy: ["self-hosted"], integrations: ["amazon-s3", "kubernetes"], free: true, tags: ["self-hosted", "s3-compatible"],
  }),
  t("seaweedfs", "SeaweedFS", {
    type: "platform", cats: ["storage"], caps: ["object-storage"],
    desc: "Fast distributed object and file store with an S3-compatible API, built for billions of files; a common self-hosted replacement for MinIO.",
    site: "https://github.com/seaweedfs/seaweedfs", docs: "https://github.com/seaweedfs/seaweedfs/wiki", repo: "https://github.com/seaweedfs/seaweedfs", oss: true, license: "Apache-2.0",
    deploy: ["self-hosted"], integrations: ["amazon-s3", "kubernetes"], free: true, maturity: "established", tags: ["self-hosted", "s3-compatible"], icon: null,
  }),
  t("garage", "Garage", {
    company: "Deuxfleurs", type: "platform", cats: ["storage"], caps: ["object-storage"],
    desc: "Lightweight, geo-distributed S3-compatible object storage designed for self-hosting on modest hardware.",
    site: "https://garagehq.deuxfleurs.fr", docs: "https://garagehq.deuxfleurs.fr/documentation/", repo: "https://git.deuxfleurs.fr/Deuxfleurs/garage", oss: true, license: "AGPL-3.0",
    deploy: ["self-hosted"], integrations: ["amazon-s3"], free: true, maturity: "growing", tags: ["self-hosted", "s3-compatible", "lightweight"], icon: null,
  }),
  t("ceph", "Ceph", {
    company: "Ceph Foundation", type: "platform", cats: ["storage"], caps: ["object-storage", "block-storage"],
    desc: "Battle-tested unified storage (object via RGW with an S3 API, block and file) for large self-managed clusters; operationally heavy.",
    site: "https://ceph.io", docs: "https://docs.ceph.com", repo: "https://github.com/ceph/ceph", oss: true, license: "LGPL-2.1",
    deploy: ["self-hosted"], integrations: ["kubernetes", "amazon-s3"], free: true, maturity: "established", tags: ["self-hosted", "heavy", "s3-compatible"],
  }),
  t("vercel-blob", "Vercel Blob", {
    company: "Vercel", type: "service", cats: ["storage"], caps: ["object-storage"],
    desc: "Simple object storage integrated with Vercel deployments for uploads and generated assets.",
    site: "https://vercel.com/storage/blob", docs: "https://vercel.com/docs/vercel-blob", pricingUrl: "https://vercel.com/docs/vercel-blob/usage-and-pricing",
    deploy: ["managed-cloud"], clouds: ["vercel"], integrations: ["vercel", "nextjs"], pricing: "usage-based", free: true, maturity: "growing", icon: "vercel",
  }),
  t("uploadthing", "UploadThing", {
    company: "Ping Labs", type: "service", cats: ["storage"], caps: ["object-storage"],
    desc: "File uploads for full-stack TypeScript apps with typed routes and React components on top of S3-class storage.",
    site: "https://uploadthing.com", docs: "https://docs.uploadthing.com", pricingUrl: "https://uploadthing.com/pricing",
    deploy: ["managed-cloud"], langs: ["typescript"], frameworks: ["nextjs", "react"], pricing: "freemium", free: true, maturity: "emerging", icon: null,
  }),
  t("pgvector", "pgvector", {
    type: "library", cats: ["vector-databases"], caps: ["vector-db"],
    desc: "Postgres extension adding vector types, HNSW/IVFFlat indexes and similarity operators. Keeps embeddings next to relational data with no extra service.",
    site: "https://github.com/pgvector/pgvector", docs: "https://github.com/pgvector/pgvector#readme", repo: "https://github.com/pgvector/pgvector", oss: true, license: "PostgreSQL",
    deploy: ["self-hosted", "managed-cloud"], clouds: ["aws", "gcp", "azure", "neon", "supabase"], integrations: ["postgresql", "supabase", "neon"], free: true, tags: ["postgres", "vector"], useCases: ["RAG under tens of millions of vectors", "hybrid SQL + vector queries"], icon: "postgresql",
  }),
  t("pinecone", "Pinecone", {
    company: "Pinecone", type: "service", cats: ["vector-databases"], caps: ["vector-db"],
    desc: "Fully managed serverless vector database with namespaces, metadata filtering, integrated inference and hybrid search at large scale.",
    site: "https://www.pinecone.io", docs: "https://docs.pinecone.io", pricingUrl: "https://www.pinecone.io/pricing/",
    deploy: ["managed-cloud"], clouds: ["aws", "gcp", "azure"], pricing: "freemium", free: true, pricingSummary: "Free starter tier, then usage-based serverless", compliance: ["SOC 2", "HIPAA", "GDPR"], tags: ["managed", "scale"], icon: null,
  }),
  t("qdrant", "Qdrant", {
    company: "Qdrant", type: "database", cats: ["vector-databases"], caps: ["vector-db"],
    desc: "Open-source Rust vector database with rich payload filtering, quantization and a managed cloud; strong choice for self-hosting.",
    site: "https://qdrant.tech", docs: "https://qdrant.tech/documentation/", repo: "https://github.com/qdrant/qdrant", pricingUrl: "https://qdrant.tech/pricing/", oss: true, license: "Apache-2.0",
    deploy: ["self-hosted", "managed-cloud", "on-device"], clouds: ["aws", "gcp", "azure"], pricing: "freemium", free: true, pricingSummary: "Free to self-host; cloud free tier", tags: ["rust", "self-hosted"],
  }),
  t("weaviate", "Weaviate", {
    company: "Weaviate", type: "database", cats: ["vector-databases"], caps: ["vector-db"],
    desc: "Open-source AI-native vector database with built-in vectorizer modules, hybrid search and multi-tenancy.",
    site: "https://weaviate.io", docs: "https://weaviate.io/developers/weaviate", repo: "https://github.com/weaviate/weaviate", pricingUrl: "https://weaviate.io/pricing", oss: true, license: "BSD-3-Clause",
    deploy: ["self-hosted", "managed-cloud"], pricing: "freemium", free: true, icon: null,
  }),
  t("milvus", "Milvus", {
    company: "Zilliz", type: "database", cats: ["vector-databases"], caps: ["vector-db"],
    desc: "Open-source distributed vector database built for billion-scale similarity search, with Zilliz Cloud as the managed option.",
    site: "https://milvus.io", docs: "https://milvus.io/docs", repo: "https://github.com/milvus-io/milvus", oss: true, license: "Apache-2.0",
    deploy: ["self-hosted", "managed-cloud"], free: true, tags: ["scale"], icon: null,
  }),
  t("chroma", "Chroma", {
    company: "Chroma", type: "database", cats: ["vector-databases"], caps: ["vector-db"],
    desc: "Developer-friendly open-source embedding database with an in-process mode; ideal for prototypes and local RAG.",
    site: "https://www.trychroma.com", docs: "https://docs.trychroma.com", repo: "https://github.com/chroma-core/chroma", oss: true, license: "Apache-2.0",
    deploy: ["on-device", "self-hosted", "managed-cloud"], langs: ["python", "typescript"], free: true, maturity: "growing", tags: ["local", "prototype"], icon: null,
  }),
  t("lancedb", "LanceDB", {
    company: "LanceDB", type: "database", cats: ["vector-databases", "data-lakes"], caps: ["vector-db"],
    desc: "Embedded, serverless vector database on the Lance columnar format; runs in-process and stores data on object storage. Great for local-first and multimodal data.",
    site: "https://lancedb.com", docs: "https://lancedb.github.io/lancedb/", repo: "https://github.com/lancedb/lancedb", oss: true, license: "Apache-2.0",
    deploy: ["on-device", "self-hosted", "managed-cloud"], langs: ["python", "typescript", "rust"], free: true, maturity: "growing", tags: ["embedded", "local-first"], icon: null,
  }),
  t("turbopuffer", "turbopuffer", {
    company: "turbopuffer", type: "service", cats: ["vector-databases", "search"], caps: ["vector-db", "search-engine"],
    desc: "Serverless vector and full-text search built on object storage, priced for very large multi-tenant workloads.",
    site: "https://turbopuffer.com", docs: "https://turbopuffer.com/docs", pricingUrl: "https://turbopuffer.com/pricing",
    deploy: ["managed-cloud"], pricing: "usage-based", maturity: "emerging", tags: ["object-storage-native"], icon: null,
  }),
  t("elasticsearch", "Elasticsearch", {
    company: "Elastic", type: "database", cats: ["search", "vector-databases", "logging"], caps: ["search-engine", "vector-db", "logging"],
    desc: "Distributed search and analytics engine with full-text, aggregations and vector search; also the core of the ELK logging stack.",
    site: "https://www.elastic.co/elasticsearch", docs: "https://www.elastic.co/docs", repo: "https://github.com/elastic/elasticsearch", pricingUrl: "https://www.elastic.co/pricing", oss: true, license: "AGPL-3.0",
    deploy: ["self-hosted", "managed-cloud"], clouds: ["aws", "gcp", "azure"], pricing: "freemium", free: true, compliance: ["SOC 2", "HIPAA", "GDPR"], tags: ["heavy", "enterprise"],
  }),
  t("opensearch", "OpenSearch", {
    company: "Linux Foundation", type: "database", cats: ["search", "vector-databases", "logging"], caps: ["search-engine", "vector-db", "logging"],
    desc: "Apache-licensed Elasticsearch fork backed by AWS with full-text, vector and log analytics; managed as Amazon OpenSearch Service.",
    site: "https://opensearch.org", docs: "https://docs.opensearch.org", repo: "https://github.com/opensearch-project/OpenSearch", oss: true, license: "Apache-2.0",
    deploy: ["self-hosted", "managed-cloud"], clouds: ["aws"], free: true,
  }),
  t("meilisearch", "Meilisearch", {
    company: "Meilisearch", type: "database", cats: ["search"], caps: ["search-engine", "vector-db"],
    desc: "Fast, typo-tolerant open-source search engine with an instant-search developer experience and hybrid semantic search.",
    site: "https://www.meilisearch.com", docs: "https://www.meilisearch.com/docs", repo: "https://github.com/meilisearch/meilisearch", pricingUrl: "https://www.meilisearch.com/pricing", oss: true, license: "MIT",
    deploy: ["self-hosted", "managed-cloud"], pricing: "freemium", free: true, maturity: "growing", tags: ["rust", "instant-search"],
  }),
  t("typesense", "Typesense", {
    company: "Typesense", type: "database", cats: ["search"], caps: ["search-engine", "vector-db"],
    desc: "Open-source, typo-tolerant search engine optimized for instant search with simple operations; Algolia alternative.",
    site: "https://typesense.org", docs: "https://typesense.org/docs/", repo: "https://github.com/typesense/typesense", oss: true, license: "GPL-3.0",
    deploy: ["self-hosted", "managed-cloud"], pricing: "freemium", free: true, maturity: "growing",
  }),
  t("algolia", "Algolia", {
    company: "Algolia", type: "service", cats: ["search"], caps: ["search-engine"],
    desc: "Hosted search-as-a-service with instant results, relevance tuning, AI ranking and prebuilt UI libraries.",
    site: "https://www.algolia.com", docs: "https://www.algolia.com/doc/", pricingUrl: "https://www.algolia.com/pricing/",
    deploy: ["managed-cloud"], pricing: "freemium", free: true, pricingSummary: "Free tier, then per-request pricing", compliance: ["SOC 2", "HIPAA", "GDPR"],
  }),
  t("clickhouse", "ClickHouse", {
    company: "ClickHouse", type: "database", cats: ["data-warehouses", "analytics"], caps: ["data-warehouse", "analytics"],
    desc: "Open-source column-oriented OLAP database for real-time analytics over billions of rows; ClickHouse Cloud is the managed offering.",
    site: "https://clickhouse.com", docs: "https://clickhouse.com/docs", repo: "https://github.com/ClickHouse/ClickHouse", pricingUrl: "https://clickhouse.com/pricing", oss: true, license: "Apache-2.0",
    deploy: ["self-hosted", "managed-cloud"], clouds: ["aws", "gcp", "azure"], pricing: "freemium", free: true, compliance: ["SOC 2", "HIPAA", "GDPR"], tags: ["olap", "real-time-analytics"],
  }),
  t("snowflake", "Snowflake", {
    company: "Snowflake", type: "service", cats: ["data-warehouses"], caps: ["data-warehouse"],
    desc: "Fully managed cloud data warehouse with separated storage and compute, data sharing and a large partner ecosystem.",
    site: "https://www.snowflake.com", docs: "https://docs.snowflake.com", pricingUrl: "https://www.snowflake.com/pricing/",
    deploy: ["managed-cloud"], clouds: ["aws", "gcp", "azure"], pricing: "usage-based", pricingSummary: "Credits per compute second plus storage", compliance: ["SOC 2", "HIPAA", "PCI DSS", "FedRAMP", "GDPR"], tags: ["enterprise"],
  }),
  t("bigquery", "Google BigQuery", {
    company: "Google", type: "service", cats: ["data-warehouses"], caps: ["data-warehouse"],
    desc: "Serverless data warehouse with pay-per-query pricing, built-in ML and streaming inserts.",
    site: "https://cloud.google.com/bigquery", docs: "https://cloud.google.com/bigquery/docs", pricingUrl: "https://cloud.google.com/bigquery/pricing",
    deploy: ["managed-cloud"], clouds: ["gcp"], pricing: "usage-based", free: true, pricingSummary: "Free monthly query and storage allowance, then per TB scanned", compliance: ["SOC 2", "HIPAA", "PCI DSS", "GDPR"], icon: "googlebigquery",
  }),
  t("databricks", "Databricks", {
    company: "Databricks", type: "platform", cats: ["data-warehouses", "data-lakes", "ml-platforms"], caps: ["data-warehouse", "etl", "ml-training"],
    desc: "Lakehouse platform combining Spark, Delta Lake, SQL warehousing, notebooks and ML tooling.",
    site: "https://www.databricks.com", docs: "https://docs.databricks.com", pricingUrl: "https://www.databricks.com/product/pricing",
    deploy: ["managed-cloud"], clouds: ["aws", "gcp", "azure"], pricing: "usage-based", compliance: ["SOC 2", "HIPAA", "PCI DSS", "FedRAMP", "GDPR"], tags: ["enterprise", "spark"],
  }),
  t("duckdb", "DuckDB", {
    company: "DuckDB Labs", type: "database", cats: ["data-warehouses", "analytics"], caps: ["data-warehouse", "analytics"],
    desc: "In-process analytical SQL database; queries Parquet, CSV and Postgres directly. Perfect for local analytics and embedded reporting.",
    site: "https://duckdb.org", docs: "https://duckdb.org/docs/", repo: "https://github.com/duckdb/duckdb", oss: true, license: "MIT",
    deploy: ["on-device", "self-hosted", "managed-cloud"], langs: ["python", "typescript", "rust", "go", "java"], free: true, tags: ["embedded", "olap"],
  }),
  t("motherduck", "MotherDuck", {
    company: "MotherDuck", type: "service", cats: ["data-warehouses"], caps: ["data-warehouse"],
    desc: "Serverless cloud data warehouse built on DuckDB with hybrid local/cloud query execution.",
    site: "https://motherduck.com", docs: "https://motherduck.com/docs/", pricingUrl: "https://motherduck.com/pricing/",
    deploy: ["managed-cloud"], integrations: ["duckdb"], pricing: "freemium", free: true, maturity: "emerging", icon: null,
  }),
  t("prisma", "Prisma", {
    company: "Prisma", type: "library", cats: ["orm"], caps: ["orm"],
    desc: "Type-safe ORM for Node.js and TypeScript with a schema DSL, migrations and Prisma Postgres managed database.",
    site: "https://www.prisma.io", docs: "https://www.prisma.io/docs", repo: "https://github.com/prisma/prisma", oss: true, license: "Apache-2.0",
    deploy: ["self-hosted", "serverless"], langs: ["typescript"], integrations: ["postgresql", "mysql", "sqlite", "mongodb", "nextjs"], free: true,
  }),
  t("drizzle", "Drizzle ORM", {
    company: "Drizzle Team", type: "library", cats: ["orm"], caps: ["orm"],
    desc: "Lightweight TypeScript ORM with SQL-like query builder, zero runtime dependencies and first-class serverless/edge support.",
    site: "https://orm.drizzle.team", docs: "https://orm.drizzle.team/docs/overview", repo: "https://github.com/drizzle-team/drizzle-orm", oss: true, license: "Apache-2.0",
    deploy: ["self-hosted", "serverless", "edge"], langs: ["typescript"], integrations: ["postgresql", "mysql", "sqlite", "neon", "turso", "nextjs"], free: true, maturity: "growing",
  }),
  t("sqlalchemy", "SQLAlchemy", {
    type: "library", cats: ["orm"], caps: ["orm"],
    desc: "The standard Python SQL toolkit and ORM, paired with Alembic for migrations.",
    site: "https://www.sqlalchemy.org", docs: "https://docs.sqlalchemy.org", repo: "https://github.com/sqlalchemy/sqlalchemy", oss: true, license: "MIT",
    deploy: ["self-hosted"], langs: ["python"], integrations: ["postgresql", "mysql", "sqlite", "fastapi"], free: true,
  }),
  t("mongoose", "Mongoose", {
    type: "library", cats: ["orm"], caps: ["orm"],
    desc: "Schema-based object modeling for MongoDB in Node.js.",
    site: "https://mongoosejs.com", docs: "https://mongoosejs.com/docs/", repo: "https://github.com/Automattic/mongoose", oss: true, license: "MIT",
    deploy: ["self-hosted"], langs: ["typescript", "javascript"], integrations: ["mongodb"], free: true,
  }),
  t("posthog", "PostHog", {
    company: "PostHog", type: "platform", cats: ["analytics", "feature-flags"], caps: ["analytics", "feature-flags"],
    desc: "Open-source product analytics with session replay, feature flags, experiments, surveys and a data warehouse in one platform. Generous free tier.",
    site: "https://posthog.com", docs: "https://posthog.com/docs", repo: "https://github.com/PostHog/posthog", pricingUrl: "https://posthog.com/pricing", oss: true, license: "MIT",
    deploy: ["managed-cloud", "self-hosted"], pricing: "freemium", free: true, pricingSummary: "Free monthly event allowance, then usage-based", compliance: ["SOC 2", "HIPAA", "GDPR"], tags: ["all-in-one"],
  }),
  t("mixpanel", "Mixpanel", {
    company: "Mixpanel", type: "service", cats: ["analytics"], caps: ["analytics"],
    desc: "Event-based product analytics with funnels, retention and cohort analysis.",
    site: "https://mixpanel.com", docs: "https://docs.mixpanel.com", pricingUrl: "https://mixpanel.com/pricing/",
    deploy: ["managed-cloud"], pricing: "freemium", free: true, compliance: ["SOC 2", "HIPAA", "GDPR"],
  }),
  t("amplitude", "Amplitude", {
    company: "Amplitude", type: "service", cats: ["analytics", "feature-flags"], caps: ["analytics", "feature-flags"],
    desc: "Enterprise product analytics and experimentation platform.",
    site: "https://amplitude.com", docs: "https://amplitude.com/docs", pricingUrl: "https://amplitude.com/pricing",
    deploy: ["managed-cloud"], pricing: "freemium", free: true, compliance: ["SOC 2", "HIPAA", "GDPR"], tags: ["enterprise"], icon: null,
  }),
  t("plausible", "Plausible Analytics", {
    company: "Plausible", type: "service", cats: ["analytics"], caps: ["analytics"],
    desc: "Lightweight, privacy-friendly, cookie-free web analytics; open-source and self-hostable.",
    site: "https://plausible.io", docs: "https://plausible.io/docs", repo: "https://github.com/plausible/analytics", pricingUrl: "https://plausible.io/#pricing", oss: true, license: "AGPL-3.0",
    deploy: ["managed-cloud", "self-hosted"], pricing: "subscription", free: false, pricingSummary: "Paid cloud plans; free to self-host", tags: ["privacy"], icon: "plausibleanalytics",
  }),
  t("segment", "Segment", {
    company: "Twilio", type: "service", cats: ["analytics", "data-engineering"], caps: ["analytics", "etl"],
    desc: "Customer data platform that collects events once and routes them to analytics, marketing and warehouse destinations.",
    site: "https://segment.com", docs: "https://segment.com/docs/", pricingUrl: "https://segment.com/pricing/",
    deploy: ["managed-cloud"], pricing: "freemium", free: true, compliance: ["SOC 2", "HIPAA", "GDPR"], icon: null,
  }),
  t("metabase", "Metabase", {
    company: "Metabase", type: "platform", cats: ["analytics"], caps: ["analytics", "bi"],
    desc: "Open-source BI and dashboards that connect directly to your database; easy self-hosting.",
    site: "https://www.metabase.com", docs: "https://www.metabase.com/docs/latest/", repo: "https://github.com/metabase/metabase", oss: true, license: "AGPL-3.0",
    deploy: ["self-hosted", "managed-cloud"], pricing: "freemium", free: true,
  }),
  t("neo4j", "Neo4j", {
    company: "Neo4j", type: "database", cats: ["nosql-databases", "databases"], caps: ["nosql-db", "graph-db"],
    desc: "The leading graph database with the Cypher query language and Aura managed cloud; also supports vector indexes for GraphRAG.",
    site: "https://neo4j.com", docs: "https://neo4j.com/docs/", repo: "https://github.com/neo4j/neo4j", pricingUrl: "https://neo4j.com/pricing/", oss: true, license: "GPL-3.0",
    deploy: ["self-hosted", "managed-cloud"], pricing: "freemium", free: true, tags: ["graph"],
  }),
  t("influxdb", "InfluxDB", {
    company: "InfluxData", type: "database", cats: ["databases", "nosql-databases"], caps: ["time-series-db", "nosql-db"],
    desc: "Purpose-built time series database for metrics, IoT and telemetry.",
    site: "https://www.influxdata.com", docs: "https://docs.influxdata.com", repo: "https://github.com/influxdata/influxdb", oss: true, license: "MIT",
    deploy: ["self-hosted", "managed-cloud"], pricing: "freemium", free: true, tags: ["time-series"],
  }),
  t("timescaledb", "TimescaleDB", {
    company: "Timescale", type: "database", cats: ["sql-databases", "databases"], caps: ["time-series-db", "relational-db"],
    desc: "Postgres extension for time series with hypertables, compression and continuous aggregates; also ships pgai vector tooling.",
    site: "https://www.timescale.com", docs: "https://docs.timescale.com", repo: "https://github.com/timescale/timescaledb", oss: true, license: "Apache-2.0",
    deploy: ["self-hosted", "managed-cloud"], integrations: ["postgresql"], pricing: "freemium", free: true, tags: ["time-series", "postgres"], icon: "timescale",
  }),
  t("cassandra", "Apache Cassandra", {
    company: "Apache Software Foundation", type: "database", cats: ["nosql-databases", "databases"], caps: ["nosql-db"],
    desc: "Wide-column distributed database for write-heavy, always-on workloads across regions.",
    site: "https://cassandra.apache.org", docs: "https://cassandra.apache.org/doc/latest/", repo: "https://github.com/apache/cassandra", oss: true, license: "Apache-2.0",
    deploy: ["self-hosted", "managed-cloud"], clouds: ["aws", "datastax"], free: true, tags: ["distributed"], icon: "apachecassandra",
  }),
  t("scylladb", "ScyllaDB", {
    company: "ScyllaDB", type: "database", cats: ["nosql-databases", "databases"], caps: ["nosql-db"],
    desc: "Cassandra- and DynamoDB-compatible NoSQL database rewritten in C++ for extreme throughput and low latency.",
    site: "https://www.scylladb.com", docs: "https://docs.scylladb.com", repo: "https://github.com/scylladb/scylladb", oss: true, license: "AGPL-3.0",
    deploy: ["self-hosted", "managed-cloud"], pricing: "freemium", free: true, tags: ["distributed", "high-throughput"], icon: null,
  }),
  t("surrealdb", "SurrealDB", {
    company: "SurrealDB", type: "database", cats: ["databases", "nosql-databases"], caps: ["nosql-db", "graph-db", "vector-db"],
    desc: "Multi-model database combining document, graph, vector and relational queries in one Rust engine.",
    site: "https://surrealdb.com", docs: "https://surrealdb.com/docs", repo: "https://github.com/surrealdb/surrealdb", oss: true, license: "BSL-1.1",
    deploy: ["self-hosted", "managed-cloud", "on-device"], free: true, maturity: "emerging", icon: null,
  }),
  t("couchbase", "Couchbase", {
    company: "Couchbase", type: "database", cats: ["nosql-databases", "databases"], caps: ["nosql-db", "cache", "vector-db"],
    desc: "Distributed document database with built-in caching, SQL++ queries and mobile sync via Couchbase Lite.",
    site: "https://www.couchbase.com", docs: "https://docs.couchbase.com", pricingUrl: "https://www.couchbase.com/pricing/",
    deploy: ["self-hosted", "managed-cloud"], pricing: "freemium", free: true, compliance: ["SOC 2", "HIPAA", "PCI DSS"], tags: ["enterprise"],
  }),
  t("electric-sql", "ElectricSQL", {
    company: "Electric DB", type: "platform", cats: ["realtime", "databases"], caps: ["realtime", "sqlite"],
    desc: "Postgres sync engine that streams partial replicas of your data into local-first web and mobile apps.",
    site: "https://electric-sql.com", docs: "https://electric-sql.com/docs/intro", repo: "https://github.com/electric-sql/electric", oss: true, license: "Apache-2.0",
    deploy: ["self-hosted", "managed-cloud"], integrations: ["postgresql"], free: true, maturity: "emerging", tags: ["local-first", "sync"], icon: null,
  }),
  t("powersync", "PowerSync", {
    company: "PowerSync", type: "service", cats: ["realtime", "databases"], caps: ["realtime", "sqlite"],
    desc: "Sync layer between Postgres/MongoDB/MySQL and local SQLite in mobile and web apps for offline-first products.",
    site: "https://www.powersync.com", docs: "https://docs.powersync.com", pricingUrl: "https://www.powersync.com/pricing",
    deploy: ["managed-cloud", "self-hosted"], integrations: ["postgresql", "mongodb", "sqlite"], pricing: "freemium", free: true, maturity: "emerging", tags: ["local-first", "offline"], icon: null,
  }),
];
