import { t } from "./helper";

export const FRONTEND = [
  t("nextjs", "Next.js", {
    company: "Vercel", type: "framework", cats: ["frontend-frameworks", "backend-frameworks"], caps: ["web-frontend", "api-backend", "static-hosting"],
    desc: "React meta-framework with server components, file-based routing, server actions, streaming and first-class Vercel deployment. The default choice for production React web apps.",
    site: "https://nextjs.org", docs: "https://nextjs.org/docs", repo: "https://github.com/vercel/next.js", oss: true, license: "MIT",
    deploy: ["managed-cloud", "self-hosted", "serverless", "edge"], clouds: ["vercel", "aws", "netlify", "cloudflare"], langs: ["typescript", "javascript"], frameworks: ["react"],
    integrations: ["react", "vercel", "tailwindcss", "prisma", "drizzle", "clerk", "auth-js", "supabase"], free: true, maturity: "established",
    tags: ["react", "ssr", "rsc", "fullstack"], useCases: ["SaaS web apps", "marketing sites", "dashboards", "AI apps"], icon: "nextdotjs",
  }),
  t("react", "React", {
    company: "Meta", type: "library", cats: ["frontend-frameworks"], caps: ["web-frontend"],
    desc: "Component-based UI library with the largest ecosystem of any frontend technology. Pairs with a meta-framework for routing and data.",
    site: "https://react.dev", docs: "https://react.dev/learn", repo: "https://github.com/facebook/react", oss: true, license: "MIT",
    deploy: ["self-hosted", "managed-cloud", "edge"], langs: ["typescript", "javascript"], integrations: ["nextjs", "remix", "vite", "react-native"], free: true,
    tags: ["ui", "spa", "components"], useCases: ["interactive web UIs"],
  }),
  t("vue", "Vue.js", {
    type: "framework", cats: ["frontend-frameworks"], caps: ["web-frontend"],
    desc: "Progressive JavaScript framework with an approachable template syntax, strong tooling and the Nuxt meta-framework.",
    site: "https://vuejs.org", docs: "https://vuejs.org/guide/", repo: "https://github.com/vuejs/core", oss: true, license: "MIT",
    deploy: ["self-hosted", "managed-cloud"], langs: ["typescript", "javascript"], integrations: ["nuxt", "vite"], free: true, tags: ["ui", "spa"], icon: "vuedotjs",
  }),
  t("nuxt", "Nuxt", {
    company: "NuxtLabs", type: "framework", cats: ["frontend-frameworks", "backend-frameworks"], caps: ["web-frontend", "api-backend"],
    desc: "Vue meta-framework with SSR, file routing, server routes and hybrid rendering. The Vue equivalent of Next.js.",
    site: "https://nuxt.com", docs: "https://nuxt.com/docs", repo: "https://github.com/nuxt/nuxt", oss: true, license: "MIT",
    deploy: ["managed-cloud", "self-hosted", "serverless", "edge"], clouds: ["vercel", "netlify", "cloudflare"], langs: ["typescript", "javascript"], frameworks: ["vue"], integrations: ["vue", "vercel"], free: true,
  }),
  t("sveltekit", "SvelteKit", {
    type: "framework", cats: ["frontend-frameworks", "backend-frameworks"], caps: ["web-frontend", "api-backend"],
    desc: "Svelte's application framework: compiled components, minimal runtime, file routing, server load functions and adapters for most hosts.",
    site: "https://svelte.dev", docs: "https://svelte.dev/docs/kit", repo: "https://github.com/sveltejs/kit", oss: true, license: "MIT",
    deploy: ["managed-cloud", "self-hosted", "serverless", "edge"], clouds: ["vercel", "netlify", "cloudflare"], langs: ["typescript", "javascript"], frameworks: ["svelte"], free: true, icon: "svelte",
  }),
  t("svelte", "Svelte", {
    type: "framework", cats: ["frontend-frameworks"], caps: ["web-frontend"],
    desc: "Compiler-based UI framework that ships very small bundles with reactive components and no virtual DOM.",
    site: "https://svelte.dev", docs: "https://svelte.dev/docs", repo: "https://github.com/sveltejs/svelte", oss: true, license: "MIT",
    deploy: ["self-hosted", "managed-cloud"], langs: ["typescript", "javascript"], integrations: ["sveltekit", "vite"], free: true,
  }),
  t("angular", "Angular", {
    company: "Google", type: "framework", cats: ["frontend-frameworks"], caps: ["web-frontend"],
    desc: "Batteries-included TypeScript web framework with dependency injection, a router, forms and RxJS. Common in large enterprise teams.",
    site: "https://angular.dev", docs: "https://angular.dev/overview", repo: "https://github.com/angular/angular", oss: true, license: "MIT",
    deploy: ["self-hosted", "managed-cloud"], langs: ["typescript"], free: true, tags: ["enterprise"],
  }),
  t("remix", "React Router (Remix)", {
    company: "Shopify", type: "framework", cats: ["frontend-frameworks", "backend-frameworks"], caps: ["web-frontend", "api-backend"],
    desc: "Full-stack React framework built on web standards with nested routing, loaders and actions. Remix has merged into React Router v7 framework mode.",
    site: "https://reactrouter.com", docs: "https://reactrouter.com/home", repo: "https://github.com/remix-run/react-router", oss: true, license: "MIT",
    deploy: ["managed-cloud", "self-hosted", "edge"], clouds: ["vercel", "cloudflare", "fly-io"], langs: ["typescript", "javascript"], frameworks: ["react"], free: true, aliases: ["Remix", "React Router"], icon: "reactrouter",
  }),
  t("astro", "Astro", {
    type: "framework", cats: ["frontend-frameworks"], caps: ["web-frontend", "static-hosting"],
    desc: "Content-focused web framework that ships zero JavaScript by default with islands of interactivity from any UI framework.",
    site: "https://astro.build", docs: "https://docs.astro.build", repo: "https://github.com/withastro/astro", oss: true, license: "MIT",
    deploy: ["managed-cloud", "self-hosted", "edge"], clouds: ["vercel", "netlify", "cloudflare"], langs: ["typescript", "javascript"], free: true, tags: ["content", "static"], useCases: ["marketing sites", "blogs", "docs"],
  }),
  t("solidjs", "SolidJS", {
    type: "framework", cats: ["frontend-frameworks"], caps: ["web-frontend"],
    desc: "Fine-grained reactive UI framework with JSX and no virtual DOM, delivering top-tier runtime performance.",
    site: "https://www.solidjs.com", docs: "https://docs.solidjs.com", repo: "https://github.com/solidjs/solid", oss: true, license: "MIT",
    deploy: ["self-hosted", "managed-cloud"], langs: ["typescript", "javascript"], free: true, maturity: "growing", icon: "solid",
  }),
  t("qwik", "Qwik", {
    company: "Builder.io", type: "framework", cats: ["frontend-frameworks"], caps: ["web-frontend"],
    desc: "Resumable web framework that avoids hydration cost entirely, aimed at instant-loading large sites.",
    site: "https://qwik.dev", docs: "https://qwik.dev/docs/", repo: "https://github.com/QwikDev/qwik", oss: true, license: "MIT",
    deploy: ["managed-cloud", "edge", "self-hosted"], langs: ["typescript"], free: true, maturity: "emerging",
  }),
  t("htmx", "htmx", {
    type: "library", cats: ["frontend-frameworks"], caps: ["web-frontend"],
    desc: "Hypermedia-driven frontend library that gives HTML attributes for AJAX, websockets and partial page updates without a JavaScript framework.",
    site: "https://htmx.org", docs: "https://htmx.org/docs/", repo: "https://github.com/bigskysoftware/htmx", oss: true, license: "0BSD",
    deploy: ["self-hosted"], langs: ["javascript"], free: true, tags: ["hypermedia", "server-rendered"], maturity: "growing",
  }),
  t("vite", "Vite", {
    company: "VoidZero", type: "tool", cats: ["developer-tools", "frontend-frameworks"], caps: ["web-frontend"],
    desc: "Fast frontend build tool and dev server used by most modern SPA and framework toolchains.",
    site: "https://vite.dev", docs: "https://vite.dev/guide/", repo: "https://github.com/vitejs/vite", oss: true, license: "MIT",
    deploy: ["self-hosted"], langs: ["typescript", "javascript"], free: true,
  }),
  t("tailwindcss", "Tailwind CSS", {
    company: "Tailwind Labs", type: "library", cats: ["frontend-frameworks", "developer-tools"], caps: ["web-frontend"],
    desc: "Utility-first CSS framework for building custom interfaces quickly with design tokens in class names.",
    site: "https://tailwindcss.com", docs: "https://tailwindcss.com/docs", repo: "https://github.com/tailwindlabs/tailwindcss", oss: true, license: "MIT",
    deploy: ["self-hosted"], langs: ["css", "typescript", "javascript"], free: true, tags: ["css", "styling"],
  }),
  t("shadcn-ui", "shadcn/ui", {
    type: "library", cats: ["frontend-frameworks"], caps: ["web-frontend"],
    desc: "Copy-and-own React component collection built on Radix primitives and Tailwind CSS.",
    site: "https://ui.shadcn.com", docs: "https://ui.shadcn.com/docs", repo: "https://github.com/shadcn-ui/ui", oss: true, license: "MIT",
    deploy: ["self-hosted"], langs: ["typescript"], frameworks: ["react", "nextjs"], integrations: ["tailwindcss", "react", "nextjs"], free: true, maturity: "growing", icon: "shadcnui",
  }),
  t("react-native", "React Native", {
    company: "Meta", type: "framework", cats: ["mobile"], caps: ["cross-platform-mobile", "ios-client", "android-client"],
    desc: "Build native iOS and Android apps from one React codebase, usually with Expo for tooling and builds.",
    site: "https://reactnative.dev", docs: "https://reactnative.dev/docs/getting-started", repo: "https://github.com/facebook/react-native", oss: true, license: "MIT",
    deploy: ["on-device"], langs: ["typescript", "javascript"], frameworks: ["react"], integrations: ["expo", "react"], free: true, icon: "react",
  }),
  t("expo", "Expo", {
    company: "Expo", type: "platform", cats: ["mobile"], caps: ["cross-platform-mobile", "ios-client", "android-client"],
    desc: "Framework and cloud services for React Native: file routing, native modules, over-the-air updates and EAS build/submit pipelines.",
    site: "https://expo.dev", docs: "https://docs.expo.dev", repo: "https://github.com/expo/expo", pricingUrl: "https://expo.dev/pricing", oss: true, license: "MIT",
    deploy: ["on-device", "managed-cloud"], langs: ["typescript", "javascript"], frameworks: ["react-native"], integrations: ["react-native"], pricing: "freemium", free: true, pricingSummary: "Open-source framework; EAS cloud builds have a free tier and paid plans",
  }),
  t("flutter", "Flutter", {
    company: "Google", type: "framework", cats: ["mobile", "desktop"], caps: ["cross-platform-mobile", "ios-client", "android-client", "desktop-client"],
    desc: "Dart-based UI toolkit compiling to native iOS, Android, web and desktop with a single rendering engine.",
    site: "https://flutter.dev", docs: "https://docs.flutter.dev", repo: "https://github.com/flutter/flutter", oss: true, license: "BSD-3-Clause",
    deploy: ["on-device", "desktop"], langs: ["dart"], free: true,
  }),
  t("swift", "Swift / SwiftUI", {
    company: "Apple", type: "language", cats: ["mobile", "languages"], caps: ["ios-client", "language"],
    desc: "Apple's language and declarative UI framework for native iOS, iPadOS, macOS, watchOS and visionOS apps with the best platform fidelity.",
    site: "https://developer.apple.com/swift/", docs: "https://developer.apple.com/documentation/swiftui", repo: "https://github.com/swiftlang/swift", oss: true, license: "Apache-2.0",
    deploy: ["on-device"], langs: ["swift"], free: true, aliases: ["SwiftUI", "iOS native"],
  }),
  t("kotlin", "Kotlin / Jetpack Compose", {
    company: "JetBrains", type: "language", cats: ["mobile", "languages"], caps: ["android-client", "language"],
    desc: "The primary language for native Android with Jetpack Compose for declarative UI; also used server-side on the JVM.",
    site: "https://kotlinlang.org", docs: "https://developer.android.com/compose", repo: "https://github.com/JetBrains/kotlin", oss: true, license: "Apache-2.0",
    deploy: ["on-device", "self-hosted"], langs: ["kotlin"], free: true, aliases: ["Jetpack Compose", "Android native"],
  }),
  t("electron", "Electron", {
    company: "OpenJS Foundation", type: "framework", cats: ["desktop"], caps: ["desktop-client"],
    desc: "Build cross-platform desktop apps with web technologies and Node.js. Mature and widely used, at the cost of bundle size.",
    site: "https://www.electronjs.org", docs: "https://www.electronjs.org/docs/latest", repo: "https://github.com/electron/electron", oss: true, license: "MIT",
    deploy: ["desktop"], langs: ["typescript", "javascript"], free: true,
  }),
  t("tauri", "Tauri", {
    type: "framework", cats: ["desktop", "mobile"], caps: ["desktop-client"],
    desc: "Lightweight desktop and mobile app framework using the system webview with a Rust backend; much smaller binaries than Electron.",
    site: "https://tauri.app", docs: "https://tauri.app/start/", repo: "https://github.com/tauri-apps/tauri", oss: true, license: "MIT",
    deploy: ["desktop", "on-device"], langs: ["rust", "typescript"], free: true, maturity: "growing",
  }),
  t("capacitor", "Capacitor", {
    company: "Ionic", type: "framework", cats: ["mobile"], caps: ["cross-platform-mobile", "ios-client", "android-client"],
    desc: "Wrap a web app as a native iOS and Android app with access to native APIs. Fits teams that already have a web frontend.",
    site: "https://capacitorjs.com", docs: "https://capacitorjs.com/docs", repo: "https://github.com/ionic-team/capacitor", oss: true, license: "MIT",
    deploy: ["on-device"], langs: ["typescript", "javascript"], free: true, maturity: "established",
  }),
  t("sanity", "Sanity", {
    company: "Sanity", type: "service", cats: ["cms"], caps: ["cms"],
    desc: "Headless CMS with a real-time content lake, customizable studio and GROQ query language.",
    site: "https://www.sanity.io", docs: "https://www.sanity.io/docs", pricingUrl: "https://www.sanity.io/pricing", repo: "https://github.com/sanity-io/sanity", oss: true, license: "MIT",
    deploy: ["managed-cloud"], langs: ["typescript", "javascript"], integrations: ["nextjs", "react"], pricing: "freemium", free: true, pricingSummary: "Free tier, then usage-based plans", compliance: ["SOC 2", "GDPR"],
  }),
  t("contentful", "Contentful", {
    company: "Contentful", type: "service", cats: ["cms"], caps: ["cms"],
    desc: "Enterprise headless CMS with structured content modeling, localization and a large integration marketplace.",
    site: "https://www.contentful.com", docs: "https://www.contentful.com/developers/docs/", pricingUrl: "https://www.contentful.com/pricing/",
    deploy: ["managed-cloud"], pricing: "freemium", free: true, pricingSummary: "Free tier; paid plans scale by usage and seats", compliance: ["SOC 2", "GDPR", "ISO 27001"], tags: ["enterprise"],
  }),
  t("strapi", "Strapi", {
    company: "Strapi", type: "framework", cats: ["cms", "backend-frameworks"], caps: ["cms"],
    desc: "Open-source Node.js headless CMS you can self-host, with a cloud option.",
    site: "https://strapi.io", docs: "https://docs.strapi.io", repo: "https://github.com/strapi/strapi", pricingUrl: "https://strapi.io/pricing-cloud", oss: true, license: "MIT",
    deploy: ["self-hosted", "managed-cloud"], langs: ["typescript", "javascript"], pricing: "freemium", free: true, pricingSummary: "Free to self-host; Strapi Cloud paid plans",
  }),
  t("payload", "Payload", {
    company: "Figma", type: "framework", cats: ["cms", "backend-frameworks"], caps: ["cms"],
    desc: "TypeScript-native headless CMS and application framework that installs directly into a Next.js app.",
    site: "https://payloadcms.com", docs: "https://payloadcms.com/docs", repo: "https://github.com/payloadcms/payload", oss: true, license: "MIT",
    deploy: ["self-hosted", "managed-cloud"], langs: ["typescript"], frameworks: ["nextjs"], integrations: ["nextjs", "postgresql", "mongodb"], free: true, maturity: "growing", icon: "payloadcms",
  }),
  t("storyblok", "Storyblok", {
    company: "Storyblok", type: "service", cats: ["cms"], caps: ["cms"],
    desc: "Headless CMS with a visual editor for marketers and a component-based content model.",
    site: "https://www.storyblok.com", docs: "https://www.storyblok.com/docs", pricingUrl: "https://www.storyblok.com/pricing",
    deploy: ["managed-cloud"], pricing: "freemium", free: true, pricingSummary: "Free tier and paid plans", compliance: ["SOC 2", "GDPR", "ISO 27001"],
  }),
  t("wordpress", "WordPress", {
    company: "Automattic", type: "platform", cats: ["cms"], caps: ["cms"],
    desc: "The most widely deployed CMS; usable headless via its REST/GraphQL APIs or as a full site platform.",
    site: "https://wordpress.org", docs: "https://developer.wordpress.org", repo: "https://github.com/WordPress/WordPress", oss: true, license: "GPL-2.0",
    deploy: ["self-hosted", "managed-cloud"], langs: ["php"], free: true, tags: ["php"],
  }),
  t("mapbox", "Mapbox", {
    company: "Mapbox", type: "api", cats: ["maps"], caps: ["maps"],
    desc: "Maps SDKs, geocoding, navigation and geospatial APIs with highly customizable map styling.",
    site: "https://www.mapbox.com", docs: "https://docs.mapbox.com", pricingUrl: "https://www.mapbox.com/pricing",
    deploy: ["managed-cloud"], langs: ["typescript", "javascript", "swift", "kotlin"], pricing: "usage-based", free: true, pricingSummary: "Free monthly usage, then pay per request",
  }),
  t("google-maps-platform", "Google Maps Platform", {
    company: "Google", type: "api", cats: ["maps"], caps: ["maps"],
    desc: "Maps, Places, Routes and geocoding APIs with the widest place data coverage.",
    site: "https://mapsplatform.google.com", docs: "https://developers.google.com/maps/documentation", pricingUrl: "https://mapsplatform.google.com/pricing/",
    deploy: ["managed-cloud"], pricing: "usage-based", free: true, pricingSummary: "Monthly free usage credit, then pay per request", icon: "googlemaps",
  }),
  t("maplibre", "MapLibre", {
    type: "library", cats: ["maps"], caps: ["maps"],
    desc: "Open-source map rendering libraries for web and mobile, a community fork of Mapbox GL.",
    site: "https://maplibre.org", docs: "https://maplibre.org/maplibre-gl-js/docs/", repo: "https://github.com/maplibre/maplibre-gl-js", oss: true, license: "BSD-3-Clause",
    deploy: ["self-hosted"], langs: ["typescript", "javascript"], free: true, maturity: "growing",
  }),
];
