import { t } from "./helper";

export const INFRA = [
  t("vercel", "Vercel", {
    company: "Vercel", type: "platform", cats: ["hosting", "serverless", "cdn-edge"], caps: ["hosting", "cdn", "serverless-functions", "static-hosting", "scheduler"],
    desc: "Frontend cloud with zero-config deployments for Next.js and other frameworks, preview deployments, edge network, Fluid Compute functions and cron. Fastest path to production for web apps.",
    site: "https://vercel.com", docs: "https://vercel.com/docs", pricingUrl: "https://vercel.com/pricing",
    deploy: ["managed-cloud", "serverless", "edge"], clouds: ["vercel"], frameworks: ["nextjs", "nuxt", "sveltekit", "astro", "remix"], integrations: ["nextjs", "github", "neon", "upstash", "vercel-blob"], pricing: "freemium", free: true, pricingSummary: "Hobby free; Pro per seat plus usage", compliance: ["SOC 2", "GDPR", "HIPAA", "ISO 27001"], tags: ["frontend-cloud", "preview-deployments"],
  }),
  t("netlify", "Netlify", {
    company: "Netlify", type: "platform", cats: ["hosting", "serverless", "cdn-edge"], caps: ["hosting", "cdn", "serverless-functions", "static-hosting"],
    desc: "Web hosting platform with git-based deploys, functions, edge functions and forms; strong for static and Jamstack sites.",
    site: "https://www.netlify.com", docs: "https://docs.netlify.com", pricingUrl: "https://www.netlify.com/pricing/",
    deploy: ["managed-cloud", "serverless", "edge"], pricing: "freemium", free: true, compliance: ["SOC 2", "GDPR"],
  }),
  t("cloudflare-workers", "Cloudflare Workers", {
    company: "Cloudflare", type: "platform", cats: ["serverless", "cdn-edge", "hosting"], caps: ["hosting", "edge-functions", "serverless-functions", "cdn", "scheduler", "queue", "static-hosting"],
    desc: "Serverless functions on Cloudflare's global edge with Workers KV, Durable Objects, D1 SQLite, Queues, R2 and Workers AI. Very low cost per request and no cold starts.",
    site: "https://workers.cloudflare.com", docs: "https://developers.cloudflare.com/workers/", pricingUrl: "https://developers.cloudflare.com/workers/platform/pricing/",
    deploy: ["edge", "serverless"], clouds: ["cloudflare"], langs: ["typescript", "javascript", "rust", "python"], integrations: ["hono", "cloudflare-r2", "cloudflare"], pricing: "freemium", free: true, pricingSummary: "Free tier of daily requests, then per-million requests", compliance: ["SOC 2", "GDPR", "ISO 27001", "PCI DSS"], aliases: ["Workers", "Cloudflare Pages"], tags: ["edge", "serverless", "cheap"], icon: "cloudflareworkers",
  }),
  t("cloudflare", "Cloudflare", {
    company: "Cloudflare", type: "platform", cats: ["cdn-edge", "dns", "security", "networking"], caps: ["cdn", "dns", "ddos-protection", "waf"],
    desc: "Global CDN, DNS, DDoS protection, WAF and zero-trust networking in front of any origin. Free tier covers most products.",
    site: "https://www.cloudflare.com", docs: "https://developers.cloudflare.com", pricingUrl: "https://www.cloudflare.com/plans/",
    deploy: ["managed-cloud", "edge"], clouds: ["cloudflare"], pricing: "freemium", free: true, compliance: ["SOC 2", "GDPR", "ISO 27001", "PCI DSS"], tags: ["cdn", "dns", "security"],
  }),
  t("aws", "Amazon Web Services", {
    company: "Amazon", type: "platform", cats: ["cloud-platforms", "compute", "serverless", "kubernetes", "storage"], caps: ["hosting", "vm-compute", "serverless-functions", "container-orchestration", "gpu-compute", "cdn", "secrets"],
    desc: "The largest cloud: EC2, Lambda, ECS/EKS, S3, RDS, SageMaker and hundreds of services with the broadest compliance coverage and region footprint.",
    site: "https://aws.amazon.com", docs: "https://docs.aws.amazon.com", pricingUrl: "https://aws.amazon.com/pricing/",
    deploy: ["managed-cloud", "serverless"], clouds: ["aws"], pricing: "usage-based", free: true, pricingSummary: "Pay as you go with a free tier", compliance: ["HIPAA", "SOC 2", "PCI DSS", "FedRAMP", "GDPR", "ISO 27001", "HITRUST"], regions: ["us", "eu", "apac", "sa", "me", "af"], aliases: ["AWS", "Amazon EC2", "AWS Lambda", "Amazon ECS", "Amazon EKS"], tags: ["hyperscaler"], icon: "amazonwebservices",
  }),
  t("google-cloud", "Google Cloud Platform", {
    company: "Google", type: "platform", cats: ["cloud-platforms", "compute", "serverless", "kubernetes"], caps: ["hosting", "vm-compute", "serverless-functions", "container-orchestration", "gpu-compute", "cdn", "secrets"],
    desc: "Google's cloud with Cloud Run, GKE (the most mature managed Kubernetes), BigQuery, Vertex AI and strong data/AI services.",
    site: "https://cloud.google.com", docs: "https://cloud.google.com/docs", pricingUrl: "https://cloud.google.com/pricing",
    deploy: ["managed-cloud", "serverless"], clouds: ["gcp"], pricing: "usage-based", free: true, compliance: ["HIPAA", "SOC 2", "PCI DSS", "FedRAMP", "GDPR", "ISO 27001"], regions: ["us", "eu", "apac", "sa", "me"], aliases: ["GCP", "Cloud Run", "GKE"], tags: ["hyperscaler"], icon: "googlecloud",
  }),
  t("azure", "Microsoft Azure", {
    company: "Microsoft", type: "platform", cats: ["cloud-platforms", "compute", "serverless", "kubernetes"], caps: ["hosting", "vm-compute", "serverless-functions", "container-orchestration", "gpu-compute", "cdn", "secrets"],
    desc: "Microsoft's cloud with AKS, Functions, Container Apps, Azure OpenAI and deep integration with Microsoft 365 and Entra ID; preferred in enterprises standardized on Microsoft.",
    site: "https://azure.microsoft.com", docs: "https://learn.microsoft.com/azure/", pricingUrl: "https://azure.microsoft.com/pricing/",
    deploy: ["managed-cloud", "serverless"], clouds: ["azure"], pricing: "usage-based", free: true, compliance: ["HIPAA", "SOC 2", "PCI DSS", "FedRAMP", "GDPR", "ISO 27001"], regions: ["us", "eu", "apac", "sa", "me", "af"], aliases: ["Azure", "AKS"], tags: ["hyperscaler", "enterprise"], icon: null,
  }),
  t("railway", "Railway", {
    company: "Railway", type: "platform", cats: ["hosting"], caps: ["hosting", "relational-db", "cache", "scheduler"],
    desc: "Deploy any service, database or Docker image from a Git repo with a visual project canvas and usage-based pricing. Excellent for small teams that want a backend host without Kubernetes.",
    site: "https://railway.com", docs: "https://docs.railway.com", pricingUrl: "https://railway.com/pricing",
    deploy: ["managed-cloud"], integrations: ["postgresql", "redis", "github"], pricing: "usage-based", free: true, pricingSummary: "Trial credit, then usage-based with a small monthly minimum", compliance: ["SOC 2"], maturity: "growing", tags: ["paas", "simple"],
  }),
  t("render", "Render", {
    company: "Render", type: "platform", cats: ["hosting"], caps: ["hosting", "relational-db", "cache", "scheduler", "workers"],
    desc: "Heroku-style platform with web services, background workers, cron jobs, managed Postgres and Redis; predictable pricing.",
    site: "https://render.com", docs: "https://render.com/docs", pricingUrl: "https://render.com/pricing",
    deploy: ["managed-cloud"], integrations: ["postgresql", "redis", "github"], pricing: "freemium", free: true, compliance: ["SOC 2", "HIPAA", "GDPR"], tags: ["paas"],
  }),
  t("fly-io", "Fly.io", {
    company: "Fly.io", type: "platform", cats: ["hosting", "compute"], caps: ["hosting", "vm-compute", "gpu-compute"],
    desc: "Run Docker containers as Firecracker microVMs close to users in 30+ regions, with GPUs and machine-level APIs; good for latency-sensitive and multi-region apps.",
    site: "https://fly.io", docs: "https://fly.io/docs/", pricingUrl: "https://fly.io/pricing/",
    deploy: ["managed-cloud"], pricing: "usage-based", free: false, pricingSummary: "Pay as you go, billed per machine", compliance: ["SOC 2"], tags: ["multi-region", "containers"], icon: "flydotio",
  }),
  t("heroku", "Heroku", {
    company: "Salesforce", type: "platform", cats: ["hosting"], caps: ["hosting", "relational-db", "workers", "scheduler"],
    desc: "The original PaaS with buildpacks, add-ons and dynos; simple but pricier than newer alternatives.",
    site: "https://www.heroku.com", docs: "https://devcenter.heroku.com", pricingUrl: "https://www.heroku.com/pricing",
    deploy: ["managed-cloud"], pricing: "subscription", free: false, compliance: ["SOC 2", "HIPAA", "PCI DSS"], maturity: "legacy",
  }),
  t("digitalocean", "DigitalOcean", {
    company: "DigitalOcean", type: "platform", cats: ["cloud-platforms", "compute", "hosting", "kubernetes"], caps: ["hosting", "vm-compute", "container-orchestration", "relational-db", "object-storage", "gpu-compute"],
    desc: "Developer-friendly cloud with simple VMs (Droplets), App Platform, managed databases, Kubernetes and Gradient AI GPU compute at predictable prices.",
    site: "https://www.digitalocean.com", docs: "https://docs.digitalocean.com", pricingUrl: "https://www.digitalocean.com/pricing",
    deploy: ["managed-cloud"], clouds: ["digitalocean"], pricing: "usage-based", free: false, compliance: ["SOC 2", "PCI DSS", "GDPR"], tags: ["simple-cloud", "predictable-pricing"],
  }),
  t("hetzner", "Hetzner", {
    company: "Hetzner", type: "platform", cats: ["cloud-platforms", "compute"], caps: ["hosting", "vm-compute", "bare-metal", "object-storage"],
    desc: "European provider with extremely cheap cloud VMs and dedicated servers; the go-to for cost-optimized self-hosting.",
    site: "https://www.hetzner.com", docs: "https://docs.hetzner.com", pricingUrl: "https://www.hetzner.com/cloud/",
    deploy: ["managed-cloud", "self-hosted"], clouds: ["hetzner"], pricing: "usage-based", regions: ["eu", "us", "apac"], compliance: ["ISO 27001", "GDPR"], tags: ["cheap", "eu", "bare-metal"],
  }),
  t("coolify", "Coolify", {
    company: "Coolify", type: "platform", cats: ["hosting"], caps: ["hosting"],
    desc: "Open-source self-hostable Heroku/Vercel alternative: deploy apps, databases and services to your own servers with Git integration.",
    site: "https://coolify.io", docs: "https://coolify.io/docs", repo: "https://github.com/coollabsio/coolify", oss: true, license: "Apache-2.0",
    deploy: ["self-hosted", "managed-cloud"], integrations: ["hetzner", "github", "docker"], pricing: "freemium", free: true, maturity: "growing", tags: ["self-hosted", "paas"], icon: null,
  }),
  t("docker", "Docker", {
    company: "Docker", type: "tool", cats: ["containers"], caps: ["container-registry"],
    desc: "Standard container build and runtime tooling; Docker Compose for local multi-service development.",
    site: "https://www.docker.com", docs: "https://docs.docker.com", repo: "https://github.com/moby/moby", oss: true, license: "Apache-2.0",
    deploy: ["self-hosted", "desktop"], pricing: "freemium", free: true,
  }),
  t("kubernetes", "Kubernetes", {
    company: "CNCF", type: "platform", cats: ["kubernetes", "containers"], caps: ["container-orchestration"],
    desc: "The industry-standard container orchestrator; run managed (EKS, GKE, AKS) or self-managed. Powerful but operationally heavy for small teams.",
    site: "https://kubernetes.io", docs: "https://kubernetes.io/docs/", repo: "https://github.com/kubernetes/kubernetes", oss: true, license: "Apache-2.0",
    deploy: ["self-hosted", "managed-cloud"], clouds: ["aws", "gcp", "azure", "digitalocean"], free: true, tags: ["orchestration", "complex"],
  }),
  t("terraform", "Terraform", {
    company: "HashiCorp (IBM)", type: "tool", cats: ["infrastructure-as-code"], caps: ["infrastructure-as-code"],
    desc: "Declarative infrastructure as code with providers for every cloud and SaaS; HCP Terraform for state and runs.",
    site: "https://www.terraform.io", docs: "https://developer.hashicorp.com/terraform/docs", repo: "https://github.com/hashicorp/terraform", pricingUrl: "https://www.hashicorp.com/products/terraform/pricing", oss: false, license: "BSL-1.1",
    deploy: ["self-hosted", "managed-cloud"], pricing: "freemium", free: true, compliance: ["SOC 2"],
  }),
  t("opentofu", "OpenTofu", {
    company: "Linux Foundation", type: "tool", cats: ["infrastructure-as-code"], caps: ["infrastructure-as-code"],
    desc: "Open-source, community-driven fork of Terraform under the MPL license.",
    site: "https://opentofu.org", docs: "https://opentofu.org/docs/", repo: "https://github.com/opentofu/opentofu", oss: true, license: "MPL-2.0",
    deploy: ["self-hosted"], free: true, maturity: "growing",
  }),
  t("pulumi", "Pulumi", {
    company: "Pulumi", type: "tool", cats: ["infrastructure-as-code"], caps: ["infrastructure-as-code", "secrets"],
    desc: "Infrastructure as code in real programming languages (TypeScript, Python, Go) with Pulumi Cloud for state and ESC secrets.",
    site: "https://www.pulumi.com", docs: "https://www.pulumi.com/docs/", repo: "https://github.com/pulumi/pulumi", pricingUrl: "https://www.pulumi.com/pricing/", oss: true, license: "Apache-2.0",
    deploy: ["self-hosted", "managed-cloud"], langs: ["typescript", "python", "go", "csharp"], pricing: "freemium", free: true,
  }),
  t("sst", "SST", {
    company: "SST", type: "framework", cats: ["infrastructure-as-code"], caps: ["infrastructure-as-code"],
    desc: "Infrastructure as code for full-stack apps on AWS and Cloudflare with typed resource linking and live local development.",
    site: "https://sst.dev", docs: "https://sst.dev/docs/", repo: "https://github.com/sst/sst", oss: true, license: "MIT",
    deploy: ["managed-cloud", "serverless"], clouds: ["aws", "cloudflare"], langs: ["typescript"], integrations: ["aws", "nextjs", "pulumi"], free: true, maturity: "growing", icon: null,
  }),
  t("aws-cdk", "AWS CDK", {
    company: "Amazon", type: "library", cats: ["infrastructure-as-code"], caps: ["infrastructure-as-code"],
    desc: "Define AWS infrastructure in TypeScript, Python or Java and synthesize CloudFormation.",
    site: "https://aws.amazon.com/cdk/", docs: "https://docs.aws.amazon.com/cdk/", repo: "https://github.com/aws/aws-cdk", oss: true, license: "Apache-2.0",
    deploy: ["managed-cloud"], clouds: ["aws"], langs: ["typescript", "python", "java", "go", "csharp"], free: true, icon: "amazonwebservices",
  }),
  t("github", "GitHub", {
    company: "Microsoft", type: "platform", cats: ["source-control", "ci-cd"], caps: ["ci-cd", "source-control"],
    desc: "Git hosting with pull requests, GitHub Actions CI/CD, Packages, Codespaces and Copilot. The default for nearly every team.",
    site: "https://github.com", docs: "https://docs.github.com", pricingUrl: "https://github.com/pricing",
    deploy: ["managed-cloud", "self-hosted"], pricing: "freemium", free: true, pricingSummary: "Free for public and private repos with Actions minutes; paid seats for teams", compliance: ["SOC 2", "GDPR", "ISO 27001"], aliases: ["GitHub Actions"], tags: ["git", "ci"],
  }),
  t("gitlab", "GitLab", {
    company: "GitLab", type: "platform", cats: ["source-control", "ci-cd"], caps: ["ci-cd", "source-control"],
    desc: "Complete DevSecOps platform with Git hosting, CI/CD, security scanning and self-hosting options popular in regulated enterprises.",
    site: "https://about.gitlab.com", docs: "https://docs.gitlab.com", repo: "https://gitlab.com/gitlab-org/gitlab", pricingUrl: "https://about.gitlab.com/pricing/", oss: true, license: "MIT",
    deploy: ["managed-cloud", "self-hosted"], pricing: "freemium", free: true, compliance: ["SOC 2", "GDPR", "ISO 27001", "FedRAMP"], tags: ["enterprise", "self-hosted"],
  }),
  t("circleci", "CircleCI", {
    company: "CircleCI", type: "service", cats: ["ci-cd"], caps: ["ci-cd"],
    desc: "Hosted CI/CD with fast parallelism and Docker-based executors.",
    site: "https://circleci.com", docs: "https://circleci.com/docs/", pricingUrl: "https://circleci.com/pricing/",
    deploy: ["managed-cloud", "self-hosted"], pricing: "freemium", free: true, compliance: ["SOC 2", "FedRAMP"],
  }),
  t("buildkite", "Buildkite", {
    company: "Buildkite", type: "service", cats: ["ci-cd"], caps: ["ci-cd"],
    desc: "CI/CD platform with self-hosted agents and a hosted control plane, favored by large engineering orgs.",
    site: "https://buildkite.com", docs: "https://buildkite.com/docs", pricingUrl: "https://buildkite.com/pricing",
    deploy: ["managed-cloud", "self-hosted"], pricing: "freemium", free: true, compliance: ["SOC 2"], tags: ["enterprise"],
  }),
  t("argo-cd", "Argo CD", {
    company: "CNCF", type: "tool", cats: ["ci-cd", "kubernetes"], caps: ["ci-cd", "container-orchestration"],
    desc: "Declarative GitOps continuous delivery for Kubernetes.",
    site: "https://argo-cd.readthedocs.io", docs: "https://argo-cd.readthedocs.io/en/stable/", repo: "https://github.com/argoproj/argo-cd", oss: true, license: "Apache-2.0",
    deploy: ["self-hosted"], integrations: ["kubernetes"], free: true, tags: ["gitops"], icon: "argo",
  }),
  t("sentry", "Sentry", {
    company: "Sentry", type: "service", cats: ["observability", "monitoring"], caps: ["monitoring", "logging", "tracing"],
    desc: "Error tracking, performance tracing, session replay and logs with SDKs for every frontend, mobile and backend platform. The default first monitoring tool.",
    site: "https://sentry.io", docs: "https://docs.sentry.io", repo: "https://github.com/getsentry/sentry", pricingUrl: "https://sentry.io/pricing/", oss: true, license: "FSL-1.1-Apache-2.0",
    deploy: ["managed-cloud", "self-hosted"], langs: ["typescript", "python", "go", "java", "ruby", "swift", "kotlin", "php", "csharp", "rust"], integrations: ["nextjs", "react-native", "fastapi", "github", "vercel"], pricing: "freemium", free: true, pricingSummary: "Free developer tier, then usage-based", compliance: ["SOC 2", "HIPAA", "GDPR", "ISO 27001"],
  }),
  t("datadog", "Datadog", {
    company: "Datadog", type: "service", cats: ["observability", "monitoring", "logging", "tracing", "security"], caps: ["monitoring", "logging", "tracing"],
    desc: "Full-stack enterprise observability: infrastructure metrics, APM, logs, RUM, security and LLM observability in one platform. Powerful and expensive.",
    site: "https://www.datadoghq.com", docs: "https://docs.datadoghq.com", pricingUrl: "https://www.datadoghq.com/pricing/",
    deploy: ["managed-cloud"], pricing: "subscription", free: true, pricingSummary: "Per host, per GB and per product pricing", compliance: ["SOC 2", "HIPAA", "PCI DSS", "FedRAMP", "GDPR", "ISO 27001"], tags: ["enterprise", "expensive"],
  }),
  t("grafana", "Grafana Stack", {
    company: "Grafana Labs", type: "platform", cats: ["observability", "monitoring", "logging", "tracing"], caps: ["monitoring", "logging", "tracing"],
    desc: "Open-source dashboards with Loki (logs), Tempo (traces), Mimir/Prometheus (metrics) and Grafana Cloud's generous free tier. Best open-source observability stack.",
    site: "https://grafana.com", docs: "https://grafana.com/docs/", repo: "https://github.com/grafana/grafana", pricingUrl: "https://grafana.com/pricing/", oss: true, license: "AGPL-3.0",
    deploy: ["self-hosted", "managed-cloud"], integrations: ["prometheus", "opentelemetry", "kubernetes"], pricing: "freemium", free: true, compliance: ["SOC 2", "GDPR", "HIPAA"], aliases: ["Loki", "Tempo", "Grafana Cloud"],
  }),
  t("prometheus", "Prometheus", {
    company: "CNCF", type: "tool", cats: ["monitoring"], caps: ["monitoring"],
    desc: "Open-source metrics collection and alerting with a pull model and PromQL; the Kubernetes standard.",
    site: "https://prometheus.io", docs: "https://prometheus.io/docs/", repo: "https://github.com/prometheus/prometheus", oss: true, license: "Apache-2.0",
    deploy: ["self-hosted"], integrations: ["grafana", "kubernetes"], free: true,
  }),
  t("opentelemetry", "OpenTelemetry", {
    company: "CNCF", type: "library", cats: ["observability", "tracing"], caps: ["tracing", "monitoring", "logging"],
    desc: "Vendor-neutral instrumentation standard for traces, metrics and logs; export to any backend.",
    site: "https://opentelemetry.io", docs: "https://opentelemetry.io/docs/", repo: "https://github.com/open-telemetry", oss: true, license: "Apache-2.0",
    deploy: ["self-hosted"], langs: ["typescript", "python", "go", "java", "rust", "ruby", "php", "csharp"], free: true, aliases: ["OTel"],
  }),
  t("new-relic", "New Relic", {
    company: "New Relic", type: "service", cats: ["observability", "monitoring"], caps: ["monitoring", "logging", "tracing"],
    desc: "All-in-one observability platform with a usage-based free tier including 100 GB of ingest per month.",
    site: "https://newrelic.com", docs: "https://docs.newrelic.com", pricingUrl: "https://newrelic.com/pricing",
    deploy: ["managed-cloud"], pricing: "freemium", free: true, compliance: ["SOC 2", "HIPAA", "FedRAMP", "GDPR"],
  }),
  t("honeycomb", "Honeycomb", {
    company: "Honeycomb", type: "service", cats: ["observability", "tracing"], caps: ["tracing", "monitoring"],
    desc: "Observability built around high-cardinality event data and distributed tracing for debugging production systems.",
    site: "https://www.honeycomb.io", docs: "https://docs.honeycomb.io", pricingUrl: "https://www.honeycomb.io/pricing",
    deploy: ["managed-cloud"], pricing: "freemium", free: true, compliance: ["SOC 2", "HIPAA", "GDPR"], icon: null,
  }),
  t("axiom", "Axiom", {
    company: "Axiom", type: "service", cats: ["logging", "observability"], caps: ["logging", "monitoring", "tracing"],
    desc: "Cost-efficient log and event storage with fast querying, dashboards and Vercel/Cloudflare integrations.",
    site: "https://axiom.co", docs: "https://axiom.co/docs", pricingUrl: "https://axiom.co/pricing",
    deploy: ["managed-cloud"], integrations: ["vercel", "cloudflare-workers"], pricing: "freemium", free: true, maturity: "growing", icon: null,
  }),
  t("better-stack", "Better Stack", {
    company: "Better Stack", type: "service", cats: ["monitoring", "logging"], caps: ["monitoring", "logging"],
    desc: "Uptime monitoring, incident management, status pages and log management with a clean UI.",
    site: "https://betterstack.com", docs: "https://betterstack.com/docs", pricingUrl: "https://betterstack.com/pricing",
    deploy: ["managed-cloud"], pricing: "freemium", free: true, maturity: "growing", icon: null,
  }),
  t("hashicorp-vault", "HashiCorp Vault", {
    company: "HashiCorp (IBM)", type: "platform", cats: ["secrets", "security"], caps: ["secrets"],
    desc: "Secrets management, dynamic credentials, PKI and encryption as a service; the enterprise self-hosted standard.",
    site: "https://www.vaultproject.io", docs: "https://developer.hashicorp.com/vault/docs", repo: "https://github.com/hashicorp/vault", oss: false, license: "BSL-1.1",
    deploy: ["self-hosted", "managed-cloud"], pricing: "freemium", free: true, tags: ["enterprise"], icon: "vault",
  }),
  t("aws-secrets-manager", "AWS Secrets Manager", {
    company: "Amazon", type: "service", cats: ["secrets"], caps: ["secrets"],
    desc: "Managed secret storage with rotation and IAM-based access, native to AWS workloads.",
    site: "https://aws.amazon.com/secrets-manager/", docs: "https://docs.aws.amazon.com/secretsmanager/", pricingUrl: "https://aws.amazon.com/secrets-manager/pricing/",
    deploy: ["managed-cloud"], clouds: ["aws"], pricing: "usage-based", compliance: ["HIPAA", "SOC 2", "PCI DSS", "FedRAMP"], icon: "amazonwebservices",
  }),
  t("doppler", "Doppler", {
    company: "Doppler", type: "service", cats: ["secrets"], caps: ["secrets"],
    desc: "Developer-friendly secrets manager that syncs environment variables across environments, CI and cloud providers.",
    site: "https://www.doppler.com", docs: "https://docs.doppler.com", pricingUrl: "https://www.doppler.com/pricing",
    deploy: ["managed-cloud"], pricing: "freemium", free: true, compliance: ["SOC 2", "GDPR"], icon: null,
  }),
  t("infisical", "Infisical", {
    company: "Infisical", type: "platform", cats: ["secrets"], caps: ["secrets"],
    desc: "Open-source secrets management platform with secret syncing, PKI and Kubernetes operator; self-host or cloud.",
    site: "https://infisical.com", docs: "https://infisical.com/docs", repo: "https://github.com/Infisical/infisical", oss: true, license: "MIT",
    deploy: ["self-hosted", "managed-cloud"], pricing: "freemium", free: true, compliance: ["SOC 2"], maturity: "growing", icon: null,
  }),
  t("launchdarkly", "LaunchDarkly", {
    company: "LaunchDarkly", type: "service", cats: ["feature-flags"], caps: ["feature-flags"],
    desc: "Enterprise feature management and experimentation with SDKs for every platform and strong governance.",
    site: "https://launchdarkly.com", docs: "https://docs.launchdarkly.com", pricingUrl: "https://launchdarkly.com/pricing/",
    deploy: ["managed-cloud"], pricing: "subscription", free: true, compliance: ["SOC 2", "HIPAA", "GDPR", "ISO 27001"], tags: ["enterprise"], icon: null,
  }),
  t("statsig", "Statsig", {
    company: "OpenAI", type: "service", cats: ["feature-flags", "analytics"], caps: ["feature-flags", "analytics"],
    desc: "Feature flags, experimentation and product analytics with a large free tier and warehouse-native option.",
    site: "https://www.statsig.com", docs: "https://docs.statsig.com", pricingUrl: "https://www.statsig.com/pricing",
    deploy: ["managed-cloud"], pricing: "freemium", free: true, compliance: ["SOC 2", "HIPAA", "GDPR"], icon: null,
  }),
  t("flagsmith", "Flagsmith", {
    company: "Flagsmith", type: "platform", cats: ["feature-flags"], caps: ["feature-flags"],
    desc: "Open-source feature flag and remote config service; self-host or cloud.",
    site: "https://www.flagsmith.com", docs: "https://docs.flagsmith.com", repo: "https://github.com/Flagsmith/flagsmith", oss: true, license: "BSD-3-Clause",
    deploy: ["self-hosted", "managed-cloud"], pricing: "freemium", free: true, icon: null,
  }),
  t("vanta", "Vanta", {
    company: "Vanta", type: "service", cats: ["compliance", "security"], caps: ["compliance-automation"],
    desc: "Compliance automation for SOC 2, HIPAA, ISO 27001 and GDPR with continuous control monitoring and audit workflows.",
    site: "https://www.vanta.com", docs: "https://developer.vanta.com", pricingUrl: "https://www.vanta.com/pricing",
    deploy: ["managed-cloud"], pricing: "subscription", compliance: ["SOC 2", "HIPAA", "ISO 27001", "GDPR", "PCI DSS"], icon: null,
  }),
  t("drata", "Drata", {
    company: "Drata", type: "service", cats: ["compliance", "security"], caps: ["compliance-automation"],
    desc: "Continuous compliance automation and trust center for SOC 2, HIPAA, ISO 27001 and more.",
    site: "https://drata.com", docs: "https://developers.drata.com",
    deploy: ["managed-cloud"], pricing: "subscription", compliance: ["SOC 2", "HIPAA", "ISO 27001", "GDPR", "PCI DSS"], icon: null,
  }),
  t("aptible", "Aptible", {
    company: "Aptible", type: "platform", cats: ["hosting", "compliance"], caps: ["hosting", "compliance-automation", "relational-db"],
    desc: "PaaS purpose-built for HIPAA and SOC 2 workloads with encryption, audit logging and BAAs included.",
    site: "https://www.aptible.com", docs: "https://www.aptible.com/docs", pricingUrl: "https://www.aptible.com/pricing",
    deploy: ["managed-cloud"], pricing: "subscription", compliance: ["HIPAA", "SOC 2", "HITRUST", "GDPR"], tags: ["healthcare", "regulated"], icon: null,
  }),
  t("snyk", "Snyk", {
    company: "Snyk", type: "service", cats: ["security"], caps: ["compliance-automation"],
    desc: "Developer security platform scanning dependencies, code, containers and IaC for vulnerabilities.",
    site: "https://snyk.io", docs: "https://docs.snyk.io", pricingUrl: "https://snyk.io/plans/",
    deploy: ["managed-cloud"], pricing: "freemium", free: true, compliance: ["SOC 2"],
  }),
  t("vitest", "Vitest", {
    company: "VoidZero", type: "library", cats: ["testing"], caps: ["testing"],
    desc: "Fast Vite-native unit test framework with Jest-compatible APIs.",
    site: "https://vitest.dev", docs: "https://vitest.dev/guide/", repo: "https://github.com/vitest-dev/vitest", oss: true, license: "MIT",
    deploy: ["self-hosted"], langs: ["typescript", "javascript"], free: true,
  }),
  t("pytest", "pytest", {
    type: "library", cats: ["testing"], caps: ["testing"],
    desc: "The standard Python testing framework with fixtures and a huge plugin ecosystem.",
    site: "https://docs.pytest.org", docs: "https://docs.pytest.org/en/stable/", repo: "https://github.com/pytest-dev/pytest", oss: true, license: "MIT",
    deploy: ["self-hosted"], langs: ["python"], free: true,
  }),
  t("cypress", "Cypress", {
    company: "Cypress", type: "library", cats: ["testing"], caps: ["testing"],
    desc: "End-to-end and component testing for web apps with a time-travel debugger and Cypress Cloud.",
    site: "https://www.cypress.io", docs: "https://docs.cypress.io", repo: "https://github.com/cypress-io/cypress", oss: true, license: "MIT",
    deploy: ["self-hosted", "managed-cloud"], langs: ["typescript", "javascript"], pricing: "freemium", free: true,
  }),
  t("vscode", "Visual Studio Code", {
    company: "Microsoft", type: "tool", cats: ["developer-tools"], caps: ["ide"],
    desc: "The most widely used code editor with a vast extension ecosystem.",
    site: "https://code.visualstudio.com", docs: "https://code.visualstudio.com/docs", repo: "https://github.com/microsoft/vscode", oss: true, license: "MIT",
    deploy: ["desktop"], free: true, icon: null,
  }),
  t("cursor", "Cursor", {
    company: "Anysphere", type: "tool", cats: ["developer-tools"], caps: ["ide", "coding-assistant"],
    desc: "AI-native code editor forked from VS Code with agentic editing and codebase-aware chat.",
    site: "https://cursor.com", docs: "https://docs.cursor.com", pricingUrl: "https://cursor.com/pricing",
    deploy: ["desktop"], pricing: "freemium", free: true, maturity: "growing", icon: null,
  }),
  t("claude-code", "Claude Code", {
    company: "Anthropic", type: "tool", cats: ["developer-tools", "ai-agents"], caps: ["coding-assistant"],
    desc: "Anthropic's agentic coding tool that works in the terminal, IDEs and the web to build, refactor and ship code.",
    site: "https://claude.com/claude-code", docs: "https://docs.anthropic.com/en/docs/claude-code/overview",
    deploy: ["desktop", "managed-cloud"], pricing: "subscription", maturity: "growing", icon: "claude",
  }),
  t("github-copilot", "GitHub Copilot", {
    company: "Microsoft", type: "tool", cats: ["developer-tools"], caps: ["coding-assistant"],
    desc: "AI pair programmer integrated in GitHub and major editors with code completion, chat and agent mode.",
    site: "https://github.com/features/copilot", docs: "https://docs.github.com/copilot", pricingUrl: "https://github.com/features/copilot/plans",
    deploy: ["desktop", "managed-cloud"], pricing: "subscription", free: true, icon: "githubcopilot",
  }),
  t("npm", "npm", {
    company: "Microsoft", type: "tool", cats: ["package-managers"], caps: ["package-manager"],
    desc: "The default package registry and CLI for JavaScript.",
    site: "https://www.npmjs.com", docs: "https://docs.npmjs.com", free: true, deploy: ["self-hosted"], langs: ["typescript", "javascript"],
  }),
  t("pnpm", "pnpm", {
    type: "tool", cats: ["package-managers"], caps: ["package-manager"],
    desc: "Fast, disk-efficient JavaScript package manager with strong monorepo workspace support.",
    site: "https://pnpm.io", docs: "https://pnpm.io/motivation", repo: "https://github.com/pnpm/pnpm", oss: true, license: "MIT", free: true, deploy: ["self-hosted"], langs: ["typescript", "javascript"],
  }),
  t("uv", "uv", {
    company: "Astral", type: "tool", cats: ["package-managers"], caps: ["package-manager"],
    desc: "Extremely fast Python package and project manager written in Rust, replacing pip, venv and pyenv workflows.",
    site: "https://docs.astral.sh/uv/", docs: "https://docs.astral.sh/uv/", repo: "https://github.com/astral-sh/uv", oss: true, license: "MIT", free: true, deploy: ["self-hosted"], langs: ["python"], maturity: "growing",
  }),
  t("turborepo", "Turborepo", {
    company: "Vercel", type: "tool", cats: ["developer-tools", "package-managers"], caps: ["package-manager"],
    desc: "High-performance build system for JavaScript and TypeScript monorepos with remote caching.",
    site: "https://turbo.build", docs: "https://turbo.build/repo/docs", repo: "https://github.com/vercel/turborepo", oss: true, license: "MIT", free: true, deploy: ["self-hosted"], langs: ["typescript"],
  }),
  t("tailscale", "Tailscale", {
    company: "Tailscale", type: "service", cats: ["networking", "security"], caps: ["networking", "vpn"],
    desc: "Zero-config WireGuard mesh VPN for connecting servers, devices and private services securely.",
    site: "https://tailscale.com", docs: "https://tailscale.com/kb", pricingUrl: "https://tailscale.com/pricing",
    deploy: ["managed-cloud", "self-hosted"], pricing: "freemium", free: true, compliance: ["SOC 2", "HIPAA", "GDPR"],
  }),
  t("nginx", "NGINX", {
    company: "F5", type: "tool", cats: ["networking", "api-gateways"], caps: ["networking", "api-gateway"],
    desc: "High-performance web server, reverse proxy and load balancer.",
    site: "https://nginx.org", docs: "https://nginx.org/en/docs/", repo: "https://github.com/nginx/nginx", oss: true, license: "BSD-2-Clause", free: true, deploy: ["self-hosted"],
  }),
  t("caddy", "Caddy", {
    type: "tool", cats: ["networking"], caps: ["networking"],
    desc: "Web server and reverse proxy with automatic HTTPS; the simplest way to front self-hosted services.",
    site: "https://caddyserver.com", docs: "https://caddyserver.com/docs/", repo: "https://github.com/caddyserver/caddy", oss: true, license: "Apache-2.0", free: true, deploy: ["self-hosted"],
  }),
  t("fastly", "Fastly", {
    company: "Fastly", type: "service", cats: ["cdn-edge"], caps: ["cdn", "edge-functions"],
    desc: "Edge cloud platform with instant purging, Compute edge functions and high-performance CDN used by large media sites.",
    site: "https://www.fastly.com", docs: "https://www.fastly.com/documentation/", pricingUrl: "https://www.fastly.com/pricing",
    deploy: ["managed-cloud", "edge"], pricing: "usage-based", free: true, compliance: ["SOC 2", "PCI DSS", "HIPAA", "GDPR"], tags: ["media"],
  }),
  t("amazon-cloudfront", "Amazon CloudFront", {
    company: "Amazon", type: "service", cats: ["cdn-edge"], caps: ["cdn", "edge-functions"],
    desc: "AWS CDN integrated with S3, Lambda@Edge and AWS WAF.",
    site: "https://aws.amazon.com/cloudfront/", docs: "https://docs.aws.amazon.com/cloudfront/", pricingUrl: "https://aws.amazon.com/cloudfront/pricing/",
    deploy: ["managed-cloud", "edge"], clouds: ["aws"], pricing: "usage-based", free: true, compliance: ["HIPAA", "SOC 2", "PCI DSS", "FedRAMP"], icon: "amazonwebservices",
  }),
  t("bunny-net", "bunny.net", {
    company: "bunny.net", type: "service", cats: ["cdn-edge", "storage", "video"], caps: ["cdn", "object-storage", "video-generation"],
    desc: "Affordable CDN, edge storage and video streaming with straightforward pricing.",
    site: "https://bunny.net", docs: "https://docs.bunny.net", pricingUrl: "https://bunny.net/pricing/",
    deploy: ["managed-cloud", "edge"], pricing: "usage-based", tags: ["cheap"], icon: null,
  }),
  t("coredns", "CoreDNS", {
    company: "CNCF", type: "tool", cats: ["dns", "networking"], caps: ["dns", "networking"],
    desc: "Pluggable DNS server written in Go and the default DNS for Kubernetes; self-hosted service discovery and authoritative DNS.",
    site: "https://coredns.io", docs: "https://coredns.io/manual/toc/", repo: "https://github.com/coredns/coredns", oss: true, license: "Apache-2.0",
    deploy: ["self-hosted"], langs: ["go"], integrations: ["kubernetes"], free: true, maturity: "established", tags: ["self-hosted"],
  }),
  t("powerdns", "PowerDNS", {
    company: "Open-Xchange", type: "platform", cats: ["dns"], caps: ["dns"],
    desc: "Open-source authoritative DNS server and recursor with database backends and an HTTP API, used by registrars and hosting providers.",
    site: "https://www.powerdns.com", docs: "https://doc.powerdns.com", repo: "https://github.com/PowerDNS/pdns", oss: true, license: "GPL-2.0",
    deploy: ["self-hosted"], integrations: ["postgresql", "mysql"], free: true, maturity: "established", tags: ["self-hosted"], icon: null,
  }),
  t("varnish", "Varnish Cache", {
    company: "Varnish Software", type: "tool", cats: ["cdn-edge", "caching", "networking"], caps: ["cdn", "cache", "networking"],
    desc: "Open-source HTTP accelerator and caching reverse proxy; the self-hosted way to put a CDN-grade cache in front of an origin.",
    site: "https://varnish-cache.org", docs: "https://varnish-cache.org/docs/", repo: "https://github.com/varnishcache/varnish-cache", oss: true, license: "BSD-2-Clause",
    deploy: ["self-hosted"], free: true, maturity: "established", tags: ["self-hosted", "cache"], icon: null,
  }),
  t("skypilot", "SkyPilot", {
    company: "SkyPilot", type: "framework", cats: ["gpu-compute", "ai-infrastructure"], caps: ["gpu-compute", "ml-training", "model-hosting"],
    desc: "Open-source framework that runs AI and batch jobs on any cloud or Kubernetes cluster, finding and provisioning the cheapest available GPUs.",
    site: "https://skypilot.readthedocs.io", docs: "https://skypilot.readthedocs.io", repo: "https://github.com/skypilot-org/skypilot", oss: true, license: "Apache-2.0",
    deploy: ["self-hosted", "managed-cloud"], clouds: ["aws", "gcp", "azure"], langs: ["python"], integrations: ["kubernetes"], free: true, maturity: "growing", tags: ["gpu", "multi-cloud"], icon: null,
  }),
  t("aws-route-53", "Amazon Route 53", {
    company: "Amazon", type: "service", cats: ["dns"], caps: ["dns"],
    desc: "Highly available DNS with health checks and routing policies, integrated with AWS.",
    site: "https://aws.amazon.com/route53/", docs: "https://docs.aws.amazon.com/route53/",
    deploy: ["managed-cloud"], clouds: ["aws"], pricing: "usage-based", icon: "amazonroute53",
  }),
];
