import { t } from "./helper";

export const INGESTION = [
  t("bullmq", "BullMQ", {
    company: "Taskforce.sh", type: "library", cats: ["queues"], caps: ["queue", "workers", "scheduler"],
    desc: "Redis-backed job queue for Node.js with retries, priorities, rate limiting, delayed and repeatable jobs.",
    site: "https://bullmq.io", docs: "https://docs.bullmq.io", repo: "https://github.com/taskforcesh/bullmq", oss: true, license: "MIT",
    deploy: ["self-hosted"], langs: ["typescript", "javascript", "python"], integrations: ["redis", "upstash"], free: true, icon: null,
  }),
  t("celery", "Celery", {
    type: "library", cats: ["queues"], caps: ["queue", "workers", "scheduler"],
    desc: "The standard distributed task queue for Python with Redis or RabbitMQ brokers and Celery Beat scheduling.",
    site: "https://docs.celeryq.dev", docs: "https://docs.celeryq.dev/en/stable/", repo: "https://github.com/celery/celery", oss: true, license: "BSD-3-Clause",
    deploy: ["self-hosted"], langs: ["python"], integrations: ["redis", "rabbitmq", "django", "fastapi"], free: true,
  }),
  t("sidekiq", "Sidekiq", {
    company: "Contributed Systems", type: "library", cats: ["queues"], caps: ["queue", "workers", "scheduler"],
    desc: "Efficient background job processing for Ruby backed by Redis.",
    site: "https://sidekiq.org", docs: "https://github.com/sidekiq/sidekiq/wiki", repo: "https://github.com/sidekiq/sidekiq", oss: true, license: "LGPL-3.0",
    deploy: ["self-hosted"], langs: ["ruby"], integrations: ["redis", "ruby-on-rails"], pricing: "freemium", free: true, icon: null,
  }),
  t("rabbitmq", "RabbitMQ", {
    company: "Broadcom", type: "platform", cats: ["queues"], caps: ["queue"],
    desc: "Mature AMQP message broker with flexible routing, acknowledgments and clustering.",
    site: "https://www.rabbitmq.com", docs: "https://www.rabbitmq.com/docs", repo: "https://github.com/rabbitmq/rabbitmq-server", oss: true, license: "MPL-2.0",
    deploy: ["self-hosted", "managed-cloud"], clouds: ["aws", "cloudamqp"], free: true,
  }),
  t("amazon-sqs", "Amazon SQS", {
    company: "Amazon", type: "service", cats: ["queues"], caps: ["queue"],
    desc: "Fully managed, virtually unlimited message queue; the default queue on AWS with SNS for fan-out.",
    site: "https://aws.amazon.com/sqs/", docs: "https://docs.aws.amazon.com/sqs/", pricingUrl: "https://aws.amazon.com/sqs/pricing/",
    deploy: ["managed-cloud"], clouds: ["aws"], pricing: "usage-based", free: true, compliance: ["HIPAA", "SOC 2", "PCI DSS", "FedRAMP"], aliases: ["SQS", "SNS"], icon: "amazonsqs",
  }),
  t("google-pubsub", "Google Cloud Pub/Sub", {
    company: "Google", type: "service", cats: ["queues", "streaming"], caps: ["queue", "streaming"],
    desc: "Global managed messaging for event ingestion and asynchronous integration on Google Cloud.",
    site: "https://cloud.google.com/pubsub", docs: "https://cloud.google.com/pubsub/docs", pricingUrl: "https://cloud.google.com/pubsub/pricing",
    deploy: ["managed-cloud"], clouds: ["gcp"], pricing: "usage-based", free: true, compliance: ["HIPAA", "SOC 2", "PCI DSS"], icon: "googlecloud",
  }),
  t("nats", "NATS", {
    company: "Synadia", type: "platform", cats: ["queues", "streaming"], caps: ["queue", "streaming", "realtime"],
    desc: "Lightweight, high-performance messaging system with JetStream persistence, key-value and object stores.",
    site: "https://nats.io", docs: "https://docs.nats.io", repo: "https://github.com/nats-io/nats-server", oss: true, license: "Apache-2.0",
    deploy: ["self-hosted", "managed-cloud", "edge"], free: true, icon: "natsdotio",
  }),
  t("apache-kafka", "Apache Kafka", {
    company: "Apache Software Foundation", type: "platform", cats: ["streaming", "queues"], caps: ["streaming", "queue"],
    desc: "Distributed event streaming platform for high-throughput, durable event logs with many consumers. Heavy to operate; use managed Confluent, Redpanda or MSK.",
    site: "https://kafka.apache.org", docs: "https://kafka.apache.org/documentation/", repo: "https://github.com/apache/kafka", oss: true, license: "Apache-2.0",
    deploy: ["self-hosted", "managed-cloud"], clouds: ["aws", "confluent", "gcp", "azure"], free: true, tags: ["heavy", "scale"], icon: "apachekafka",
  }),
  t("confluent", "Confluent Cloud", {
    company: "Confluent", type: "service", cats: ["streaming"], caps: ["streaming", "queue"],
    desc: "Fully managed Kafka with schema registry, connectors and Flink stream processing.",
    site: "https://www.confluent.io", docs: "https://docs.confluent.io", pricingUrl: "https://www.confluent.io/confluent-cloud/pricing/",
    deploy: ["managed-cloud"], clouds: ["aws", "gcp", "azure"], pricing: "usage-based", free: true, compliance: ["SOC 2", "HIPAA", "PCI DSS", "GDPR"], integrations: ["apache-kafka"],
  }),
  t("redpanda", "Redpanda", {
    company: "Redpanda Data", type: "platform", cats: ["streaming"], caps: ["streaming", "queue"],
    desc: "Kafka-compatible streaming platform in C++ with no ZooKeeper or JVM, simpler to operate and faster.",
    site: "https://www.redpanda.com", docs: "https://docs.redpanda.com", repo: "https://github.com/redpanda-data/redpanda", pricingUrl: "https://www.redpanda.com/pricing", oss: true, license: "BSL-1.1",
    deploy: ["self-hosted", "managed-cloud"], pricing: "freemium", free: true, integrations: ["apache-kafka"], icon: null,
  }),
  t("temporal", "Temporal", {
    company: "Temporal Technologies", type: "platform", cats: ["workflow-automation", "queues"], caps: ["workers", "scheduler", "queue"],
    desc: "Durable execution platform: write long-running, reliable workflows as code with automatic retries and state persistence. Open-source with Temporal Cloud.",
    site: "https://temporal.io", docs: "https://docs.temporal.io", repo: "https://github.com/temporalio/temporal", pricingUrl: "https://temporal.io/pricing", oss: true, license: "MIT",
    deploy: ["self-hosted", "managed-cloud"], langs: ["typescript", "python", "go", "java", "php", "csharp", "ruby"], pricing: "freemium", free: true, compliance: ["SOC 2", "HIPAA"], tags: ["durable-execution"],
  }),
  t("inngest", "Inngest", {
    company: "Inngest", type: "service", cats: ["workflow-automation", "queues"], caps: ["workers", "queue", "scheduler"],
    desc: "Event-driven durable functions that run inside your existing serverless or server app with steps, retries, concurrency and cron; great with Next.js and Vercel.",
    site: "https://www.inngest.com", docs: "https://www.inngest.com/docs", repo: "https://github.com/inngest/inngest", pricingUrl: "https://www.inngest.com/pricing", oss: true, license: "Apache-2.0",
    deploy: ["managed-cloud", "self-hosted", "serverless"], langs: ["typescript", "python", "go"], integrations: ["nextjs", "vercel"], pricing: "freemium", free: true, compliance: ["SOC 2"], maturity: "growing", tags: ["durable-functions", "serverless"], icon: null,
  }),
  t("trigger-dev", "Trigger.dev", {
    company: "Trigger.dev", type: "service", cats: ["workflow-automation", "queues"], caps: ["workers", "scheduler", "queue"],
    desc: "Open-source background jobs platform for TypeScript with long-running tasks, no timeouts, realtime progress and scheduling.",
    site: "https://trigger.dev", docs: "https://trigger.dev/docs", repo: "https://github.com/triggerdotdev/trigger.dev", pricingUrl: "https://trigger.dev/pricing", oss: true, license: "Apache-2.0",
    deploy: ["managed-cloud", "self-hosted"], langs: ["typescript"], integrations: ["nextjs", "vercel"], pricing: "freemium", free: true, maturity: "growing", icon: null,
  }),
  t("vercel-workflow", "Vercel Workflow", {
    company: "Vercel", type: "library", cats: ["workflow-automation"], caps: ["workers", "scheduler"],
    desc: "Durable workflows for TypeScript apps on Vercel: pause/resume, retries and step-based execution without a separate worker fleet.",
    site: "https://vercel.com/docs/workflow", docs: "https://vercel.com/docs/workflow",
    deploy: ["managed-cloud", "serverless"], clouds: ["vercel"], langs: ["typescript"], integrations: ["vercel", "nextjs"], pricing: "usage-based", free: true, maturity: "emerging", icon: "vercel",
  }),
  t("apache-airflow", "Apache Airflow", {
    company: "Apache Software Foundation", type: "platform", cats: ["data-engineering", "scheduling"], caps: ["etl", "scheduler", "workers"],
    desc: "The standard batch workflow orchestrator for data pipelines with DAGs defined in Python; managed by Astronomer, MWAA and Cloud Composer.",
    site: "https://airflow.apache.org", docs: "https://airflow.apache.org/docs/", repo: "https://github.com/apache/airflow", oss: true, license: "Apache-2.0",
    deploy: ["self-hosted", "managed-cloud"], langs: ["python"], free: true, tags: ["data-pipelines"], icon: "apacheairflow",
  }),
  t("dagster", "Dagster", {
    company: "Dagster Labs", type: "platform", cats: ["data-engineering", "scheduling"], caps: ["etl", "scheduler"],
    desc: "Asset-oriented data orchestrator with strong local development, testing and observability; Dagster+ cloud.",
    site: "https://dagster.io", docs: "https://docs.dagster.io", repo: "https://github.com/dagster-io/dagster", pricingUrl: "https://dagster.io/pricing", oss: true, license: "Apache-2.0",
    deploy: ["self-hosted", "managed-cloud"], langs: ["python"], pricing: "freemium", free: true, maturity: "growing", icon: null,
  }),
  t("prefect", "Prefect", {
    company: "Prefect", type: "platform", cats: ["data-engineering", "scheduling"], caps: ["etl", "scheduler", "workers"],
    desc: "Python-native workflow orchestration with minimal boilerplate and Prefect Cloud.",
    site: "https://www.prefect.io", docs: "https://docs.prefect.io", repo: "https://github.com/PrefectHQ/prefect", oss: true, license: "Apache-2.0",
    deploy: ["self-hosted", "managed-cloud"], langs: ["python"], pricing: "freemium", free: true,
  }),
  t("dbt", "dbt", {
    company: "dbt Labs", type: "tool", cats: ["etl", "data-engineering"], caps: ["etl"],
    desc: "SQL-based transformation framework for analytics engineering in the warehouse with testing and documentation.",
    site: "https://www.getdbt.com", docs: "https://docs.getdbt.com", repo: "https://github.com/dbt-labs/dbt-core", oss: true, license: "Apache-2.0",
    deploy: ["self-hosted", "managed-cloud"], langs: ["sql", "python"], integrations: ["snowflake", "bigquery", "databricks", "postgresql"], pricing: "freemium", free: true,
  }),
  t("airbyte", "Airbyte", {
    company: "Airbyte", type: "platform", cats: ["etl"], caps: ["etl"],
    desc: "Open-source ELT with hundreds of source connectors into warehouses and databases.",
    site: "https://airbyte.com", docs: "https://docs.airbyte.com", repo: "https://github.com/airbytehq/airbyte", oss: true, license: "MIT",
    deploy: ["self-hosted", "managed-cloud"], pricing: "freemium", free: true,
  }),
  t("fivetran", "Fivetran", {
    company: "Fivetran", type: "service", cats: ["etl"], caps: ["etl"],
    desc: "Fully managed data connectors with automated schema handling for warehouse loading.",
    site: "https://www.fivetran.com", docs: "https://fivetran.com/docs", pricingUrl: "https://www.fivetran.com/pricing",
    deploy: ["managed-cloud"], pricing: "usage-based", free: true, compliance: ["SOC 2", "HIPAA", "GDPR", "ISO 27001"], tags: ["enterprise"],
  }),
  t("apache-spark", "Apache Spark", {
    company: "Apache Software Foundation", type: "framework", cats: ["data-engineering", "streaming"], caps: ["etl", "streaming"],
    desc: "Distributed compute engine for large-scale batch and streaming data processing.",
    site: "https://spark.apache.org", docs: "https://spark.apache.org/docs/latest/", repo: "https://github.com/apache/spark", oss: true, license: "Apache-2.0",
    deploy: ["self-hosted", "managed-cloud"], langs: ["python", "scala", "java"], free: true, tags: ["big-data"], icon: "apachespark",
  }),
  t("apache-flink", "Apache Flink", {
    company: "Apache Software Foundation", type: "framework", cats: ["streaming"], caps: ["streaming"],
    desc: "Stateful stream processing framework for low-latency, exactly-once event pipelines.",
    site: "https://flink.apache.org", docs: "https://nightlies.apache.org/flink/flink-docs-stable/", repo: "https://github.com/apache/flink", oss: true, license: "Apache-2.0",
    deploy: ["self-hosted", "managed-cloud"], langs: ["java", "python", "sql"], free: true, icon: "apacheflink",
  }),
  t("n8n", "n8n", {
    company: "n8n", type: "platform", cats: ["workflow-automation", "ai-agents"], caps: ["workers", "scheduler", "ai-orchestration"],
    desc: "Source-available workflow automation with 400+ integrations, code nodes and AI agent nodes; self-host or cloud.",
    site: "https://n8n.io", docs: "https://docs.n8n.io", repo: "https://github.com/n8n-io/n8n", pricingUrl: "https://n8n.io/pricing/", oss: true, license: "Sustainable Use License",
    deploy: ["self-hosted", "managed-cloud"], pricing: "freemium", free: true, tags: ["low-code"],
  }),
  t("windmill", "Windmill", {
    company: "Windmill Labs", type: "platform", cats: ["workflow-automation"], caps: ["workers", "scheduler"],
    desc: "Open-source developer platform for scripts, workflows and internal apps in Python, TypeScript, Go and more.",
    site: "https://www.windmill.dev", docs: "https://www.windmill.dev/docs/intro", repo: "https://github.com/windmill-labs/windmill", oss: true, license: "AGPL-3.0",
    deploy: ["self-hosted", "managed-cloud"], pricing: "freemium", free: true, maturity: "growing", icon: null,
  }),
  t("cron-jobs", "System cron / platform cron", {
    type: "tool", cats: ["scheduling"], caps: ["scheduler"],
    desc: "Plain scheduled jobs using the host platform's cron (Vercel Cron, Cloudflare Cron Triggers, Kubernetes CronJob, Linux cron). Zero extra services for simple recurring tasks.",
    site: "https://en.wikipedia.org/wiki/Cron", oss: true, license: "Various", free: true,
    deploy: ["self-hosted", "managed-cloud", "serverless"], aliases: ["cron"], icon: null,
  }),
  t("ably", "Ably", {
    company: "Ably", type: "service", cats: ["realtime"], caps: ["realtime", "notifications"],
    desc: "Realtime pub/sub messaging with guaranteed delivery, presence and global edge; SLA-backed.",
    site: "https://ably.com", docs: "https://ably.com/docs", pricingUrl: "https://ably.com/pricing",
    deploy: ["managed-cloud"], pricing: "freemium", free: true, compliance: ["SOC 2", "HIPAA", "GDPR"], icon: null,
  }),
  t("pusher", "Pusher", {
    company: "Pusher", type: "service", cats: ["realtime", "notifications"], caps: ["realtime", "notifications"],
    desc: "Hosted WebSocket channels and push notifications with simple client SDKs.",
    site: "https://pusher.com", docs: "https://pusher.com/docs/", pricingUrl: "https://pusher.com/pricing/",
    deploy: ["managed-cloud"], pricing: "freemium", free: true,
  }),
  t("socket-io", "Socket.IO", {
    type: "library", cats: ["realtime"], caps: ["realtime"],
    desc: "Bidirectional event-based realtime library for Node.js and browsers with rooms and automatic reconnection.",
    site: "https://socket.io", docs: "https://socket.io/docs/v4/", repo: "https://github.com/socketio/socket.io", oss: true, license: "MIT",
    deploy: ["self-hosted"], langs: ["typescript", "javascript"], integrations: ["redis", "nodejs"], free: true, icon: "socketdotio",
  }),
  t("liveblocks", "Liveblocks", {
    company: "Liveblocks", type: "service", cats: ["realtime"], caps: ["realtime"],
    desc: "Realtime collaboration infrastructure: presence, comments, multiplayer editing and notifications for React apps.",
    site: "https://liveblocks.io", docs: "https://liveblocks.io/docs", pricingUrl: "https://liveblocks.io/pricing",
    deploy: ["managed-cloud"], langs: ["typescript"], frameworks: ["react", "nextjs"], pricing: "freemium", free: true, maturity: "growing", tags: ["collaboration"], icon: null,
  }),
  t("partykit", "PartyKit (Cloudflare)", {
    company: "Cloudflare", type: "platform", cats: ["realtime"], caps: ["realtime", "edge-functions"],
    desc: "Realtime multiplayer primitives on Cloudflare Durable Objects for collaborative and multiplayer apps.",
    site: "https://www.partykit.io", docs: "https://docs.partykit.io", repo: "https://github.com/partykit/partykit", oss: true, license: "MIT",
    deploy: ["edge", "managed-cloud"], clouds: ["cloudflare"], langs: ["typescript"], free: true, maturity: "emerging", icon: null,
  }),
  t("centrifugo", "Centrifugo", {
    type: "platform", cats: ["realtime"], caps: ["realtime"],
    desc: "Scalable open-source realtime messaging server (WebSocket, SSE) with presence and history, language-agnostic.",
    site: "https://centrifugal.dev", docs: "https://centrifugal.dev/docs/getting-started/introduction", repo: "https://github.com/centrifugal/centrifugo", oss: true, license: "Apache-2.0",
    deploy: ["self-hosted"], free: true, icon: null,
  }),
  t("supabase-realtime", "Supabase Realtime", {
    company: "Supabase", type: "service", cats: ["realtime"], caps: ["realtime"],
    desc: "Postgres change streams, broadcast and presence over WebSockets, included with Supabase.",
    site: "https://supabase.com/realtime", docs: "https://supabase.com/docs/guides/realtime", repo: "https://github.com/supabase/realtime", oss: true, license: "Apache-2.0",
    deploy: ["managed-cloud", "self-hosted"], integrations: ["supabase", "postgresql"], pricing: "freemium", free: true, icon: "supabase",
  }),
];
